/**
 * TANTRAMOUR 2026 — Référentiel de données commun
 * ================================================
 * Source unique pour les 3 rapports HTML.
 * Pour mettre à jour : modifier uniquement ce fichier.
 *
 * Structure de chaque entrée :
 *   jour       {string}  "Jour 1" … "Jour 7"
 *   date       {string}  "Samedi 29 aout" …
 *   heure      {string}  "9:45 - 11:00" | "Matin" | "APRES MIDI"
 *   type       {string}  catégorie (ex: "ATELIERS TANTRA (AM)")
 *   atelier    {string}  nom de l'atelier / activité
 *   lieu       {string}  salle / espace (ex: "SHIVA", "CHENREZIG" …)
 *   fac1       {string}  Animateur principal
 *   fac2       {string}  Animateur secondaire
 *   fac3       {string}  Animateur 3
 *   fac4       {string}  Animateur 4
 *   traduction {string}  Langue / traducteur
 *   helper1    {string}  Helper 1
 *   helper2    {string}  Helper 2
 *   helper3    {string}  Helper 3
 *   helper4    {string}  Helper 4
 *   angel      {string}  Angel
 *   note       {string}  Note logistique (ex: "Shift Colibri", "Atelier + long")
 *   colibri    {boolean} Vrai si un Colibri est requis pour cet atelier
 */

var AGENDA = [

  // ─── Jour 1 — Samedi 29 aout ────────────────────────────────────────
  {id:"A_7050",jour:"Jour 1",date:"Samedi 29 aout",heure:"7:30 - 10:00",type:"REPAS & PAUSE",atelier:"PETIT DEJ",lieu:"",fac1:"",fac2:"",fac3:"",fac4:"",traduction:"",helper1:"",helper2:"",helper3:"",helper4:"",angel:"",note:"",piment:0,colibri:false,logisticId:"LOG_Jour1_PETIT_DEJ_2",meetingRoles:""},
  {id:"A_3055",jour:"Jour 1",date:"Samedi 29 aout",heure:"09:00 - 14:00",type:"PREPA & LOGISTICS",atelier:"DECO temples, Acceuil, exterieur",lieu:"",fac1:"",fac2:"",fac3:"",fac4:"",traduction:"",helper1:"",helper2:"",helper3:"",helper4:"",angel:"",note:"",piment:0,colibri:false,logisticId:"",meetingRoles:""},
  {id:"A_7200",jour:"Jour 1",date:"Samedi 29 aout",heure:"11:00 - 16:00",type:"PREPA & LOGISTICS",atelier:"Tests son & sono a  SHIVA",lieu:"SHIVA",fac1:"",fac2:"",fac3:"",fac4:"",traduction:"",helper1:"",helper2:"",helper3:"",helper4:"",angel:"",note:"",piment:0,colibri:false,logisticId:"",meetingRoles:""},
  {id:"A_5970",jour:"Jour 1",date:"Samedi 29 aout",heure:"12:30 - 14:30",type:"REPAS & PAUSE",atelier:"DEJEUNER",lieu:"",fac1:"",fac2:"",fac3:"",fac4:"",traduction:"",helper1:"",helper2:"",helper3:"",helper4:"",angel:"",note:"",piment:0,colibri:false,logisticId:"",meetingRoles:""},
  {id:"A_4387",jour:"Jour 1",date:"Samedi 29 aout",heure:"14:30 - 15:30",type:"REUNION",atelier:"REUNION D'EQUIPE (Helpers)",lieu:"SHIVA",fac1:"Sabryna",fac2:"ShivaChris",fac3:"",fac4:"",traduction:"",helper1:"",helper2:"",helper3:"",helper4:"",angel:"",note:"",piment:0,colibri:false,logisticId:"JOUR1_REUNION_D_EQUIPE__HELPERS_",meetingRoles:""},
  {id:"A_1692",jour:"Jour 1",date:"Samedi 29 aout",heure:"16:00 - 17:00",type:"REUNION",atelier:"REUNION D'EQUIPE - DREAM TEAM (Tous)",lieu:"SHIVA",fac1:"ShivaChris",fac2:"Sabryna",fac3:"",fac4:"",traduction:"",helper1:"",helper2:"",helper3:"",helper4:"",angel:"",note:"",piment:0,colibri:false,logisticId:"",meetingRoles:""},
  {id:"A_7984",jour:"Jour 1",date:"Samedi 29 aout",heure:"17:00 - 18:00",type:"PREPA & LOGISTICS",atelier:"PREPA OPENING CEREMONY",lieu:"SHIVA",fac1:"",fac2:"",fac3:"",fac4:"",traduction:"",helper1:"Veronique Santini Bottemer",helper2:"Alexandre Sattler",helper3:"Yannick Bohrer",helper4:"Delphine Dupré",angel:"",note:"",piment:0,colibri:false,logisticId:"",meetingRoles:""},
  {id:"A_1133",jour:"Jour 1",date:"Samedi 29 aout",heure:"18:00 - 19:30",type:"CEREMONIE & CONCERT",atelier:"OPENING CEREMONY",lieu:"SHIVA",fac1:"Sabryna",fac2:"ShivaChris",fac3:"",fac4:"",traduction:"Sandrine Bettinelli",helper1:"Alexandre Fourcault",helper2:"Aurelie Lechardeur",helper3:"Bhaskar (Alexandre Roque)",helper4:"Carine Janez",angel:"Daniel Latapie",note:"",piment:1,colibri:false,logisticId:"JOUR1_OPENING_CEREMONY",meetingRoles:""},
  {id:"A_6419",jour:"Jour 1",date:"Samedi 29 aout",heure:"19:00 - 20:30",type:"REPAS & PAUSE",atelier:"DINNER",lieu:"",fac1:"",fac2:"",fac3:"",fac4:"",traduction:"",helper1:"",helper2:"",helper3:"",helper4:"",angel:"",note:"",piment:0,colibri:false,logisticId:"",meetingRoles:""},
  {id:"A_2322",jour:"Jour 1",date:"Samedi 29 aout",heure:"20:00 - 21:00",type:"PREPA & LOGISTICS",atelier:"PREPA CONCERT (SHIVA) - DJ Set (Ecstatic dance)",lieu:"SHIVA",fac1:"",fac2:"",fac3:"",fac4:"",traduction:"",helper1:"Frederic Chalard",helper2:"Philippe Hanrion",helper3:"Veronique Santini Bottemer",helper4:"",angel:"",note:"",piment:0,colibri:false,logisticId:"",meetingRoles:""},
  {id:"A_1929",jour:"Jour 1",date:"Samedi 29 aout",heure:"21:00 - 23:00",type:"DJ Set",atelier:"SOIREE ECSTATIC DANSE",lieu:"SHIVA",fac1:"Pascal de Lacaze",fac2:"",fac3:"",fac4:"",traduction:"",helper1:"Yannick Bohrer",helper2:"Delphine Dupré",helper3:"Boris Desvignes",helper4:"Carine Janez",angel:"Mukti (Cecile Yvorel)",note:"",piment:0,colibri:false,logisticId:"JOUR1_SOIREE_ECSTATIC_DANSE",meetingRoles:""},

  // ─── Jour 2 — Dimanche 30 aout ──────────────────────────────────────
  {id:"A_6375",jour:"Jour 2",date:"Dimanche 30 aout",heure:"08:00 - 09:00",type:"MEDITATION / YOGA",atelier:"Yoga2",lieu:"CHENREZIG",fac1:"Paul Raj Amar",fac2:"",fac3:"",fac4:"",traduction:"",helper1:"Delphine Dupré",helper2:"",helper3:"",helper4:"",angel:"",note:"",piment:1,colibri:false,logisticId:"LOG_Jour2_YOGA2",meetingRoles:""},
  {id:"A_9178",jour:"Jour 2",date:"Dimanche 30 aout",heure:"7:30 - 9:00",type:"MEDITATION / YOGA",atelier:"Meditation active",lieu:"SHAKTI",fac1:"Dorian Vallet",fac2:"",fac3:"",fac4:"",traduction:"",helper1:"Yannick Bohrer",helper2:"",helper3:"",helper4:"",angel:"",note:"",piment:1,colibri:false,logisticId:"LOG_Jour2_MEDITATION_ACTIVE",meetingRoles:""},
  {id:"A_8834",jour:"Jour 2",date:"Dimanche 30 aout",heure:"9:00 - 9:30",type:"REUNION",atelier:"REUNION D'EQUIPE (Animateurs et Artistes)",lieu:"TARA",fac1:"Sabryna",fac2:"ShivaChris",fac3:"",fac4:"",traduction:"",helper1:"",helper2:"",helper3:"",helper4:"",angel:"",note:"",piment:0,colibri:false,logisticId:"JOUR2_REUNION_D_EQUIPE__ANIMATEURS_E",meetingRoles:""},
  {id:"A_6277",jour:"Jour 2",date:"Dimanche 30 aout",heure:"7:30 - 10:00",type:"REPAS & PAUSE",atelier:"PETIT DEJ",lieu:"",fac1:"",fac2:"",fac3:"",fac4:"",traduction:"",helper1:"",helper2:"",helper3:"",helper4:"",angel:"",note:"",piment:0,colibri:false,logisticId:"",meetingRoles:""},
  {id:"A_1591",jour:"Jour 2",date:"Dimanche 30 aout",heure:"9:00 - 9:30",type:"PREPA & LOGISTICS",atelier:"PREPARATION Rassemblement",lieu:"SHIVA",fac1:"",fac2:"",fac3:"",fac4:"",traduction:"",helper1:"Frederic Chalard",helper2:"Damien Eissen",helper3:"",helper4:"",angel:"",note:"",piment:0,colibri:false,logisticId:"JOUR2_PREPARATION_RASSEMBLEMENT",meetingRoles:""},
  {id:"A_2491",jour:"Jour 2",date:"Dimanche 30 aout",heure:"9:45 - 11:00",type:"RASSEMBLEMENT",atelier:"Rassemblement",lieu:"SHIVA",fac1:"Jivan Muti (Clement Victor)",fac2:"Atman Clochette (Matthieu Chapeleau)",fac3:"",fac4:"",traduction:"Sandrine Bettinelli",helper1:"Maeva Mantione",helper2:"Linda Stachetti",helper3:"",helper4:"",angel:"",note:"",piment:1,colibri:false,logisticId:"LOG_Jour2_RASSEMBLEMENT",meetingRoles:""},
  {id:"A_6662",jour:"Jour 2",date:"Dimanche 30 aout",heure:"11:15 - 12:45",type:"ATELIERS TANTRA (Matin)",atelier:"Opening Connections",lieu:"SHIVA",fac1:"Scott McClure",fac2:"",fac3:"",fac4:"",traduction:"Delphine Dupré",helper1:"Maeva Mantione",helper2:"",helper3:"",helper4:"",angel:"Boris Desvignes",note:"",piment:1,colibri:false,logisticId:"JOUR2_OPENING_CONNECTIONS",meetingRoles:""},
  {id:"A_3187",jour:"Jour 2",date:"Dimanche 30 aout",heure:"11:15 - 12:45",type:"ATELIERS TANTRA (Matin)",atelier:"Alice : Ouverture (1/3) - Massage meditatif tantrique",lieu:"CHENREZIG",fac1:"Joe Jam",fac2:"",fac3:"",fac4:"",traduction:"",helper1:"Daniel Latapie",helper2:"Cedric Vesper",helper3:"",helper4:"",angel:"Boris Desvignes",note:"",piment:1,colibri:false,logisticId:"JOUR2_ALICE___OUVERTURE__1_3____MASS",meetingRoles:""},
  {id:"A_8885",jour:"Jour 2",date:"Dimanche 30 aout",heure:"16:00 - 17:30",type:"ATELIERS TANTRA (Apres-Midi)",atelier:"Yabyum - let love happen",lieu:"TARA",fac1:"Selma (Celine Laroche)",fac2:"",fac3:"",fac4:"",traduction:"",helper1:"Cedric Vesper",helper2:"Linda Stachetti",helper3:"",helper4:"",angel:"Virginie Bertrand",note:"",piment:2,colibri:false,logisticId:"JOUR2_YABYUM___LET_LOVE_HAPPEN",meetingRoles:""},
  {id:"A_6384",jour:"Jour 2",date:"Dimanche 30 aout",heure:"11:30 - 13:00",type:"ATELIERS TANTRA (Matin)",atelier:"Shakti puja : Le mystere des Mahavidya",lieu:"TARA",fac1:"Ishvari",fac2:"",fac3:"",fac4:"",traduction:"Linda Stachetti",helper1:"Emma Roussel",helper2:"",helper3:"",helper4:"",angel:"Boris Desvignes",note:"",piment:1,colibri:false,logisticId:"JOUR2_SHAKTI_PUJA___LE_MYSTERE_DES_M",meetingRoles:""},
  {id:"A_1991",jour:"Jour 2",date:"Dimanche 30 aout",heure:"12:00 - 13:30",type:"ATELIER ARTISTIQUE (Matin)",atelier:"Meeting Your Deity - Hypnosis & Sacred Arts Workshop",lieu:"GANESH",fac1:"Samantha Marvels",fac2:"",fac3:"",fac4:"",traduction:"Carine Janez",helper1:"Aurelie Lechardeur",helper2:"",helper3:"",helper4:"",angel:"Boris Desvignes",note:"",piment:1,colibri:false,logisticId:"JOUR2_MEETING_YOUR_DEITY___HYPNOSIS_",meetingRoles:""},
  {id:"A_7993",jour:"Jour 2",date:"Dimanche 30 aout",heure:"11:15 - 13:30",type:"SHIFT ANGEL",atelier:"Angel - Shift Matin (AM)",lieu:"EXTERIEUR",fac1:"",fac2:"",fac3:"",fac4:"",traduction:"",helper1:"",helper2:"",helper3:"",helper4:"",angel:"Boris Desvignes",note:"",piment:0,colibri:false,logisticId:"",meetingRoles:""},
  {id:"A_6296",jour:"Jour 2",date:"Dimanche 30 aout",heure:"12:30 - 14:30",type:"REPAS & PAUSE",atelier:"DEJEUNER",lieu:"",fac1:"",fac2:"",fac3:"",fac4:"",traduction:"",helper1:"",helper2:"",helper3:"",helper4:"",angel:"",note:"",piment:0,colibri:false,logisticId:"",meetingRoles:""},
  {id:"A_0514",jour:"Jour 2",date:"Dimanche 30 aout",heure:"14:30 - 16:00",type:"SUPPORT EMOTIONNEL",atelier:"SUPPORT EMOTIONNEL",lieu:"BUDDHA",fac1:"",fac2:"",fac3:"",fac4:"",traduction:"",helper1:"",helper2:"",helper3:"",helper4:"",angel:"Virginie Bertrand",note:"",piment:0,colibri:false,logisticId:"",meetingRoles:""},
  {id:"A_3149",jour:"Jour 2",date:"Dimanche 30 aout",heure:"16.00 - 17.30",type:"ATELIERS TANTRA (Apres-Midi)",atelier:"La Danse de la Polarite",lieu:"SHIVA",fac1:"Mahadevi (Tina Defoy)",fac2:"",fac3:"",fac4:"",traduction:"",helper1:"Damien Eissen",helper2:"Stephane Ahmed",helper3:"",helper4:"",angel:"Virginie Bertrand",note:"",piment:1,colibri:false,logisticId:"JOUR2_LA_DANSE_DE_LA_POLARITE",meetingRoles:""},
  {id:"A_5547",jour:"Jour 2",date:"Dimanche 30 aout",heure:"16.00 - 17.30",type:"ATELIERS TANTRA (Apres-Midi)",atelier:"Vibration à l'unisson: Tête - Coeur - Sexe",lieu:"GANESH",fac1:"Sophie O'Heix",fac2:"",fac3:"",fac4:"",traduction:"Mukti (Cecile Yvorel)",helper1:"Veronique Santini Bottemer",helper2:"",helper3:"",helper4:"",angel:"Virginie Bertrand",note:"",piment:1,colibri:false,logisticId:"JOUR2_VIBRATION___L_UNISSON__T_TE___",meetingRoles:""},
  {id:"A_8201",jour:"Jour 2",date:"Dimanche 30 aout",heure:"11:30 - 13:00",type:"ATELIERS TANTRA (Matin)",atelier:"Roue de Terre : Consentir et Communiquer",lieu:"SHAKTI",fac1:"Jivan Muti (Clement Victor)",fac2:"",fac3:"",fac4:"",traduction:"Mukti (Cecile Yvorel)",helper1:"Vera De Sousa",helper2:"",helper3:"",helper4:"",angel:"Boris Desvignes",note:"",piment:1,colibri:false,logisticId:"JOUR2_ROUE_DE_TERRE___CONSENTIR_ET_C",meetingRoles:""},

  // ─── Jour 3 — Lundi 31 aout ─────────────────────────────────────────
  {id:"A_6488",jour:"Jour 3",date:"Lundi 31 aout",heure:"16.00 - 17.30",type:"ATELIERS TANTRA (Apres-Midi)",atelier:"Cesser de Faire, Laisser Etre",lieu:"TARA",fac1:"Audrey Barthelemy",fac2:"",fac3:"",fac4:"",traduction:"Linda Stachetti",helper1:"Yannick Bohrer",helper2:"",helper3:"",helper4:"",angel:"Boris Desvignes",note:"",piment:1,colibri:false,logisticId:"JOUR2_CESSER_DE_FAIRE__LAISSER_ETRE",meetingRoles:""},

  // ─── Jour 2 — Dimanche 30 aout ──────────────────────────────────────
  {id:"A_6356",jour:"Jour 2",date:"Dimanche 30 aout",heure:"14:30 - 19:30",type:"SHIFT ANGEL",atelier:"Angel - Shift Après-midi (PM)",lieu:"EXTERIEUR",fac1:"",fac2:"",fac3:"",fac4:"",traduction:"",helper1:"",helper2:"",helper3:"",helper4:"",angel:"Virginie Bertrand",note:"",piment:0,colibri:false,logisticId:"",meetingRoles:""},
  {id:"A_1838",jour:"Jour 2",date:"Dimanche 30 aout",heure:"17.30 - 18.15",type:"REPAS & PAUSE",atelier:"GOUTER",lieu:"",fac1:"",fac2:"",fac3:"",fac4:"",traduction:"",helper1:"",helper2:"",helper3:"",helper4:"",angel:"",note:"",piment:0,colibri:false,logisticId:"",meetingRoles:""},
  {id:"A_0816",jour:"Jour 2",date:"Dimanche 30 aout",heure:"18:00 - 19:30",type:"ATELIER ARTISTIQUE (Apres-Midi)",atelier:"Danse Ecstatic Contact #1 ",lieu:"SHIVA",fac1:"Cedric Vesper",fac2:"Suman (Emmanuelle Cueff)",fac3:"",fac4:"",traduction:"",helper1:"Ishvari",helper2:"Boris Desvignes",helper3:"",helper4:"",angel:"Virginie Bertrand",note:"",piment:1,colibri:false,logisticId:"JOUR2_DANSE_ECSTATIC_CONTACT__1_",meetingRoles:""},
  {id:"A_7948",jour:"Jour 2",date:"Dimanche 30 aout",heure:"18:00 - 19:30",type:"ATELIER ARTISTIQUE (Apres-Midi)",atelier:"Move & Connect with the 5 Elements",lieu:"CHENREZIG",fac1:"Dorian Vallet",fac2:"Sevda Duroy",fac3:"",fac4:"",traduction:"",helper1:"",helper2:"David Llorca",helper3:"Bhaskar (Alexandre Roque)",helper4:"",angel:"Virginie Bertrand",note:"",piment:1,colibri:false,logisticId:"JOUR2_MOVE___CONNECT_WITH_THE_5_ELEM",meetingRoles:""},
  {id:"A_9578",jour:"Jour 2",date:"Dimanche 30 aout",heure:"18:00 - 19:30",type:"ATELIER ARTISTIQUE (Apres-Midi)",atelier:"Ecstatic Dance niveau 1 ",lieu:"SHAKTI",fac1:"Yannick Bohrer",fac2:"",fac3:"",fac4:"",traduction:"",helper1:"Vera De Sousa",helper2:"Sandrine Bettinelli",helper3:"",helper4:"",angel:"Virginie Bertrand",note:"",piment:1,colibri:false,logisticId:"LOG_Jour2_ECSTATIC_DANCE_NIVEAU_1_",meetingRoles:""},
  {id:"A_4420",jour:"Jour 2",date:"Dimanche 30 aout",heure:"18:00 - 19:30",type:"ATELIER ARTISTIQUE (Apres-Midi)",atelier:"L'Union sacree d'Hathor et Horus ",lieu:"TARA",fac1:"Philippe Hanrion",fac2:"",fac3:"",fac4:"",traduction:"Delphine Dupré",helper1:"Sophie O'Heix",helper2:"",helper3:"",helper4:"",angel:"Virginie Bertrand",note:"",piment:1,colibri:false,logisticId:"JOUR2_L_UNION_SACREE_D_HATHOR_ET_HOR",meetingRoles:""},
  {id:"A_9930",jour:"Jour 2",date:"Dimanche 30 aout",heure:"19:00 - 20:30",type:"REPAS & PAUSE",atelier:"DINNER",lieu:"",fac1:"",fac2:"",fac3:"",fac4:"",traduction:"",helper1:"",helper2:"",helper3:"",helper4:"",angel:"",note:"",piment:0,colibri:false,logisticId:"",meetingRoles:""},
  {id:"A_2860",jour:"Jour 2",date:"Dimanche 30 aout",heure:"20:00 - 21:00",type:"PREPA & LOGISTICS",atelier:"PREPA Ceremonie CACAO (SHIVA)",lieu:"SHIVA",fac1:"Amana (William Duplain)",fac2:"",fac3:"",fac4:"",traduction:"",helper1:"Frederic Chalard",helper2:"Mukti (Cecile Yvorel)",helper3:"Damien Eissen",helper4:"",angel:"",note:"",piment:0,colibri:false,logisticId:"",meetingRoles:""},
  {id:"A_5735",jour:"Jour 2",date:"Dimanche 30 aout",heure:"21:00 - 23:00",type:"CEREMONIE & CONCERT",atelier:"CEROMONIE CACAO - Dancing Heart",lieu:"SHIVA",fac1:"Amana (William Duplain)",fac2:"Ishvari",fac3:"",fac4:"",traduction:"Bhaskar (Alexandre Roque)",helper1:"Emma Roussel",helper2:"",helper3:"",helper4:"",angel:"Aurelie Lechardeur",note:"",piment:1,colibri:false,logisticId:"LOG_Jour2_CEROMONIE_CACAO___DANCING_HEAR",meetingRoles:""},
  {id:"A_0127",jour:"Jour 2",date:"Dimanche 30 aout",heure:"19:30 - 20:00",type:"PREPA & LOGISTICS",atelier:"PREPA TEMPLE (CHENREZIG) - Shibari Performance",lieu:"CHENREZIG",fac1:"Amana (William Duplain)",fac2:"Ishvari",fac3:"",fac4:"",traduction:"",helper1:"Yannick Bohrer",helper2:"Alexandre Sattler",helper3:"Veronique Santini Bottemer",helper4:"",angel:"",note:"",piment:0,colibri:false,logisticId:"",meetingRoles:""},
  {id:"A_6560",jour:"Jour 2",date:"Dimanche 30 aout",heure:"23:30 - 01:00",type:"LOVE TEMPLE",atelier:"Shibari Performance & Interactive Jam",lieu:"CHENREZIG",fac1:"Amana (William Duplain)",fac2:"Ishvari",fac3:"",fac4:"",traduction:"Bhaskar (Alexandre Roque)",helper1:"Damien Eissen",helper2:"Delphine Dupré",helper3:"",helper4:"",angel:"Aurelie Lechardeur",note:"",piment:1,colibri:false,logisticId:"JOUR2_SHIBARI_PERFORMANCE___INTERACT",meetingRoles:""},

  // ─── Jour 3 — Lundi 31 aout ─────────────────────────────────────────
  {id:"A_0480",jour:"Jour 3",date:"Lundi 31 aout",heure:"08:00 - 09:00",type:"MEDITATION / YOGA",atelier:"Yoga",lieu:"CHENREZIG",fac1:"Sevda Duroy",fac2:"",fac3:"",fac4:"",traduction:"",helper1:"Veronique Santini Bottemer",helper2:"",helper3:"",helper4:"",angel:"",note:"",piment:0,colibri:false,logisticId:"LOG_Jour3_YOGA",meetingRoles:""},
  {id:"A_1791",jour:"Jour 3",date:"Lundi 31 aout",heure:"7:30 - 9:00",type:"MEDITATION / YOGA",atelier:"Méditation active d'Osho : Laughing Drums Meditation",lieu:"SHAKTI",fac1:"Selma (Celine Laroche)",fac2:"",fac3:"",fac4:"",traduction:"",helper1:"Philippe Hanrion",helper2:"",helper3:"",helper4:"",angel:"",note:"",piment:1,colibri:false,logisticId:"LOG_Jour3_MEDITATION_ACTIVE_D_OSHO___LAU",meetingRoles:""},

  // ─── Jour 2 — Dimanche 30 aout ──────────────────────────────────────
  {id:"A_4995",jour:"Jour 2",date:"Dimanche 30 aout",heure:"9:00 - 9:30",type:"REUNION",atelier:"REUNION D'EQUIPE (Helpers)",lieu:"HANUMAN",fac1:"Dorian Vallet",fac2:"Atman Clochette (Matthieu Chapeleau)",fac3:"",fac4:"",traduction:"",helper1:"",helper2:"",helper3:"",helper4:"",angel:"",note:"",piment:0,colibri:false,logisticId:"",meetingRoles:""},

  // ─── Jour 3 — Lundi 31 aout ─────────────────────────────────────────
  {id:"A_8764",jour:"Jour 3",date:"Lundi 31 aout",heure:"7:30 - 10:00",type:"REPAS & PAUSE",atelier:"PETIT DEJ",lieu:"",fac1:"",fac2:"",fac3:"",fac4:"",traduction:"",helper1:"",helper2:"",helper3:"",helper4:"",angel:"",note:"",piment:0,colibri:false,logisticId:"",meetingRoles:""},
  {id:"A_0046",jour:"Jour 3",date:"Lundi 31 aout",heure:"9:00 - 9:30",type:"PREPA & LOGISTICS",atelier:"PREPARATION Rassemblement",lieu:"SHIVA",fac1:"",fac2:"",fac3:"",fac4:"",traduction:"",helper1:"Frederic Chalard",helper2:"Damien Eissen",helper3:"",helper4:"",angel:"",note:"",piment:0,colibri:false,logisticId:"JOUR3_PREPARATION_RASSEMBLEMENT",meetingRoles:""},
  {id:"A_6791",jour:"Jour 3",date:"Lundi 31 aout",heure:"9:45 - 11:00",type:"RASSEMBLEMENT",atelier:"Rassemblement",lieu:"SHIVA",fac1:"Jivan Muti (Clement Victor)",fac2:"Atman Clochette (Matthieu Chapeleau)",fac3:"",fac4:"",traduction:"Amana (William Duplain)",helper1:"Vera De Sousa",helper2:"Linda Stachetti",helper3:"",helper4:"",angel:"",note:"",piment:0,colibri:false,logisticId:"LOG_Jour3_RASSEMBLEMENT",meetingRoles:""},
  {id:"A_2356",jour:"Jour 3",date:"Lundi 31 aout",heure:"11:15 - 12:45",type:"ATELIERS TANTRA (Matin)",atelier:"Entre dans la caresse comme dans la vie Eternelle",lieu:"SHIVA",fac1:"Sandrine Bettinelli",fac2:"",fac3:"",fac4:"",traduction:"",helper1:"Cedric Vesper",helper2:"Maeva Mantione",helper3:"",helper4:"",angel:"Virginie Bertrand",note:"",piment:2,colibri:false,logisticId:"JOUR3_ENTRE_DANS_LA_CARESSE_COMME_DA",meetingRoles:""},
  {id:"A_4501",jour:"Jour 3",date:"Lundi 31 aout",heure:"11:15 - 12:45",type:"ATELIERS TANTRA (Matin)",atelier:"Ôde a KALI",lieu:"CHENREZIG",fac1:"Suman (Emmanuelle Cueff)",fac2:"",fac3:"",fac4:"",traduction:"Daniel Latapie",helper1:"Yannick Bohrer",helper2:"",helper3:"",helper4:"",angel:"Virginie Bertrand",note:"",piment:2,colibri:false,logisticId:"JOUR3__DE_A_KALI",meetingRoles:""},

  // ─── Jour 4 — Mardi 1 septembre ─────────────────────────────────────
  {id:"A_2021",jour:"Jour 4",date:"Mardi 1 septembre",heure:"11:30 - 13:00",type:"ATELIERS TANTRA (Matin)",atelier:"La Merkaba tantrique ",lieu:"SHAKTI",fac1:"Sabryna",fac2:"ShivaChris",fac3:"",fac4:"",traduction:"Carine Janez",helper1:"Maeva Mantione",helper2:"",helper3:"",helper4:"",angel:"Aurelie Lechardeur",note:"",piment:2,colibri:false,logisticId:"JOUR4_LA_MERKABA_TANTRIQUE_",meetingRoles:""},

  // ─── Jour 2 — Dimanche 30 aout ──────────────────────────────────────
  {id:"A_2267",jour:"Jour 2",date:"Dimanche 30 aout",heure:"16:00 - 17:30",type:"ATELIERS TANTRA (Apres-Midi)",atelier:"Plongez dans l'experience « Du plaisir » (pour femmes ou personnes identifiées)",lieu:"SHAKTI",fac1:"Audrey Barthelemy",fac2:"",fac3:"",fac4:"",traduction:"Carine Janez",helper1:"Emma Roussel",helper2:"",helper3:"",helper4:"",angel:"Virginie Bertrand",note:"Atelier Femme",piment:1,colibri:false,logisticId:"LOG_Jour2_PLONGEZ_DANS_L_EXPERIENCE___DU_2",meetingRoles:""},

  // ─── Jour 3 — Lundi 31 aout ─────────────────────────────────────────
  {id:"A_1935",jour:"Jour 3",date:"Lundi 31 aout",heure:"12:00 - 13:30",type:"ATELIERS TANTRA (Matin)",atelier:"Danse des portes multidimensionnelles de l'Etre",lieu:"GANESH",fac1:"Mahadevi (Tina Defoy)",fac2:"",fac3:"",fac4:"",traduction:"",helper1:"Kalista",helper2:"Emma Roussel",helper3:"",helper4:"",angel:"Virginie Bertrand",note:"",piment:1,colibri:false,logisticId:"JOUR3_DANSE_DES_PORTES_MULTIDIMENSIO",meetingRoles:""},
  {id:"A_1082",jour:"Jour 3",date:"Lundi 31 aout",heure:"11:15 - 13:30",type:"SHIFT ANGEL",atelier:"Angel - Shift Matin (AM)",lieu:"EXTERIEUR",fac1:"",fac2:"",fac3:"",fac4:"",traduction:"",helper1:"",helper2:"",helper3:"",helper4:"",angel:"Virginie Bertrand",note:"",piment:0,colibri:false,logisticId:"",meetingRoles:""},
  {id:"A_9749",jour:"Jour 3",date:"Lundi 31 aout",heure:"12:30 - 14:30",type:"REPAS & PAUSE",atelier:"DEJEUNER",lieu:"",fac1:"",fac2:"",fac3:"",fac4:"",traduction:"",helper1:"",helper2:"",helper3:"",helper4:"",angel:"",note:"",piment:0,colibri:false,logisticId:"",meetingRoles:""},
  {id:"A_2903",jour:"Jour 3",date:"Lundi 31 aout",heure:"14:30 - 15:00",type:"PREPA & LOGISTICS",atelier:"Prepa - POOL PARTY",lieu:"PISCINE",fac1:"",fac2:"",fac3:"",fac4:"",traduction:"",helper1:"Frederic Chalard",helper2:"",helper3:"",helper4:"",angel:"",note:"",piment:0,colibri:false,logisticId:"",meetingRoles:""},
  {id:"A_0567",jour:"Jour 3",date:"Lundi 31 aout",heure:"15:00 - 16:00",type:"POOL PARTY",atelier:"POOL PARTY - DJ Surprise",lieu:"PISCINE",fac1:"DJ Surprise",fac2:"",fac3:"",fac4:"",traduction:"",helper1:"Emma Roussel",helper2:"",helper3:"",helper4:"",angel:"Boris Desvignes",note:"",piment:0,colibri:false,logisticId:"JOUR3_POOL_PARTY_____DJ_PASCAL_DE_LA",meetingRoles:""},
  {id:"A_3375",jour:"Jour 3",date:"Lundi 31 aout",heure:"14:30 - 16:00",type:"SUPPORT EMOTIONNEL",atelier:"SUPPORT EMOTIONNEL",lieu:"BUDDHA",fac1:"",fac2:"",fac3:"",fac4:"",traduction:"",helper1:"",helper2:"",helper3:"",helper4:"",angel:"Boris Desvignes",note:"",piment:0,colibri:false,logisticId:"",meetingRoles:""},
  {id:"A_1658",jour:"Jour 3",date:"Lundi 31 aout",heure:"16.00 - 17.30",type:"ATELIERS TANTRA (Apres-Midi)",atelier:"Voyage avec la Rose (femmes)",lieu:"GANESH",fac1:"Emma Roussel",fac2:"",fac3:"",fac4:"",traduction:"Mukti (Cecile Yvorel)",helper1:"Aurelie Lechardeur",helper2:"",helper3:"",helper4:"",angel:"Boris Desvignes",note:"Atelier Femme",piment:0,colibri:false,logisticId:"JOUR3_VOYAGE_AVEC_LA_ROSE__FEMMES_",meetingRoles:""},
  {id:"A_9855",jour:"Jour 3",date:"Lundi 31 aout",heure:"16:00 - 19:00",type:"ATELIERS TANTRA (Apres-Midi)",atelier:"L'espace entre nous : un rituel entre le masculin et le féminin (3hrs)",lieu:"CHENREZIG",fac1:"Our Echo",fac2:"Guy El Hadad",fac3:"",fac4:"",traduction:"Amana (William Duplain)",helper1:"Alexandre Fourcault",helper2:"Daniel Latapie",helper3:"",helper4:"",angel:"Boris Desvignes",note:"",piment:0,colibri:false,logisticId:"JOUR3_THE_SPACE_BETWEEN_US__3HRS_",meetingRoles:""},
  {id:"A_6731",jour:"Jour 3",date:"Lundi 31 aout",heure:"16.00 - 17.30",type:"ATELIERS TANTRA (Apres-Midi)",atelier:"Yoni & Lingam Puja",lieu:"SHAKTI",fac1:"Ishvari",fac2:"",fac3:"",fac4:"",traduction:"Bhaskar (Alexandre Roque)",helper1:"Maeva Mantione",helper2:"",helper3:"",helper4:"",angel:"Boris Desvignes",note:"",piment:2,colibri:false,logisticId:"JOUR3_YONI___LINGAM_PUJA",meetingRoles:""},

  // ─── Jour 2 — Dimanche 30 aout ──────────────────────────────────────
  {id:"A_1317",jour:"Jour 2",date:"Dimanche 30 aout",heure:"18:00 - 19:30",type:"ATELIER ARTISTIQUE (Apres-Midi)",atelier:"La Saveur du Desir ",lieu:"GANESH",fac1:"Daniel Latapie",fac2:"",fac3:"",fac4:"",traduction:"",helper1:"Alexandre Sattler",helper2:"Mitsch Kohn",helper3:"",helper4:"",angel:"Virginie Bertrand",note:"",piment:1,colibri:false,logisticId:"JOUR2_LA_SAVEUR_DU_DESIR_",meetingRoles:""},

  // ─── Jour 3 — Lundi 31 aout ─────────────────────────────────────────
  {id:"A_3189",jour:"Jour 3",date:"Lundi 31 aout",heure:"14:30 - 20:00",type:"SHIFT ANGEL",atelier:"Angel - Shift Après-midi (PM)",lieu:"EXTERIEUR",fac1:"",fac2:"",fac3:"",fac4:"",traduction:"",helper1:"",helper2:"",helper3:"",helper4:"",angel:"Boris Desvignes",note:"",piment:0,colibri:false,logisticId:"",meetingRoles:""},
  {id:"A_5999",jour:"Jour 3",date:"Lundi 31 aout",heure:"17.30 - 18.15",type:"REPAS & PAUSE",atelier:"GOUTER",lieu:"",fac1:"",fac2:"",fac3:"",fac4:"",traduction:"",helper1:"",helper2:"",helper3:"",helper4:"",angel:"",note:"",piment:0,colibri:false,logisticId:"",meetingRoles:""},
  {id:"A_6747",jour:"Jour 3",date:"Lundi 31 aout",heure:"18:00 - 19:30",type:"ATELIER ARTISTIQUE (Apres-Midi)",atelier:"Alchimie du coeur (Danse médecine)",lieu:"SHAKTI",fac1:"David Llorca",fac2:"",fac3:"",fac4:"",traduction:"Carine Janez",helper1:"Veronique Santini Bottemer",helper2:"",helper3:"",helper4:"",angel:"Boris Desvignes",note:"",piment:1,colibri:false,logisticId:"JOUR3_ALCHIMIE_DU_COEUR__DANSE_M_DEC",meetingRoles:""},
  {id:"A_7616",jour:"Jour 3",date:"Lundi 31 aout",heure:"18:00 - 19:30",type:"ATELIER ARTISTIQUE (Apres-Midi)",atelier:"Danse Orgasmique - Danser la jouissance d'Etre vivant -",lieu:"GANESH",fac1:"Virginie Bertrand",fac2:"",fac3:"",fac4:"",traduction:"Mukti (Cecile Yvorel)",helper1:"Alexandre Sattler",helper2:"",helper3:"",helper4:"",angel:"Boris Desvignes",note:"",piment:1,colibri:false,logisticId:"JOUR3_DANSE_ORGASMIQUE___DANSER_LA_J",meetingRoles:""},
  {id:"A_5070",jour:"Jour 3",date:"Lundi 31 aout",heure:"18:00 - 19:30",type:"ATELIER ARTISTIQUE (Apres-Midi)",atelier:"Initiation à la danse Fusion",lieu:"TARA",fac1:"Stephane Ahmed",fac2:"",fac3:"",fac4:"",traduction:"Delphine Dupré",helper1:"Vera De Sousa",helper2:"",helper3:"",helper4:"",angel:"Boris Desvignes",note:"",piment:0,colibri:false,logisticId:"JOUR3_INITIATION_A__LA_DANSE_FUSION",meetingRoles:""},
  {id:"A_0174",jour:"Jour 3",date:"Lundi 31 aout",heure:"18:00 - 20:00",type:"ATELIER ARTISTIQUE (Apres-Midi)",atelier:"Traverser : souffle, froid et confiance (Methode Wim Hof - bain froid) (2 hr)",lieu:"SHIVA",fac1:"Damien Eissen",fac2:"Dorian Vallet",fac3:"",fac4:"",traduction:"",helper1:"Philippe Hanrion",helper2:"Cedric Vesper",helper3:"",helper4:"Atman Clochette (Matthieu Chapeleau)",angel:"Boris Desvignes",note:"Atelier + long",piment:1,colibri:false,logisticId:"JOUR3_TRAVERSER___SOUFFLE__FROID_ET_",meetingRoles:""},
  {id:"A_8181",jour:"Jour 3",date:"Lundi 31 aout",heure:"19:00 - 20:30",type:"REPAS & PAUSE",atelier:"DINNER",lieu:"",fac1:"",fac2:"",fac3:"",fac4:"",traduction:"",helper1:"",helper2:"",helper3:"",helper4:"",angel:"",note:"",piment:0,colibri:false,logisticId:"",meetingRoles:""},
  {id:"A_8378",jour:"Jour 3",date:"Lundi 31 aout",heure:"19:30 - 20:30",type:"PREPA & LOGISTICS",atelier:"PREPA CONCERT  - DJ Set",lieu:"SHAKTI",fac1:"",fac2:"",fac3:"",fac4:"",traduction:"",helper1:"Frederic Chalard",helper2:"Bhaskar (Alexandre Roque)",helper3:"",helper4:"",angel:"",note:"",piment:0,colibri:false,logisticId:"",meetingRoles:""},
  {id:"A_6162",jour:"Jour 3",date:"Lundi 31 aout",heure:"21:00 - 23:00",type:"DJ Set",atelier:"DJ Set avec Juan Felix",lieu:"SHAKTI",fac1:"Felix Ardevol",fac2:"",fac3:"",fac4:"",traduction:"",helper1:"Yannick Bohrer",helper2:"",helper3:"",helper4:"",angel:"Linda Stachetti",note:"",piment:0,colibri:false,logisticId:"JOUR3_DJ_SET_AVEC_JUAN_FELIX",meetingRoles:""},
  {id:"A_5642",jour:"Jour 3",date:"Lundi 31 aout",heure:"19:30 - 21:00",type:"PREPA & LOGISTICS",atelier:"PREPA TEMPLE (CHENREZIG) - Erotypes",lieu:"CHENREZIG",fac1:"Paul Raj Amar",fac2:"Audrey Barthelemy",fac3:"",fac4:"",traduction:"",helper1:"Delphine Dupré",helper2:"David Llorca",helper3:"",helper4:"",angel:"",note:"",piment:0,colibri:false,logisticId:"",meetingRoles:""},
  {id:"A_9272",jour:"Jour 3",date:"Lundi 31 aout",heure:"21:00 - 1:00",type:"LOVE TEMPLE",atelier:"Love Temple des Erotypes @R",lieu:"CHENREZIG",fac1:"Paul Raj Amar",fac2:"Audrey Barthelemy",fac3:"",fac4:"",traduction:"",helper1:"Delphine Dupré",helper2:"Alexandre Fourcault",helper3:"",helper4:"",angel:"Linda Stachetti",note:"",piment:2,colibri:false,logisticId:"JOUR3_LOVE_TEMPLE_DES_EROTYPES__R",meetingRoles:""},

  // ─── Jour 4 — Mardi 1 septembre ─────────────────────────────────────
  {id:"A_0389",jour:"Jour 4",date:"Mardi 1 septembre",heure:"08:00 - 09:00",type:"MEDITATION / YOGA",atelier:"Yoga",lieu:"CHENREZIG",fac1:"Sevda Duroy",fac2:"",fac3:"",fac4:"",traduction:"",helper1:"Cedric Vesper",helper2:"",helper3:"",helper4:"",angel:"",note:"",piment:0,colibri:false,logisticId:"LOG_Jour4_YOGA",meetingRoles:""},
  {id:"A_3243",jour:"Jour 4",date:"Mardi 1 septembre",heure:"7:30 - 9:00",type:"MEDITATION / YOGA",atelier:"Meditation",lieu:"SHAKTI",fac1:"ShivaChris",fac2:"",fac3:"",fac4:"",traduction:"",helper1:"Carine Janez",helper2:"",helper3:"",helper4:"",angel:"",note:"",piment:0,colibri:false,logisticId:"LOG_Jour4_MEDITATION",meetingRoles:""},
  {id:"A_7810",jour:"Jour 4",date:"Mardi 1 septembre",heure:"7:30 - 10:00",type:"REPAS & PAUSE",atelier:"PETIT DEJ",lieu:"",fac1:"",fac2:"",fac3:"",fac4:"",traduction:"",helper1:"",helper2:"",helper3:"",helper4:"",angel:"",note:"",piment:0,colibri:false,logisticId:"",meetingRoles:""},
  {id:"A_0043",jour:"Jour 4",date:"Mardi 1 septembre",heure:"9:00 - 9:30",type:"PREPA & LOGISTICS",atelier:"PREPARATION Rassemblement",lieu:"SHIVA",fac1:"",fac2:"",fac3:"",fac4:"",traduction:"",helper1:"Frederic Chalard",helper2:"Damien Eissen",helper3:"",helper4:"",angel:"",note:"",piment:0,colibri:false,logisticId:"JOUR4_PREPARATION_RASSEMBLEMENT",meetingRoles:""},
  {id:"A_2014",jour:"Jour 4",date:"Mardi 1 septembre",heure:"9:45 - 11:00",type:"RASSEMBLEMENT",atelier:"Rassemblement",lieu:"SHIVA",fac1:"Jivan Muti (Clement Victor)",fac2:"Atman Clochette (Matthieu Chapeleau)",fac3:"",fac4:"",traduction:"Sandrine Bettinelli",helper1:"Delphine Dupré",helper2:"Linda Stachetti",helper3:"",helper4:"",angel:"",note:"",piment:0,colibri:false,logisticId:"LOG_Jour4_RASSEMBLEMENT",meetingRoles:""},
  {id:"A_7026",jour:"Jour 4",date:"Mardi 1 septembre",heure:"11:15 - 12:45",type:"ATELIERS TANTRA (Matin)",atelier:"Releasing Sexual Shame & Conditioning",lieu:"SHIVA",fac1:"Samantha Marvels",fac2:"",fac3:"",fac4:"",traduction:"Mukti (Cecile Yvorel)",helper1:"Yannick Bohrer",helper2:"",helper3:"",helper4:"",angel:"Aurelie Lechardeur",note:"",piment:2,colibri:false,logisticId:"",meetingRoles:""},
  {id:"A_9468",jour:"Jour 4",date:"Mardi 1 septembre",heure:"11:15 - 12:45",type:"ATELIERS TANTRA (Matin)",atelier:"Alice - Dissolution (2/3) massage meditatif tantrique",lieu:"CHENREZIG",fac1:"Bruno Deck",fac2:"",fac3:"",fac4:"",traduction:"",helper1:"Veronique Santini Bottemer",helper2:"Alexandre Fourcault",helper3:"",helper4:"",angel:"Aurelie Lechardeur",note:"",piment:2,colibri:false,logisticId:"JOUR4_ALICE___DISSOLUTION__2_3__MASS",meetingRoles:""},

  // ─── Jour 3 — Lundi 31 aout ─────────────────────────────────────────
  {id:"A_9200",jour:"Jour 3",date:"Lundi 31 aout",heure:"11:30 - 13:00",type:"ATELIERS TANTRA (Matin)",atelier:"Le toucher comme porte vers l'extase",lieu:"SHAKTI",fac1:"Sabryna",fac2:"ShivaChris",fac3:"",fac4:"",traduction:"Bhaskar (Alexandre Roque)",helper1:"Veronique Santini Bottemer",helper2:"",helper3:"",helper4:"",angel:"Virginie Bertrand",note:"",piment:2,colibri:false,logisticId:"JOUR3_LE_TOUCHER_COMME_PORTE_VERS_L_",meetingRoles:""},

  // ─── Jour 4 — Mardi 1 septembre ─────────────────────────────────────
  {id:"A_9541",jour:"Jour 4",date:"Mardi 1 septembre",heure:"11:30 - 13:45",type:"ATELIERS TANTRA (Matin)",atelier:"Ôde à la liberte (2h15)",lieu:"TARA",fac1:"Selma (Celine Laroche)",fac2:"",fac3:"",fac4:"",traduction:"",helper1:"Emma Roussel",helper2:"Vera De Sousa",helper3:"Amana (William Duplain)",helper4:"",angel:"Aurelie Lechardeur",note:"Atelier + long",piment:2,colibri:false,logisticId:"JOUR4__DE___LA_LIBERTE__2HRS_",meetingRoles:""},
  {id:"A_0213",jour:"Jour 4",date:"Mardi 1 septembre",heure:"12:00 - 13:30",type:"ATELIERS TANTRA (Matin)",atelier:"Baladi Tao-Tantrique",lieu:"GANESH",fac1:"Mahadevi (Tina Defoy)",fac2:"",fac3:"",fac4:"",traduction:"Virginie Bertrand",helper1:"Cedric Vesper",helper2:"",helper3:"",helper4:"",angel:"Aurelie Lechardeur",note:"",piment:1,colibri:false,logisticId:"JOUR4_BALADI_TAO_TANTRIQUE",meetingRoles:""},
  {id:"A_2472",jour:"Jour 4",date:"Mardi 1 septembre",heure:"11:15 - 13:45",type:"SHIFT ANGEL",atelier:"Angel - Shift Matin (AM)",lieu:"EXTERIEUR",fac1:"",fac2:"",fac3:"",fac4:"",traduction:"",helper1:"",helper2:"",helper3:"",helper4:"",angel:"Aurelie Lechardeur",note:"",piment:0,colibri:false,logisticId:"",meetingRoles:""},
  {id:"A_0513",jour:"Jour 4",date:"Mardi 1 septembre",heure:"12:30 - 14:30",type:"REPAS & PAUSE",atelier:"DEJEUNER",lieu:"",fac1:"",fac2:"",fac3:"",fac4:"",traduction:"",helper1:"",helper2:"",helper3:"",helper4:"",angel:"",note:"",piment:0,colibri:false,logisticId:"",meetingRoles:""},
  {id:"A_0230",jour:"Jour 4",date:"Mardi 1 septembre",heure:"14:30 - 16:00",type:"SUPPORT EMOTIONNEL",atelier:"SUPPORT EMOTIONNEL",lieu:"BUDDHA",fac1:"",fac2:"",fac3:"",fac4:"",traduction:"",helper1:"",helper2:"",helper3:"",helper4:"",angel:"Linda Stachetti",note:"",piment:0,colibri:false,logisticId:"",meetingRoles:""},
  {id:"A_2564",jour:"Jour 4",date:"Mardi 1 septembre",heure:"16.00 - 17.30",type:"ATELIERS TANTRA (Apres-Midi)",atelier:"The Art of Kissing - Inspiré des Érotypes@R",lieu:"CHENREZIG",fac1:"Paul Raj Amar",fac2:"Helene Planquelle",fac3:"",fac4:"",traduction:"Delphine Dupré",helper1:"Emma Roussel",helper2:"",helper3:"",helper4:"Atman Clochette (Matthieu Chapeleau)",angel:"Linda Stachetti",note:"",piment:2,colibri:false,logisticId:"JOUR4_THE_ART_OF_KISSING_",meetingRoles:""},
  {id:"A_4021",jour:"Jour 4",date:"Mardi 1 septembre",heure:"16:00 - 19:00",type:"ATELIERS TANTRA (Apres-Midi)",atelier:"Sacred Mirrors: Grief Ceremony - Celebration of Life (3hrs)",lieu:"SHIVA",fac1:"Our Echo",fac2:"Mitsch Kohn",fac3:"",fac4:"",traduction:"Bhaskar (Alexandre Roque)",helper1:"Veronique Santini Bottemer",helper2:"",helper3:"",helper4:"",angel:"Linda Stachetti",note:"Atelier + long",piment:0,colibri:false,logisticId:"JOUR4_SACRED_MIRRORS__GRIEF_CEREMONY",meetingRoles:""},
  {id:"A_3621",jour:"Jour 4",date:"Mardi 1 septembre",heure:"16.00 - 17.30",type:"ATELIERS TANTRA (Apres-Midi)",atelier:"Roue de l'Eau : Roue du consentement & free flow massage ",lieu:"SHAKTI",fac1:"Jivan Muti (Clement Victor)",fac2:"",fac3:"",fac4:"",traduction:"Sandrine Bettinelli",helper1:"Vera De Sousa",helper2:"Maeva Mantione",helper3:"",helper4:"",angel:"Linda Stachetti",note:"",piment:2,colibri:false,logisticId:"JOUR4_ROUE_DE_L_EAU___ROUE_DU_CONSEN",meetingRoles:""},
  {id:"A_0681",jour:"Jour 4",date:"Mardi 1 septembre",heure:"16.00 - 17.30",type:"ATELIERS TANTRA (Apres-Midi)",atelier:"L'Ouroboros tantrique : cercle, souffle et alchimie",lieu:"TARA",fac1:"Damien Eissen",fac2:"",fac3:"",fac4:"",traduction:"",helper1:"Daniel Latapie",helper2:"David Llorca",helper3:"",helper4:"",angel:"Linda Stachetti",note:"",piment:2,colibri:false,logisticId:"JOUR4_L_OUROBOROS_TANTRIQUE___CERCLE",meetingRoles:""},
  {id:"A_7115",jour:"Jour 4",date:"Mardi 1 septembre",heure:"14:30 - 19:30",type:"SHIFT ANGEL",atelier:"Angel - Shift Après-midi (PM)",lieu:"EXTERIEUR",fac1:"",fac2:"",fac3:"",fac4:"",traduction:"",helper1:"",helper2:"",helper3:"",helper4:"",angel:"Linda Stachetti",note:"",piment:0,colibri:false,logisticId:"",meetingRoles:""},
  {id:"A_1767",jour:"Jour 4",date:"Mardi 1 septembre",heure:"17.30 - 18.15",type:"REPAS & PAUSE",atelier:"GOUTER",lieu:"",fac1:"",fac2:"",fac3:"",fac4:"",traduction:"",helper1:"",helper2:"",helper3:"",helper4:"",angel:"",note:"",piment:0,colibri:false,logisticId:"",meetingRoles:""},
  {id:"A_7182",jour:"Jour 4",date:"Mardi 1 septembre",heure:"18:00 - 19:30",type:"ATELIER ARTISTIQUE (Apres-Midi)",atelier:"Danse Fusion : guider / se laisser guider",lieu:"CHENREZIG",fac1:"Stephane Ahmed",fac2:"",fac3:"",fac4:"",traduction:"Virginie Bertrand",helper1:"Audrey Barthelemy",helper2:"",helper3:"",helper4:"",angel:"Linda Stachetti",note:"",piment:0,colibri:false,logisticId:"JOUR4_DANSE_FUSION___GUIDER___SE_LAI",meetingRoles:""},
  {id:"A_2634",jour:"Jour 4",date:"Mardi 1 septembre",heure:"18:00 - 19:30",type:"ATELIER ARTISTIQUE (Apres-Midi)",atelier:"Danse Ecstatic Contact #2 ",lieu:"SHAKTI",fac1:"Cedric Vesper",fac2:"Suman (Emmanuelle Cueff)",fac3:"",fac4:"",traduction:"",helper1:"Alexandre Fourcault",helper2:"Sophie O'Heix",helper3:"",helper4:"",angel:"Linda Stachetti",note:"",piment:1,colibri:false,logisticId:"JOUR4_DANSE_ECSTATIC_CONTACT__2_",meetingRoles:""},

  // ─── Jour 5 — Mercredi 2 septembre ──────────────────────────────────
  {id:"A_9222",jour:"Jour 5",date:"Mercredi 2 septembre",heure:"18:00 - 19:30",type:"ATELIER ARTISTIQUE (Apres-Midi)",atelier:"Animal Embodiment ",lieu:"TARA",fac1:"Dorian Vallet",fac2:"",fac3:"",fac4:"",traduction:"",helper1:"Virginie Bertrand",helper2:"Veronique Santini Bottemer",helper3:"",helper4:"",angel:"Aurelie Lechardeur",note:"",piment:1,colibri:false,logisticId:"JOUR5_ANIMAL_EMBODIMENT_",meetingRoles:""},

  // ─── Jour 4 — Mardi 1 septembre ─────────────────────────────────────
  {id:"A_6579",jour:"Jour 4",date:"Mardi 1 septembre",heure:"19:00 - 20:30",type:"REPAS & PAUSE",atelier:"DINNER",lieu:"",fac1:"",fac2:"",fac3:"",fac4:"",traduction:"",helper1:"",helper2:"",helper3:"",helper4:"",angel:"",note:"",piment:0,colibri:false,logisticId:"",meetingRoles:""},
  {id:"A_4817",jour:"Jour 4",date:"Mardi 1 septembre",heure:"20:00 - 21:00",type:"PREPA & LOGISTICS",atelier:"PREPA CONCERT Kelly Aura / Claude Brame (SHIVA)",lieu:"SHIVA",fac1:"",fac2:"",fac3:"",fac4:"",traduction:"",helper1:"Philippe Hanrion",helper2:"Frederic Chalard",helper3:"Delphine Dupré",helper4:"",angel:"",note:"",piment:0,colibri:false,logisticId:"",meetingRoles:""},
  {id:"A_2868",jour:"Jour 4",date:"Mardi 1 septembre",heure:"21:00 - 23:00",type:"CEREMONIE & CONCERT",atelier:"CONCERT chants & mantra avec Kelly Aura & Claude Brame",lieu:"SHIVA",fac1:"Kelly Aura",fac2:"Claude Brame",fac3:"",fac4:"",traduction:"Mukti (Cecile Yvorel)",helper1:"Damien Eissen",helper2:"Philippe Hanrion",helper3:"",helper4:"Echo Clem (Clement Marchal)",angel:"Boris Desvignes",note:"",piment:1,colibri:false,logisticId:"JOUR4_CONCERT_CHANTS___MANTRA_AVEC_K",meetingRoles:""},
  {id:"A_7424",jour:"Jour 4",date:"Mardi 1 septembre",heure:"21:00 - 22:00",type:"PREPA & LOGISTICS",atelier:"PREPA TEMPLE (CHENREZIG) - Devotion",lieu:"CHENREZIG",fac1:"Ishvari",fac2:"",fac3:"",fac4:"",traduction:"",helper1:"Emma Roussel",helper2:"Veronique Santini Bottemer",helper3:"Audrey Barthelemy",helper4:"",angel:"",note:"",piment:0,colibri:false,logisticId:"JOUR4_PREPA_TEMPLE__CHENREZIG____DEV",meetingRoles:""},
  {id:"A_0061",jour:"Jour 4",date:"Mardi 1 septembre",heure:"23:30 - 01:00",type:"LOVE TEMPLE",atelier:"Love temple devotionnel",lieu:"CHENREZIG",fac1:"Ishvari",fac2:"",fac3:"",fac4:"",traduction:"",helper1:"Bhaskar (Alexandre Roque)",helper2:"Maeva Mantione",helper3:"",helper4:"",angel:"Boris Desvignes",note:"",piment:1,colibri:false,logisticId:"JOUR4_LOVE_TEMPLE_DEVOTIONNEL",meetingRoles:""},

  // ─── Jour 5 — Mercredi 2 septembre ──────────────────────────────────
  {id:"A_8890",jour:"Jour 5",date:"Mercredi 2 septembre",heure:"7:30 - 9:00",type:"MEDITATION / YOGA",atelier:"Yoga Nidra",lieu:"CHENREZIG",fac1:"Simone Bikene",fac2:"",fac3:"",fac4:"",traduction:"",helper1:"Damien Eissen",helper2:"",helper3:"",helper4:"",angel:"",note:"",piment:1,colibri:false,logisticId:"LOG_Jour5_YOGA_NIDRA",meetingRoles:""},
  {id:"A_5826",jour:"Jour 5",date:"Mercredi 2 septembre",heure:"08:00 - 09:00",type:"MEDITATION / YOGA",atelier:"Grounding / Integrative Movement Class (suite atelier « Sacred Mirrors » de la veille : intégration)",lieu:"SHAKTI",fac1:"Our Echo",fac2:"",fac3:"",fac4:"",traduction:"Bhaskar (Alexandre Roque)",helper1:"Virginie Bertrand",helper2:"",helper3:"",helper4:"",angel:"",note:"",piment:0,colibri:false,logisticId:"JOUR5_GROUNDING___INTEGRATIVE_MOVEME",meetingRoles:""},
  {id:"A_3771",jour:"Jour 5",date:"Mercredi 2 septembre",heure:"7:30 - 10:00",type:"REPAS & PAUSE",atelier:"PETIT DEJ",lieu:"",fac1:"",fac2:"",fac3:"",fac4:"",traduction:"",helper1:"",helper2:"",helper3:"",helper4:"",angel:"",note:"",piment:0,colibri:false,logisticId:"",meetingRoles:""},
  {id:"A_2856",jour:"Jour 5",date:"Mercredi 2 septembre",heure:"9:00 - 9:30",type:"PREPA & LOGISTICS",atelier:"PREPARATION Rassemblement",lieu:"SHIVA",fac1:"",fac2:"",fac3:"",fac4:"",traduction:"",helper1:"Frederic Chalard",helper2:"Damien Eissen",helper3:"Alexandre Sattler",helper4:"",angel:"",note:"",piment:0,colibri:false,logisticId:"",meetingRoles:""},
  {id:"A_0268",jour:"Jour 5",date:"Mercredi 2 septembre",heure:"9:45 - 11:00",type:"RASSEMBLEMENT",atelier:"Rassemblement",lieu:"SHIVA",fac1:"Jivan Muti (Clement Victor)",fac2:"Atman Clochette (Matthieu Chapeleau)",fac3:"",fac4:"",traduction:"Selma (Celine Laroche)",helper1:"Vera De Sousa",helper2:"Linda Stachetti",helper3:"",helper4:"",angel:"",note:"",piment:0,colibri:false,logisticId:"LOG_Jour5_RASSEMBLEMENT",meetingRoles:""},
  {id:"A_1050",jour:"Jour 5",date:"Mercredi 2 septembre",heure:"11:15 - 12:45",type:"ATELIERS TANTRA (Matin)",atelier:"Roue du Feu : Liberation emotionnelle et Kali ",lieu:"SHIVA",fac1:"Jivan Muti (Clement Victor)",fac2:"",fac3:"",fac4:"",traduction:"Mukti (Cecile Yvorel)",helper1:"Maeva Mantione",helper2:"",helper3:"",helper4:"",angel:"Virginie Bertrand",note:"",piment:3,colibri:false,logisticId:"LOG_Jour5_ROUE_DU_FEU___LIBERATION_EMOTI",meetingRoles:""},
  {id:"A_3445",jour:"Jour 5",date:"Mercredi 2 septembre",heure:"11:15 - 12:45",type:"ATELIERS TANTRA (Matin)",atelier:"Ôde à SHIVA ",lieu:"CHENREZIG",fac1:"Suman (Emmanuelle Cueff)",fac2:"",fac3:"",fac4:"",traduction:"Delphine Dupré",helper1:"Alexandre Sattler",helper2:"",helper3:"",helper4:"",angel:"Virginie Bertrand",note:"",piment:1,colibri:false,logisticId:"JOUR5__DE___SHIVA_",meetingRoles:""},
  {id:"A_7736",jour:"Jour 5",date:"Mercredi 2 septembre",heure:"11:30 - 13:00",type:"ATELIERS TANTRA (Matin)",atelier:"Mystic Shibari - L'art du Lâcher-Prise",lieu:"SHAKTI",fac1:"Amana (William Duplain)",fac2:"",fac3:"",fac4:"",traduction:"Bhaskar (Alexandre Roque)",helper1:"Emma Roussel",helper2:"",helper3:"",helper4:"",angel:"Virginie Bertrand",note:"",piment:1,colibri:false,logisticId:"LOG_Jour5_MYSTIC_SHIBARI___L_ART_DE_LA_T",meetingRoles:""},
  {id:"A_5055",jour:"Jour 5",date:"Mercredi 2 septembre",heure:"11:30 - 13:00",type:"ATELIERS TANTRA (Matin)",atelier:"Au commencement etait le corps ",lieu:"TARA",fac1:"Sandrine Bettinelli",fac2:"",fac3:"",fac4:"",traduction:"",helper1:"Cedric Vesper",helper2:"Veronique Santini Bottemer",helper3:"",helper4:"",angel:"Virginie Bertrand",note:"",piment:3,colibri:false,logisticId:"JOUR5_AU_COMMENCEMENT_ETAIT_LE_CORPS",meetingRoles:""},

  // ─── Jour 6 — Jeudi 3 septembre ─────────────────────────────────────
  {id:"A_5665",jour:"Jour 6",date:"Jeudi 3 septembre",heure:"12:00 - 13:30",type:"ATELIER ARTISTIQUE (Matin)",atelier:"Danse de sublimation et Yi king ",lieu:"GANESH",fac1:"Boris Desvignes",fac2:"",fac3:"",fac4:"",traduction:"Virginie Bertrand",helper1:"Claude Brame",helper2:"",helper3:"",helper4:"",angel:"Aurelie Lechardeur",note:"",piment:1,colibri:false,logisticId:"JOUR6_DANSE_DE_SUBLIMATION_ET_YI_KIN",meetingRoles:""},

  // ─── Jour 5 — Mercredi 2 septembre ──────────────────────────────────
  {id:"A_7940",jour:"Jour 5",date:"Mercredi 2 septembre",heure:"12:00 - 13:30",type:"ATELIER ARTISTIQUE (Matin)",atelier:"Alchimie fluide (Danse des dauphins)",lieu:"PISCINE",fac1:"David Llorca",fac2:"",fac3:"",fac4:"",traduction:"Helene Planquelle",helper1:"Damien Eissen",helper2:"",helper3:"",helper4:"",angel:"Virginie Bertrand",note:"",piment:2,colibri:false,logisticId:"JOUR5_ALCHIMIE_FLUIDE__DANSE_DES_DAU",meetingRoles:""},
  {id:"A_0182",jour:"Jour 5",date:"Mercredi 2 septembre",heure:"11:15 - 13:30",type:"SHIFT ANGEL",atelier:"Angel - Shift Matin (AM)",lieu:"EXTERIEUR",fac1:"",fac2:"",fac3:"",fac4:"",traduction:"",helper1:"",helper2:"",helper3:"",helper4:"",angel:"Virginie Bertrand",note:"",piment:0,colibri:false,logisticId:"",meetingRoles:""},
  {id:"A_2043",jour:"Jour 5",date:"Mercredi 2 septembre",heure:"12:30 - 14:30",type:"REPAS & PAUSE",atelier:"DEJEUNER",lieu:"",fac1:"",fac2:"",fac3:"",fac4:"",traduction:"",helper1:"",helper2:"",helper3:"",helper4:"",angel:"",note:"",piment:0,colibri:false,logisticId:"",meetingRoles:""},
  {id:"A_7270",jour:"Jour 5",date:"Mercredi 2 septembre",heure:"15:00 - 16:00",type:"TANTRA CAFE",atelier:"Tantra Café - Tout ce que vous avez toujours voulu savoir sur la sexualite tantrique",lieu:"SHIVA",fac1:"Sandrine Bettinelli",fac2:"",fac3:"",fac4:"",traduction:"Linda Stachetti",helper1:"Sevda Duroy",helper2:"",helper3:"",helper4:"",angel:"",note:"",piment:1,colibri:false,logisticId:"JOUR5_TANTRA_CAFE___TOUT_CE_QUE_VOUS",meetingRoles:""},
  {id:"A_3244",jour:"Jour 5",date:"Mercredi 2 septembre",heure:"15:00 - 16:00",type:"PREPA & LOGISTICS",atelier:"Prepa - POOL PARTY",lieu:"PISCINE",fac1:"",fac2:"",fac3:"",fac4:"",traduction:"",helper1:"Frederic Chalard",helper2:"Echo Clem (Clement Marchal)",helper3:"",helper4:"",angel:"",note:"",piment:0,colibri:false,logisticId:"",meetingRoles:""},
  {id:"A_3493",jour:"Jour 5",date:"Mercredi 2 septembre",heure:"16.00 - 17.30",type:"POOL PARTY",atelier:"POOL PARTY - DJ Juan Felix",lieu:"PISCINE",fac1:"Felix Ardevol",fac2:"",fac3:"",fac4:"",traduction:"",helper1:"Alexandre Sattler",helper2:"",helper3:"",helper4:"",angel:"Aurelie Lechardeur",note:"",piment:0,colibri:false,logisticId:"JOUR5_POOL_PARTY___DJ_JUAN_FELIX",meetingRoles:""},
  {id:"A_1032",jour:"Jour 5",date:"Mercredi 2 septembre",heure:"14:30 - 16:00",type:"SUPPORT EMOTIONNEL",atelier:"SUPPORT EMOTIONNEL",lieu:"BUDDHA",fac1:"",fac2:"",fac3:"",fac4:"",traduction:"",helper1:"",helper2:"",helper3:"",helper4:"",angel:"Aurelie Lechardeur",note:"",piment:0,colibri:false,logisticId:"",meetingRoles:""},
  {id:"A_2496",jour:"Jour 5",date:"Mercredi 2 septembre",heure:"14:00 - 19:30",type:"SHIFT ANGEL",atelier:"Angel - Shift Après-midi (PM)",lieu:"EXTERIEUR",fac1:"",fac2:"",fac3:"",fac4:"",traduction:"",helper1:"",helper2:"",helper3:"",helper4:"",angel:"Aurelie Lechardeur",note:"",piment:0,colibri:false,logisticId:"",meetingRoles:""},
  {id:"A_0362",jour:"Jour 5",date:"Mercredi 2 septembre",heure:"17.30 - 18.15",type:"REPAS & PAUSE",atelier:"GOUTER",lieu:"",fac1:"",fac2:"",fac3:"",fac4:"",traduction:"",helper1:"",helper2:"",helper3:"",helper4:"",angel:"",note:"",piment:0,colibri:false,logisticId:"",meetingRoles:""},
  {id:"A_2451",jour:"Jour 5",date:"Mercredi 2 septembre",heure:"18:00 - 19:30",type:"ATELIERS TANTRA (Apres-Midi)",atelier:"Et si tu tissais le fil de ta liberte ?",lieu:"CHENREZIG",fac1:"Laurence Heitzmann",fac2:"Laurent Lacoste",fac3:"",fac4:"",traduction:"Bhaskar (Alexandre Roque)",helper1:"Philippe Hanrion",helper2:"Audrey Barthelemy",helper3:"",helper4:"",angel:"Aurelie Lechardeur",note:"",piment:2,colibri:false,logisticId:"JOUR5_ET_SI_TU_TISSAIS_LE_FIL_DE_TA_",meetingRoles:""},

  // ─── Jour 4 — Mardi 1 septembre ─────────────────────────────────────
  {id:"A_6424",jour:"Jour 4",date:"Mardi 1 septembre",heure:"18:00 - 19:30",type:"ATELIER ARTISTIQUE (Apres-Midi)",atelier:"Roue de l'Air - Poemes Medecine ",lieu:"CHENREZIG",fac1:"Jivan Muti (Clement Victor)",fac2:"Atman Clochette (Matthieu Chapeleau)",fac3:"",fac4:"",traduction:"Mukti (Cecile Yvorel)",helper1:"Maeva Mantione",helper2:"",helper3:"",helper4:"",angel:"Linda Stachetti",note:"",piment:1,colibri:false,logisticId:"JOUR4_ROUE_DE_L_AIR___POEMES_MEDECIN",meetingRoles:""},

  // ─── Jour 5 — Mercredi 2 septembre ──────────────────────────────────
  {id:"A_2970",jour:"Jour 5",date:"Mercredi 2 septembre",heure:"18:00 - 19:30",type:"ATELIER ARTISTIQUE (Apres-Midi)",atelier:"Live Méditatif Électro Accoustique & Voix ",lieu:"SHAKTI",fac1:"Suman (Emmanuelle Cueff)",fac2:"Stephane Ahmed",fac3:"",fac4:"",traduction:"Delphine Dupré",helper1:"Cedric Vesper",helper2:"",helper3:"",helper4:"",angel:"Aurelie Lechardeur",note:"",piment:1,colibri:false,logisticId:"JOUR5_LIVE_ELECTRO_ACCOUSTIQUE___VOI",meetingRoles:""},
  {id:"A_3117",jour:"Jour 5",date:"Mercredi 2 septembre",heure:"18:00 - 19:30",type:"ATELIER ARTISTIQUE (Apres-Midi)",atelier:"Glorious Bodies / Corps de gloire (bodypainting) ",lieu:"GANESH",fac1:"Paul Raj Amar",fac2:"Helene Planquelle",fac3:"",fac4:"",traduction:"",helper1:"Damien Eissen",helper2:"Emma Roussel",helper3:"",helper4:"",angel:"Aurelie Lechardeur",note:"",piment:1,colibri:false,logisticId:"JOUR5_GLORIOUS_BODIES___CORPS_DE_GLO",meetingRoles:""},
  {id:"A_9831",jour:"Jour 5",date:"Mercredi 2 septembre",heure:"19:00 - 20:30",type:"REPAS & PAUSE",atelier:"DINNER",lieu:"",fac1:"",fac2:"",fac3:"",fac4:"",traduction:"",helper1:"",helper2:"",helper3:"",helper4:"",angel:"",note:"",piment:0,colibri:false,logisticId:"",meetingRoles:""},
  {id:"A_5525",jour:"Jour 5",date:"Mercredi 2 septembre",heure:"20:00 - 21:00",type:"PREPA & LOGISTICS",atelier:"PREPA CONCERT (SHIVA) - Mitsch",lieu:"SHIVA",fac1:"",fac2:"",fac3:"",fac4:"",traduction:"",helper1:"Frederic Chalard",helper2:"Philippe Hanrion",helper3:"",helper4:"",angel:"",note:"",piment:0,colibri:false,logisticId:"",meetingRoles:""},
  {id:"A_0262",jour:"Jour 5",date:"Mercredi 2 septembre",heure:"21:00 - 23:00",type:"CEREMONIE & CONCERT",atelier:"Concert: Mitsch Kohn (& artists a  definir)",lieu:"SHIVA",fac1:"Mitsch Kohn",fac2:"Kelly Aura",fac3:"",fac4:"",traduction:"",helper1:"Philippe Hanrion",helper2:"Yannick Bohrer",helper3:"",helper4:"Echo Clem (Clement Marchal)",angel:"Daniel Latapie",note:"",piment:1,colibri:false,logisticId:"JOUR5_CONCERT__MITSCH_KOHN____ARTIST",meetingRoles:""},
  {id:"A_5258",jour:"Jour 5",date:"Mercredi 2 septembre",heure:"20:00 - 22:00",type:"PREPA & LOGISTICS",atelier:"PREPA TEMPLE (CHENREZIG) - Le mystere (Jivan & Le Splendid)",lieu:"CHENREZIG",fac1:"Jivan Muti (Clement Victor)",fac2:"Atman Clochette (Matthieu Chapeleau)",fac3:"",fac4:"",traduction:"",helper1:"Maeva Mantione",helper2:"Alexandre Fourcault",helper3:"Sandrine Bettinelli",helper4:"Dorian Vallet",angel:"",note:"",piment:0,colibri:false,logisticId:"",meetingRoles:""},
  {id:"A_2545",jour:"Jour 5",date:"Mercredi 2 septembre",heure:"23:30 - 01:00",type:"LOVE TEMPLE",atelier:"Embrasser le Mystere",lieu:"CHENREZIG",fac1:"Jivan Muti (Clement Victor)",fac2:"Atman Clochette (Matthieu Chapeleau)",fac3:"",fac4:"",traduction:"",helper1:"Vera De Sousa",helper2:"Boris Desvignes",helper3:"Maeva Mantione",helper4:"Delphine Dupré",angel:"Daniel Latapie",note:"",piment:2,colibri:false,logisticId:"JOUR5_EMBRASSER_LE_MYSTERE",meetingRoles:""},

  // ─── Jour 6 — Jeudi 3 septembre ─────────────────────────────────────
  {id:"A_0344",jour:"Jour 6",date:"Jeudi 3 septembre",heure:"7:30 - 9:00",type:"MEDITATION / YOGA",atelier:"AcroYoga ",lieu:"CHENREZIG",fac1:"Sevda Duroy",fac2:"ShivaChris",fac3:"",fac4:"",traduction:"",helper1:"Alexandre Sattler",helper2:"",helper3:"",helper4:"",angel:"",note:"",piment:0,colibri:false,logisticId:"LOG_Jour6_ACROYOGA_",meetingRoles:""},
  {id:"A_0934",jour:"Jour 6",date:"Jeudi 3 septembre",heure:"7:30 - 9:00",type:"MEDITATION / YOGA",atelier:"Mindfulness & Mouvements Somatiques",lieu:"SHAKTI",fac1:"Linda Stachetti",fac2:"",fac3:"",fac4:"",traduction:"",helper1:"Philippe Hanrion",helper2:"",helper3:"",helper4:"",angel:"",note:"",piment:0,colibri:false,logisticId:"LOG_Jour6_MINDFULNESS___MOUVEMENTS_SOMAT",meetingRoles:""},
  {id:"A_0541",jour:"Jour 6",date:"Jeudi 3 septembre",heure:"7:30 - 10:00",type:"REPAS & PAUSE",atelier:"PETIT DEJ",lieu:"",fac1:"",fac2:"",fac3:"",fac4:"",traduction:"",helper1:"",helper2:"",helper3:"",helper4:"",angel:"",note:"",piment:0,colibri:false,logisticId:"",meetingRoles:""},
  {id:"A_3529",jour:"Jour 6",date:"Jeudi 3 septembre",heure:"9:00 - 9:30",type:"PREPA & LOGISTICS",atelier:"PREPARATION Rassemblement",lieu:"SHIVA",fac1:"",fac2:"",fac3:"",fac4:"",traduction:"",helper1:"Frederic Chalard",helper2:"Damien Eissen",helper3:"",helper4:"",angel:"",note:"",piment:0,colibri:false,logisticId:"JOUR6_PREPARATION_RASSEMBLEMENT",meetingRoles:""},
  {id:"A_2957",jour:"Jour 6",date:"Jeudi 3 septembre",heure:"9:45 - 11:00",type:"RASSEMBLEMENT",atelier:"Rassemblement",lieu:"SHIVA",fac1:"Jivan Muti (Clement Victor)",fac2:"Atman Clochette (Matthieu Chapeleau)",fac3:"",fac4:"",traduction:"Amana (William Duplain)",helper1:"Veronique Santini Bottemer",helper2:"Linda Stachetti",helper3:"",helper4:"",angel:"",note:"",piment:0,colibri:false,logisticId:"LOG_Jour6_RASSEMBLEMENT",meetingRoles:""},
  {id:"A_6513",jour:"Jour 6",date:"Jeudi 3 septembre",heure:"11:15 - 12:45",type:"ATELIERS TANTRA (Matin)",atelier:"Alice : Incarnation (3/3) massage meditatif tantrique",lieu:"CHENREZIG",fac1:"Simone Bikene",fac2:"",fac3:"",fac4:"",traduction:"Dorian Vallet",helper1:"Vera De Sousa",helper2:"",helper3:"",helper4:"",angel:"Aurelie Lechardeur",note:"",piment:2,colibri:false,logisticId:"LOG_Jour6_ALICE___INCARNATION__3_3__MASS_2",meetingRoles:""},
  {id:"A_8516",jour:"Jour 6",date:"Jeudi 3 septembre",heure:"11:30 - 13:00",type:"ATELIERS TANTRA (Matin)",atelier:"Un leadership aimant",lieu:"SHAKTI",fac1:"Scott McClure",fac2:"",fac3:"",fac4:"",traduction:"Linda Stachetti",helper1:"Philippe Hanrion",helper2:"",helper3:"",helper4:"",angel:"Aurelie Lechardeur",note:"",piment:3,colibri:false,logisticId:"JOUR6_LOVING_LEADERSHIP_",meetingRoles:""},
  {id:"A_6410",jour:"Jour 6",date:"Jeudi 3 septembre",heure:"11:30 - 12:45",type:"ATELIERS TANTRA (Matin)",atelier:"La Grande Spirale du COEUR ",lieu:"TARA",fac1:"Suman (Emmanuelle Cueff)",fac2:"",fac3:"",fac4:"",traduction:"Bhaskar (Alexandre Roque)",helper1:"Maeva Mantione",helper2:"",helper3:"",helper4:"",angel:"Aurelie Lechardeur",note:"",piment:1,colibri:false,logisticId:"LOG_Jour6_LA_GRANDE_SPIRALE_DU_COEUR_",meetingRoles:""},
  {id:"A_5091",jour:"Jour 6",date:"Jeudi 3 septembre",heure:"11:15 - 13:00",type:"CONFERENCE",atelier:"Conference : Pour un tantra d'aujourd'hui ",lieu:"SHIVA",fac1:"Laurent Lacoste",fac2:"",fac3:"",fac4:"",traduction:"Selma (Celine Laroche)",helper1:"Mukti (Cecile Yvorel)",helper2:"",helper3:"",helper4:"",angel:"",note:"",piment:1,colibri:false,logisticId:"LOG_Jour6_CONFERENCE___POUR_UN_TANTRA_D_",meetingRoles:""},
  {id:"A_3790",jour:"Jour 6",date:"Jeudi 3 septembre",heure:"11:15 - 13:30",type:"SHIFT ANGEL",atelier:"Angel - Shift Matin (AM)",lieu:"EXTERIEUR",fac1:"",fac2:"",fac3:"",fac4:"",traduction:"",helper1:"",helper2:"",helper3:"",helper4:"",angel:"Aurelie Lechardeur",note:"",piment:0,colibri:false,logisticId:"",meetingRoles:""},
  {id:"A_7794",jour:"Jour 6",date:"Jeudi 3 septembre",heure:"12:30 - 14:30",type:"REPAS & PAUSE",atelier:"DEJEUNER",lieu:"",fac1:"",fac2:"",fac3:"",fac4:"",traduction:"",helper1:"",helper2:"",helper3:"",helper4:"",angel:"",note:"",piment:0,colibri:false,logisticId:"",meetingRoles:""},
  {id:"A_5389",jour:"Jour 6",date:"Jeudi 3 septembre",heure:"14:30 - 16:00",type:"SUPPORT EMOTIONNEL",atelier:"SUPPORT EMOTIONNEL",lieu:"BUDDHA",fac1:"",fac2:"",fac3:"",fac4:"",traduction:"",helper1:"",helper2:"",helper3:"",helper4:"",angel:"Virginie Bertrand",note:"",piment:0,colibri:false,logisticId:"",meetingRoles:""},
  {id:"A_6975",jour:"Jour 6",date:"Jeudi 3 septembre",heure:"16.00 - 17.30",type:"ATELIERS TANTRA (Apres-Midi)",atelier:"Alchimie relationnelle (Contact meets Tantra)",lieu:"SHIVA",fac1:"David Llorca",fac2:"",fac3:"",fac4:"",traduction:"Daniel Latapie",helper1:"Veronique Santini Bottemer",helper2:"",helper3:"",helper4:"",angel:"Virginie Bertrand",note:"",piment:1,colibri:false,logisticId:"LOG_Jour6_CONTACT_MEETS_TANTRA",meetingRoles:""},
  {id:"A_2079",jour:"Jour 6",date:"Jeudi 3 septembre",heure:"16:00 - 18:00",type:"ATELIERS TANTRA (Apres-Midi)",atelier:"Voyage au pays de mon sexe (2hrs)",lieu:"CHENREZIG",fac1:"Laurence Heitzmann",fac2:"Laurent Lacoste",fac3:"",fac4:"",traduction:"",helper1:"Damien Eissen",helper2:"Alexandre Fourcault",helper3:"",helper4:"",angel:"Virginie Bertrand",note:"Atelier + long",piment:3,colibri:false,logisticId:"JOUR6_VOYAGE_AU_PAYS_DE_MON_SEXE",meetingRoles:""},
  {id:"A_4760",jour:"Jour 6",date:"Jeudi 3 septembre",heure:"16.00 - 17.30",type:"ATELIERS TANTRA (Apres-Midi)",atelier:"Mystic Shibari - L'Art de la Transgression",lieu:"SHAKTI",fac1:"Amana (William Duplain)",fac2:"",fac3:"",fac4:"",traduction:"Bhaskar (Alexandre Roque)",helper1:"Emma Roussel",helper2:"",helper3:"",helper4:"",angel:"Virginie Bertrand",note:"",piment:3,colibri:false,logisticId:"LOG_Jour6_MYSTIC_SHIBARI__THE_ART_OF_SUR",meetingRoles:""},
  {id:"A_9285",jour:"Jour 6",date:"Jeudi 3 septembre",heure:"16.00 - 17.30",type:"ATELIERS TANTRA (Apres-Midi)",atelier:"Un bain de guerison Corps et Ame",lieu:"TARA",fac1:"Sophie O'Heix",fac2:"",fac3:"",fac4:"",traduction:"Carine Janez",helper1:"Cedric Vesper",helper2:"",helper3:"",helper4:"",angel:"Virginie Bertrand",note:"",piment:1,colibri:false,logisticId:"JOUR6_UN_BAIN_DE_GUERISON_CORPS_ET_A",meetingRoles:""},
  {id:"A_4818",jour:"Jour 6",date:"Jeudi 3 septembre",heure:"14:30 - 19:30",type:"SHIFT ANGEL",atelier:"Angel - Shift Après-midi (PM)",lieu:"EXTERIEUR",fac1:"",fac2:"",fac3:"",fac4:"",traduction:"",helper1:"",helper2:"",helper3:"",helper4:"",angel:"Virginie Bertrand",note:"",piment:0,colibri:false,logisticId:"",meetingRoles:""},
  {id:"A_6077",jour:"Jour 6",date:"Jeudi 3 septembre",heure:"17.30 - 18.15",type:"REPAS & PAUSE",atelier:"GOUTER",lieu:"",fac1:"",fac2:"",fac3:"",fac4:"",traduction:"",helper1:"",helper2:"",helper3:"",helper4:"",angel:"",note:"",piment:0,colibri:false,logisticId:"",meetingRoles:""},
  {id:"A_3509",jour:"Jour 6",date:"Jeudi 3 septembre",heure:"18:00 - 19:30",type:"ATELIER ARTISTIQUE (Apres-Midi)",atelier:"Atelier artistique « free your voice and movement playshop»",lieu:"SHIVA",fac1:"Mitsch Kohn",fac2:"",fac3:"",fac4:"",traduction:"",helper1:"Maeva Mantione",helper2:"Alexandre Sattler",helper3:"",helper4:"",angel:"Virginie Bertrand",note:"",piment:1,colibri:false,logisticId:"JOUR6_ATELIER_ARTISTIQUE___FREE_YOUR",meetingRoles:""},
  {id:"A_8702",jour:"Jour 6",date:"Jeudi 3 septembre",heure:"18:15 - 19:30",type:"ATELIER ARTISTIQUE (Apres-Midi)",atelier:"L'Art d'Etre en Mouvement ",lieu:"CHENREZIG",fac1:"Linda Stachetti",fac2:"",fac3:"",fac4:"",traduction:"",helper1:"Alexandre Fourcault",helper2:"Sevda Duroy",helper3:"",helper4:"",angel:"Virginie Bertrand",note:"",piment:1,colibri:false,logisticId:"JOUR6_L_ART_D_ETRE_EN_MOUVEMENT_",meetingRoles:""},
  {id:"A_3512",jour:"Jour 6",date:"Jeudi 3 septembre",heure:"18:00 - 19:30",type:"ATELIER ARTISTIQUE (Apres-Midi)",atelier:"Pranam : Danse Devotionnelle",lieu:"SHAKTI",fac1:"Ishvari",fac2:"",fac3:"",fac4:"",traduction:"",helper1:"Yannick Bohrer",helper2:"Philippe Hanrion",helper3:"",helper4:"",angel:"Virginie Bertrand",note:"",piment:1,colibri:false,logisticId:"JOUR6_PRANAM___DANSE_DEVOTIONNELLE",meetingRoles:""},
  {id:"A_6707",jour:"Jour 6",date:"Jeudi 3 septembre",heure:"18:00 - 19:30",type:"ATELIER ARTISTIQUE (Apres-Midi)",atelier:"Bain Mantrique - Soin Sonore Collectif",lieu:"TARA",fac1:"Suman (Emmanuelle Cueff)",fac2:"",fac3:"",fac4:"",traduction:"",helper1:"Claude Brame",helper2:"Daniel Latapie",helper3:"",helper4:"",angel:"Virginie Bertrand",note:"",piment:1,colibri:false,logisticId:"JOUR6_BAIN_MANTRIQUE___SOIN_SONORE_C",meetingRoles:""},
  {id:"A_7821",jour:"Jour 6",date:"Jeudi 3 septembre",heure:"19:00 - 20:30",type:"REPAS & PAUSE",atelier:"DINNER",lieu:"",fac1:"",fac2:"",fac3:"",fac4:"",traduction:"",helper1:"",helper2:"",helper3:"",helper4:"",angel:"",note:"",piment:0,colibri:false,logisticId:"",meetingRoles:""},
  {id:"A_1395",jour:"Jour 6",date:"Jeudi 3 septembre",heure:"20:00 - 21:00",type:"PREPA & LOGISTICS",atelier:"PREPA CONCERT - Soirée surprise (SHIVA)",lieu:"SHIVA",fac1:"",fac2:"",fac3:"",fac4:"",traduction:"",helper1:"Frederic Chalard",helper2:"Mukti (Cecile Yvorel)",helper3:"Cedric Vesper",helper4:"Philippe Hanrion",angel:"",note:"",piment:0,colibri:false,logisticId:"",meetingRoles:""},
  {id:"A_3196",jour:"Jour 6",date:"Jeudi 3 septembre",heure:"21:00 - 23:00",type:"CEREMONIE & CONCERT",atelier:"SOIREE SURPRISE pour enflammer le Chapiteau !",lieu:"SHIVA",fac1:"",fac2:"",fac3:"",fac4:"",traduction:"",helper1:"Daniel Latapie",helper2:"Cedric Vesper",helper3:"",helper4:"Atman Clochette (Matthieu Chapeleau)",angel:"Boris Desvignes",note:"",piment:1,colibri:false,logisticId:"JOUR6_SOIREE_SURPRISE_POUR_ENFLAMMER",meetingRoles:""},
  {id:"A_1055",jour:"Jour 6",date:"Jeudi 3 septembre",heure:"20:45 - 22:00",type:"PREPA & LOGISTICS",atelier:"PREPA TEMPLE (CHENREZIG) - Erotic innocence (Echo)",lieu:"CHENREZIG",fac1:"Our Echo",fac2:"",fac3:"",fac4:"",traduction:"",helper1:"Maeva Mantione",helper2:"Yannick Bohrer",helper3:"Vera De Sousa",helper4:"Bhaskar (Alexandre Roque)",angel:"",note:"",piment:0,colibri:false,logisticId:"",meetingRoles:""},
  {id:"A_3707",jour:"Jour 6",date:"Jeudi 3 septembre",heure:"23:30 - 01:00",type:"LOVE TEMPLE",atelier:"The temple of erotic innocence - An Oracular Night Ceremony",lieu:"CHENREZIG",fac1:"Our Echo",fac2:"Guy El Hadad",fac3:"",fac4:"",traduction:"Carine Janez",helper1:"Vera De Sousa",helper2:"",helper3:"",helper4:"",angel:"Boris Desvignes",note:"",piment:0,colibri:false,logisticId:"JOUR6_THE_TEMPLE_OF_EROTIC_INNOCENCE",meetingRoles:""},

  // ─── Jour 7 — Vendredi 4 septembre ──────────────────────────────────
  {id:"A_8853",jour:"Jour 7",date:"Vendredi 4 septembre",heure:"7:30 - 9:00",type:"MEDITATION / YOGA",atelier:"Yoga & automassages",lieu:"CHENREZIG",fac1:"Sevda Duroy",fac2:"",fac3:"",fac4:"",traduction:"",helper1:"Emma Roussel",helper2:"",helper3:"",helper4:"",angel:"",note:"",piment:0,colibri:false,logisticId:"LOG_Jour7_YOGA___AUTOMASSAGES",meetingRoles:""},
  {id:"A_7531",jour:"Jour 7",date:"Vendredi 4 septembre",heure:"7:30 - 10:00",type:"REPAS & PAUSE",atelier:"PETIT DEJ",lieu:"",fac1:"",fac2:"",fac3:"",fac4:"",traduction:"",helper1:"",helper2:"",helper3:"",helper4:"",angel:"",note:"",piment:0,colibri:false,logisticId:"",meetingRoles:""},
  {id:"A_4757",jour:"Jour 7",date:"Vendredi 4 septembre",heure:"10:00 - 11:00",type:"PREPA & LOGISTICS",atelier:"PREPARATION CEREMONIE DE CLOTURE",lieu:"SHIVA",fac1:"",fac2:"",fac3:"",fac4:"",traduction:"",helper1:"Frederic Chalard",helper2:"Philippe Hanrion",helper3:"Carine Janez",helper4:"Damien Eissen",angel:"",note:"",piment:0,colibri:false,logisticId:"JOUR7_PREPARATION_CEREMONIE_DE_CLOTU",meetingRoles:""},
  {id:"A_0598",jour:"Jour 7",date:"Vendredi 4 septembre",heure:"11:00 - 13:30",type:"CEREMONIE & CONCERT",atelier:"CEREMONIE DE CLOTURE",lieu:"SHIVA",fac1:"Sabryna",fac2:"ShivaChris",fac3:"",fac4:"",traduction:"Sandrine Bettinelli",helper1:"Veronique Santini Bottemer",helper2:"Yannick Bohrer",helper3:"Alexandre Fourcault",helper4:"Emma Roussel",angel:"Virginie Bertrand",note:"",piment:1,colibri:false,logisticId:"JOUR7_CEREMONIE_DE_CLOTURE",meetingRoles:""},
  {id:"A_1989",jour:"Jour 7",date:"Vendredi 4 septembre",heure:"12:30 - 14:30",type:"REPAS & PAUSE",atelier:"DEJEUNER",lieu:"",fac1:"",fac2:"",fac3:"",fac4:"",traduction:"",helper1:"",helper2:"",helper3:"",helper4:"",angel:"",note:"",piment:0,colibri:false,logisticId:"",meetingRoles:""},
  {id:"A_9908",jour:"Jour 7",date:"Vendredi 4 septembre",heure:"16:00 - 17:00",type:"REUNION",atelier:"REUNION D'EQUIPE - FINAL DEBRIEF",lieu:"TARA",fac1:"Sabryna",fac2:"ShivaChris",fac3:"",fac4:"",traduction:"",helper1:"",helper2:"",helper3:"",helper4:"",angel:"",note:"",piment:0,colibri:false,logisticId:"JOUR7_REUNION_D_EQUIPE___FINAL_DEBRI",meetingRoles:""},
  {id:"A_7910",jour:"Jour 7",date:"Vendredi 4 septembre",heure:"15:00 - 19:00",type:"PREPA & LOGISTICS",atelier:"RANGEMENT",lieu:"",fac1:"",fac2:"",fac3:"",fac4:"",traduction:"",helper1:"",helper2:"",helper3:"",helper4:"",angel:"",note:"",piment:0,colibri:false,logisticId:"",meetingRoles:""},

  // ─── Jour 2 — Dimanche 30 aout ──────────────────────────────────────
  {id:"A_5466",jour:"Jour 2",date:"Dimanche 30 aout",heure:"16.00 - 17.30",type:"ATELIERS TANTRA (Apres-Midi)",atelier:"Un parcours somatique à la découverte de la masculinité. Entre hommes, par des hommes.",lieu:"CHENREZIG",fac1:"Guy El Hadad",fac2:"",fac3:"",fac4:"",traduction:"Bhaskar (Alexandre Roque)",helper1:"Alexandre Fourcault",helper2:"Dorian Vallet",helper3:"",helper4:"",angel:"Virginie Bertrand",note:"Atelier Homme",piment:1,colibri:false,logisticId:"JOUR2_INMEN___HELD_BY_MEN_A_SOMATIC_",meetingRoles:""},

  // ─── Jour 3 — Lundi 31 aout ─────────────────────────────────────────
  {id:"A_1618",jour:"Jour 3",date:"Lundi 31 aout",heure:"11:30 - 13:00",type:"ATELIERS TANTRA (Matin)",atelier:"L'Eros dansant",lieu:"TARA",fac1:"Guy El Hadad",fac2:"",fac3:"",fac4:"",traduction:"Mukti (Cecile Yvorel)",helper1:"Alexandre Sattler",helper2:"",helper3:"",helper4:"",angel:"Virginie Bertrand",note:"",piment:0,colibri:false,logisticId:"JOUR3_DANCING_EROS",meetingRoles:""},

  // ─── Jour 4 — Mardi 1 septembre ─────────────────────────────────────
  {id:"A_8494",jour:"Jour 4",date:"Mardi 1 septembre",heure:"18:00 - 19:30",type:"ATELIER ARTISTIQUE (Apres-Midi)",atelier:"Ecstatic Dance en silent disco",lieu:"EXTERIEUR",fac1:"Yannick Bohrer",fac2:"",fac3:"",fac4:"",traduction:"Carine Janez",helper1:"Frederic Chalard",helper2:"",helper3:"",helper4:"",angel:"Linda Stachetti",note:"",piment:1,colibri:false,logisticId:"JOUR4_ECSTATIC_DANCE_EN_SILENT_DISCO",meetingRoles:""},

  // ─── Jour 5 — Mercredi 2 septembre ──────────────────────────────────
  {id:"A_2488",jour:"Jour 5",date:"Mercredi 2 septembre",heure:"12:00 - 13:30",type:"ATELIER ARTISTIQUE (Matin)",atelier:"L'art de devenir un amant d'exception par l'harmonie et la présence",lieu:"GANESH",fac1:"Samantha Marvels",fac2:"Scott McClure",fac3:"",fac4:"",traduction:"Carine Janez",helper1:"Boris Desvignes",helper2:"",helper3:"",helper4:"",angel:"Virginie Bertrand",note:"",piment:2,colibri:false,logisticId:"",meetingRoles:""},

  // ─── Jour 2 — Dimanche 30 aout ──────────────────────────────────────
  {id:"A_5225",jour:"Jour 2",date:"Dimanche 30 aout",heure:"21:00 - 01:00",type:"SHIFT ANGEL",atelier:"Angel - Shift Soir (Soirée)",lieu:"EXTERIEUR",fac1:"",fac2:"",fac3:"",fac4:"",traduction:"",helper1:"",helper2:"",helper3:"",helper4:"",angel:"Aurelie Lechardeur",note:"",piment:0,colibri:false,logisticId:"",meetingRoles:""},

  // ─── Jour 3 — Lundi 31 aout ─────────────────────────────────────────
  {id:"A_8483",jour:"Jour 3",date:"Lundi 31 aout",heure:"21:00 - 01:00",type:"SHIFT ANGEL",atelier:"Angel - Shift Soir (Soirée)",lieu:"EXTERIEUR",fac1:"",fac2:"",fac3:"",fac4:"",traduction:"",helper1:"",helper2:"",helper3:"",helper4:"",angel:"Linda Stachetti",note:"",piment:0,colibri:false,logisticId:"",meetingRoles:""},

  // ─── Jour 4 — Mardi 1 septembre ─────────────────────────────────────
  {id:"A_8734",jour:"Jour 4",date:"Mardi 1 septembre",heure:"21:00 - 01:00",type:"SHIFT ANGEL",atelier:"Angel - Shift Soir (Soirée)",lieu:"EXTERIEUR",fac1:"",fac2:"",fac3:"",fac4:"",traduction:"",helper1:"",helper2:"",helper3:"",helper4:"",angel:"Boris Desvignes",note:"",piment:0,colibri:false,logisticId:"",meetingRoles:""},

  // ─── Jour 5 — Mercredi 2 septembre ──────────────────────────────────
  {id:"A_0616",jour:"Jour 5",date:"Mercredi 2 septembre",heure:"21:00 - 01:00",type:"SHIFT ANGEL",atelier:"Angel - Shift Soir (Soirée)",lieu:"EXTERIEUR",fac1:"",fac2:"",fac3:"",fac4:"",traduction:"",helper1:"",helper2:"",helper3:"",helper4:"",angel:"Daniel Latapie",note:"",piment:0,colibri:false,logisticId:"",meetingRoles:""},

  // ─── Jour 6 — Jeudi 3 septembre ─────────────────────────────────────
  {id:"A_8051",jour:"Jour 6",date:"Jeudi 3 septembre",heure:"21:00 - 01:00",type:"SHIFT ANGEL",atelier:"Angel - Shift Soir (Soirée)",lieu:"EXTERIEUR",fac1:"",fac2:"",fac3:"",fac4:"",traduction:"",helper1:"",helper2:"",helper3:"",helper4:"",angel:"Boris Desvignes",note:"",piment:0,colibri:false,logisticId:"",meetingRoles:""},

  // ─── Jour 7 — Vendredi 4 septembre ──────────────────────────────────
  {id:"A_5740",jour:"Jour 7",date:"Vendredi 4 septembre",heure:"11:00 - 13:30",type:"SHIFT ANGEL",atelier:"Angel - Shift Matin (AM)",lieu:"EXTERIEUR",fac1:"",fac2:"",fac3:"",fac4:"",traduction:"",helper1:"",helper2:"",helper3:"",helper4:"",angel:"Virginie Bertrand",note:"",piment:0,colibri:false,logisticId:"",meetingRoles:""},

  // ─── Jour 1 — Samedi 29 aout ────────────────────────────────────────
  {id:"A_8076",jour:"Jour 1",date:"Samedi 29 aout",heure:"21:00 - 23:00",type:"SHIFT ANGEL",atelier:"Angel - Shift Soir (Soirée)",lieu:"EXTERIEUR",fac1:"",fac2:"",fac3:"",fac4:"",traduction:"",helper1:"",helper2:"",helper3:"",helper4:"",angel:"Mukti (Cecile Yvorel)",note:"",piment:0,colibri:false,logisticId:"",meetingRoles:""},
  {id:"A_1573",jour:"Jour 1",date:"Samedi 29 aout",heure:"18:00 - 19:30",type:"SHIFT ANGEL",atelier:"Angel - Shift Après-midi (PM)",lieu:"EXTERIEUR",fac1:"",fac2:"",fac3:"",fac4:"",traduction:"",helper1:"",helper2:"",helper3:"",helper4:"",angel:"Daniel Latapie",note:"",piment:0,colibri:false,logisticId:"",meetingRoles:""},
  {id:"A_6954",jour:"Jour 1",date:"Samedi 29 aout",heure:"18:00 - 19:30",type:"PREPA & LOGISTICS",atelier:"EXTRA SUPPORT - OPENING CEREMONY",lieu:"SHIVA",fac1:"",fac2:"",fac3:"",fac4:"",traduction:"",helper1:"Damien Eissen",helper2:"Emma Roussel",helper3:"Maeva Mantione",helper4:"Cedric Vesper",angel:"",note:"",piment:0,colibri:false,logisticId:"JOUR1_EXTRA_SUPPORT___OPENING_CEREMO",meetingRoles:""},

  // ─── Jour 7 — Vendredi 4 septembre ──────────────────────────────────
  {id:"A_7823",jour:"Jour 7",date:"Vendredi 4 septembre",heure:"11:00 - 13:30",type:"PREPA & LOGISTICS",atelier:"EXTRA SUPPORT - CEREMONIE DE CLOTURE",lieu:"SHIVA",fac1:"",fac2:"",fac3:"",fac4:"",traduction:"",helper1:"Boris Desvignes",helper2:"Carine Janez",helper3:"Philippe Hanrion",helper4:"Damien Eissen",angel:"",note:"",piment:0,colibri:false,logisticId:"",meetingRoles:""},

  // ─── Jour 2 — Dimanche 30 aout ──────────────────────────────────────
  {id:"A_9412",jour:"Jour 2",date:"Dimanche 30 aout",heure:"09:30 - 09:45",type:"PREPA & LOGISTICS",atelier:"\"CALL\" pour Rassemblement",lieu:"EXTERIEUR",fac1:"",fac2:"",fac3:"",fac4:"",traduction:"",helper1:"David Llorca",helper2:"Boris Desvignes",helper3:"Bhaskar (Alexandre Roque)",helper4:"",angel:"",note:"",piment:0,colibri:false,logisticId:"JOUR2__CALL__POUR_RASSEMBLEMENT",meetingRoles:""},

  // ─── Jour 3 — Lundi 31 aout ─────────────────────────────────────────
  {id:"A_8264",jour:"Jour 3",date:"Lundi 31 aout",heure:"09:30 - 09:45",type:"PREPA & LOGISTICS",atelier:"\"CALL\" pour Rassemblement",lieu:"EXTERIEUR",fac1:"",fac2:"",fac3:"",fac4:"",traduction:"",helper1:"Emma Roussel",helper2:"Carine Janez",helper3:"Stephane Ahmed",helper4:"",angel:"",note:"",piment:0,colibri:false,logisticId:"JOUR3__CALL__POUR_RASSEMBLEMENT",meetingRoles:""},

  // ─── Jour 4 — Mardi 1 septembre ─────────────────────────────────────
  {id:"A_4341",jour:"Jour 4",date:"Mardi 1 septembre",heure:"09:30 - 09:45",type:"PREPA & LOGISTICS",atelier:"\"CALL\" pour Rassemblement",lieu:"EXTERIEUR",fac1:"",fac2:"",fac3:"",fac4:"",traduction:"",helper1:"Philippe Hanrion",helper2:"Vera De Sousa",helper3:"Veronique Santini Bottemer",helper4:"",angel:"",note:"",piment:0,colibri:false,logisticId:"JOUR4__CALL__POUR_RASSEMBLEMENT",meetingRoles:""},

  // ─── Jour 5 — Mercredi 2 septembre ──────────────────────────────────
  {id:"A_6987",jour:"Jour 5",date:"Mercredi 2 septembre",heure:"09:30 - 09:45",type:"PREPA & LOGISTICS",atelier:"\"CALL\" pour Rassemblement",lieu:"EXTERIEUR",fac1:"",fac2:"",fac3:"",fac4:"",traduction:"",helper1:"Aurelie Lechardeur",helper2:"Ishvari",helper3:"Alexandre Fourcault",helper4:"",angel:"",note:"",piment:0,colibri:false,logisticId:"JOUR5__CALL__POUR_RASSEMBLEMENT",meetingRoles:""},

  // ─── Jour 6 — Jeudi 3 septembre ─────────────────────────────────────
  {id:"A_1175",jour:"Jour 6",date:"Jeudi 3 septembre",heure:"09:30 - 09:45",type:"PREPA & LOGISTICS",atelier:"\"CALL\" pour Rassemblement",lieu:"EXTERIEUR",fac1:"",fac2:"",fac3:"",fac4:"",traduction:"",helper1:"Carine Janez",helper2:"Boris Desvignes",helper3:"Audrey Barthelemy",helper4:"",angel:"",note:"",piment:0,colibri:false,logisticId:"JOUR6__CALL__POUR_RASSEMBLEMENT",meetingRoles:""},

  // ─── Jour 7 — Vendredi 4 septembre ──────────────────────────────────
  {id:"A_2185",jour:"Jour 7",date:"Vendredi 4 septembre",heure:"10:45 - 11:00",type:"PREPA & LOGISTICS",atelier:"\"CALL\" pour CEREMONIE DE CLOTURE",lieu:"EXTERIEUR",fac1:"",fac2:"",fac3:"",fac4:"",traduction:"",helper1:"Daniel Latapie",helper2:"Maeva Mantione",helper3:"Veronique Santini Bottemer",helper4:"",angel:"",note:"",piment:0,colibri:false,logisticId:"",meetingRoles:""},

  // ─── Jour 3 — Lundi 31 aout ─────────────────────────────────────────
  {id:"A_4879",jour:"Jour 3",date:"Lundi 31 aout",heure:"9:00 - 9:30",type:"REUNION",atelier:"REUNION D'EQUIPE (Animateurs et Artistes)",lieu:"TARA",fac1:"Sabryna",fac2:"ShivaChris",fac3:"",fac4:"",traduction:"",helper1:"",helper2:"",helper3:"",helper4:"",angel:"",note:"",piment:0,colibri:false,logisticId:"",meetingRoles:""},
  {id:"A_2299",jour:"Jour 3",date:"Lundi 31 aout",heure:"9:00 - 9:30",type:"REUNION",atelier:"REUNION D'EQUIPE (Helpers)",lieu:"HANUMAN",fac1:"Dorian Vallet",fac2:"",fac3:"",fac4:"",traduction:"",helper1:"",helper2:"",helper3:"",helper4:"",angel:"",note:"",piment:0,colibri:false,logisticId:"",meetingRoles:""},

  // ─── Jour 4 — Mardi 1 septembre ─────────────────────────────────────
  {id:"A_1536",jour:"Jour 4",date:"Mardi 1 septembre",heure:"9:00 - 9:30",type:"REUNION",atelier:"REUNION D'EQUIPE (Animateurs et Artistes)",lieu:"TARA",fac1:"Sabryna",fac2:"ShivaChris",fac3:"",fac4:"",traduction:"",helper1:"",helper2:"",helper3:"",helper4:"",angel:"",note:"",piment:0,colibri:false,logisticId:"",meetingRoles:""},
  {id:"A_9038",jour:"Jour 4",date:"Mardi 1 septembre",heure:"9:00 - 9:30",type:"REUNION",atelier:"REUNION D'EQUIPE (Helpers)",lieu:"HANUMAN",fac1:"Dorian Vallet",fac2:"",fac3:"",fac4:"",traduction:"",helper1:"",helper2:"",helper3:"",helper4:"",angel:"",note:"",piment:0,colibri:false,logisticId:"",meetingRoles:""},

  // ─── Jour 5 — Mercredi 2 septembre ──────────────────────────────────
  {id:"A_3920",jour:"Jour 5",date:"Mercredi 2 septembre",heure:"9:00 - 9:30",type:"REUNION",atelier:"REUNION D'EQUIPE (Animateurs et Artistes)",lieu:"TARA",fac1:"Sabryna",fac2:"ShivaChris",fac3:"",fac4:"",traduction:"",helper1:"",helper2:"",helper3:"",helper4:"",angel:"",note:"",piment:0,colibri:false,logisticId:"",meetingRoles:""},
  {id:"A_3083",jour:"Jour 5",date:"Mercredi 2 septembre",heure:"9:00 - 9:30",type:"REUNION",atelier:"REUNION D'EQUIPE (Helpers)",lieu:"HANUMAN",fac1:"Dorian Vallet",fac2:"",fac3:"",fac4:"",traduction:"",helper1:"",helper2:"",helper3:"",helper4:"",angel:"",note:"",piment:0,colibri:false,logisticId:"",meetingRoles:""},

  // ─── Jour 6 — Jeudi 3 septembre ─────────────────────────────────────
  {id:"A_7646",jour:"Jour 6",date:"Jeudi 3 septembre",heure:"9:00 - 9:30",type:"REUNION",atelier:"REUNION D'EQUIPE (Animateurs et Artistes)",lieu:"TARA",fac1:"Sabryna",fac2:"ShivaChris",fac3:"",fac4:"",traduction:"",helper1:"",helper2:"",helper3:"",helper4:"",angel:"",note:"",piment:0,colibri:false,logisticId:"",meetingRoles:""},

  // ─── Jour 7 — Vendredi 4 septembre ──────────────────────────────────
  {id:"A_3012",jour:"Jour 7",date:"Vendredi 4 septembre",heure:"9:00 - 9:30",type:"REUNION",atelier:"REUNION D'EQUIPE (ALL) - Pre Cérémonie de Cloture",lieu:"TARA",fac1:"Sabryna",fac2:"ShivaChris",fac3:"",fac4:"",traduction:"",helper1:"",helper2:"",helper3:"",helper4:"",angel:"",note:"",piment:0,colibri:false,logisticId:"",meetingRoles:""},

  // ─── Jour 6 — Jeudi 3 septembre ─────────────────────────────────────
  {id:"A_1679",jour:"Jour 6",date:"Jeudi 3 septembre",heure:"9:00 - 9:30",type:"REUNION",atelier:"REUNION D'EQUIPE (Helpers)",lieu:"HANUMAN",fac1:"Dorian Vallet",fac2:"",fac3:"",fac4:"",traduction:"",helper1:"",helper2:"",helper3:"",helper4:"",angel:"",note:"",piment:0,colibri:false,logisticId:"",meetingRoles:""},

  // ─── Jour 3 — Lundi 31 aout ─────────────────────────────────────────
  {id:"A_7729",jour:"Jour 3",date:"Lundi 31 aout",heure:"21:00 - 1:00",type:"PREPA & LOGISTICS",atelier:"EXTRA STAFF (1) - Love Temple des Erotypes",lieu:"CHENREZIG",fac1:"Paul Raj Amar",fac2:"Audrey Barthelemy",fac3:"",fac4:"",traduction:"",helper1:"Daniel Latapie",helper2:"Mukti (Cecile Yvorel)",helper3:"Philippe Hanrion",helper4:"Aurelie Lechardeur",angel:"",note:"",piment:2,colibri:false,logisticId:"",meetingRoles:""},
  {id:"A_6040",jour:"Jour 3",date:"Lundi 31 aout",heure:"21:00 - 1:00",type:"PREPA & LOGISTICS",atelier:"EXTRA STAFF (2) - Love Temple des Erotypes",lieu:"CHENREZIG",fac1:"",fac2:"",fac3:"",fac4:"",traduction:"",helper1:"Amana (William Duplain)",helper2:"Echo Clem (Clement Marchal)",helper3:"Helene Planquelle",helper4:"",angel:"",note:"",piment:2,colibri:false,logisticId:"",meetingRoles:""},

  // ─── Jour 4 — Mardi 1 septembre ─────────────────────────────────────
  {id:"A_9295",jour:"Jour 4",date:"Mardi 1 septembre",heure:"14:00 - 15:00",type:"PREPA & LOGISTICS",atelier:"BALANCE CONCERT Kelly Aura / Claude Brame (SHIVA)",lieu:"SHIVA",fac1:"Kelly Aura",fac2:"Claude Brame",fac3:"",fac4:"",traduction:"",helper1:"Echo Clem (Clement Marchal)",helper2:"",helper3:"",helper4:"",angel:"",note:"",piment:0,colibri:false,logisticId:"",meetingRoles:""},

  // ─── Jour 5 — Mercredi 2 septembre ──────────────────────────────────
  {id:"A_1488",jour:"Jour 5",date:"Mercredi 2 septembre",heure:"18:00 - 19:00",type:"PREPA & LOGISTICS",atelier:"BALANCE - CONCERT (SHIVA) - Mitsch",lieu:"SHIVA",fac1:"Mitsch Kohn",fac2:"Kelly Aura",fac3:"",fac4:"",traduction:"",helper1:"Echo Clem (Clement Marchal)",helper2:"",helper3:"",helper4:"",angel:"",note:"",piment:0,colibri:false,logisticId:"",meetingRoles:""},

  // ─── Jour 6 — Jeudi 3 septembre ─────────────────────────────────────
  {id:"A_0855",jour:"Jour 6",date:"Jeudi 3 septembre",heure:"14:00 - 15:00",type:"PREPA & LOGISTICS",atelier:"BALANCE - PREPA CONCERT - Soirée surprise (SHIVA)",lieu:"SHIVA",fac1:"",fac2:"",fac3:"",fac4:"",traduction:"",helper1:"Echo Clem (Clement Marchal)",helper2:"",helper3:"",helper4:"",angel:"",note:"",piment:0,colibri:false,logisticId:"",meetingRoles:""},
];

/**
 * Convertit un objet AGENDA en tableau positionnel [17 colonnes]
 * identique au format RAW utilisé par les rapports.
 * Indice : [0]jour [1]date [2]heure [3]type [4]atelier [5]lieu
 *          [6]fac1 [7]fac2 [8]traduction [9]helper1 [10]helper2
 *          [11]helper3 [12]helper4 [13]angel [14]note [15]logisticId [16]piment
 *          [17]fac3 [18]fac4 [19]meetingRoles
 */
function agendaToRaw(entries) {
  return entries.map(e => [
    e.jour, e.date, e.heure, e.type, e.atelier, e.lieu,
    e.fac1, e.fac2, e.traduction,
    e.helper1, e.helper2, e.helper3, e.helper4 || '',
    e.angel, e.note, e.logisticId || '', e.piment || 0,
    e.fac3 || '', e.fac4 || '', e.meetingRoles || ''
  ]);
}