/**
 * TANTRAMOUR 2026 — Référentiel de données commun
 * ================================================
 * Source unique pour les 3 rapports HTML.
 * Pour mettre à jour : modifier uniquement ce fichier.
 *
 * Structure de chaque entrée :
 *   jour       {string}  "Jour 1" … "Jour 7"
 *   date       {string}  "Samedi 29 aout" …
 *   heure      {string}  "9:45 - 11:00" | "Matin" | "APRES MIDI"
 *   type       {string}  catégorie (ex: "ATELIERS TANTRA (AM)")
 *   atelier    {string}  nom de l'atelier / activité
 *   lieu       {string}  salle / espace (ex: "SHIVA", "CHENREZIG" …)
 *   fac1       {string}  Facilitateur principal
 *   fac2       {string}  Facilitateur secondaire
 *   traduction {string}  Langue / traducteur
 *   helper1    {string}  Helper 1
 *   helper2    {string}  Helper 2
 *   helper3    {string}  Helper 3
 *   angel      {string}  Angel
 *   note       {string}  Note logistique (ex: "Shift Colibri", "Atelier + long")
 */

const AGENDA = [

  // ─── Jour 1 — Samedi 29 aout ────────────────────────────────────────
  {jour:"Jour 1",date:"Samedi 29 aout",heure:"7:30 - 10:00",type:"REPAS & PAUSE",atelier:"PETIT DEJ",lieu:"",fac1:"",fac2:"",traduction:"",helper1:"",helper2:"",helper3:"",angel:"",note:"",logisticId:""},
  {jour:"Jour 1",date:"Samedi 29 aout",heure:"Matin",type:"PREPA & LOGITICS",atelier:"DECO temples, Acceuil, exterieur",lieu:"",fac1:"",fac2:"",traduction:"",helper1:"",helper2:"",helper3:"",angel:"",note:"",logisticId:""},
  {jour:"Jour 1",date:"Samedi 29 aout",heure:"Matin",type:"PREPA & LOGITICS",atelier:"Tests son & sono a  SHIVA",lieu:"SHIVA",fac1:"",fac2:"",traduction:"",helper1:"",helper2:"",helper3:"",angel:"",note:"",logisticId:""},
  {jour:"Jour 1",date:"Samedi 29 aout",heure:"12:30 - 14:30",type:"REPAS & PAUSE",atelier:"DEJEUNER",lieu:"",fac1:"",fac2:"",traduction:"",helper1:"",helper2:"",helper3:"",angel:"",note:"",logisticId:""},
  {jour:"Jour 1",date:"Samedi 29 aout",heure:"14:30 - 15:30",type:"REUNION D'EQUIPE",atelier:"REUNION D'EQUIPE (Helpers)",lieu:"",fac1:"Sabryna",fac2:"ShivaChris",traduction:"",helper1:"",helper2:"",helper3:"",angel:"",note:"",logisticId:""},
  {jour:"Jour 1",date:"Samedi 29 aout",heure:"16:00 - 17:00",type:"REUNION D'EQUIPE",atelier:"DREAM TEAM (tous)",lieu:"",fac1:"",fac2:"",traduction:"",helper1:"",helper2:"",helper3:"",angel:"",note:"",logisticId:""},
  {jour:"Jour 1",date:"Samedi 29 aout",heure:"17:00 - 18:00 ",type:"PREPA & LOGITICS",atelier:"PREPA OPENING CEREMONY",lieu:"SHIVA",fac1:"",fac2:"",traduction:"",helper1:"Daniel Latapie",helper2:"Frederic Chalard",helper3:"Philippe Hanrion",angel:"",note:"",logisticId:""},
  {jour:"Jour 1",date:"Samedi 29 aout",heure:"18:00 - 19:30",type:"CEREMONIE & CONCERT",atelier:"OPENING CEREMONY",lieu:"SHIVA",fac1:"Sabryna",fac2:"ShivaChris",traduction:"",helper1:"Yannick Bohrer",helper2:"Mukti - Cecile Yvorel",helper3:"",angel:"Linda Stachetti",note:"",logisticId:""},
  {jour:"Jour 1",date:"Samedi 29 aout",heure:"19:00 - 20:30",type:"REPAS & PAUSE",atelier:"DINNER",lieu:"",fac1:"",fac2:"",traduction:"",helper1:"",helper2:"",helper3:"",angel:"",note:"",logisticId:""},
  {jour:"Jour 1",date:"Samedi 29 aout",heure:"20:30 - 21:00",type:"PREPA & LOGITICS",atelier:"PREPA CONCERT (SHIVA)",lieu:"SHIVA",fac1:"",fac2:"",traduction:"",helper1:"Alexandre Sattler",helper2:"Virginie Bertrand",helper3:"",angel:"",note:"",logisticId:""},
  {jour:"Jour 1",date:"Samedi 29 aout",heure:"21:00 - 23:00",type:"CEREMONIE & CONCERT",atelier:"SOIREE ECSTATIC DANSE",lieu:"SHIVA",fac1:"Pascal de Lacaze",fac2:"",traduction:"",helper1:"Emma Roussel",helper2:"Cedric Vesper",helper3:"",angel:"Aurelie Lechardeur",note:"",logisticId:""},
  {jour:"Jour 1",date:"Samedi 29 aout",heure:"07:15 - 08:00",type:"POOL PARTY",atelier:"TEST MATT",lieu:"SHIVA",fac1:"Matthieu Chapeleau (Atman)",fac2:"",traduction:"Alexandre Fourcault",helper1:"Matthieu Chapeleau (Atman)",helper2:"",helper3:"",angel:"Aurelie Lechardeur",note:"Shift Colibri",logisticId:""},
  {jour:"Jour 1",date:"Samedi 29 aout",heure:"Heure manuelle UPDATE",type:"PREPA & LOGITICS",atelier:"TEST 3",lieu:"CHENREZIG",fac1:"Matthieu Chapeleau (Atman)",fac2:"",traduction:"Emma Roussel",helper1:"Sevda Duroy",helper2:"Sevda Duroy",helper3:"",angel:"",note:"Atelier + long",logisticId:""},

  // ─── Jour 2 — Dimanche 30 aout ──────────────────────────────────────
  {jour:"Jour 2",date:"Dimanche 30 aout",heure:"7:30 - 9:00",type:"MEDITATION / YOGA",atelier:"Yoga2",lieu:"CHENREZIG",fac1:"Paul Raj Amar",fac2:"",traduction:"",helper1:"Delphine Del Dupre",helper2:"",helper3:"",angel:"",note:"",logisticId:""},
  {jour:"Jour 2",date:"Dimanche 30 aout",heure:"7:30 - 9:00",type:"MEDITATION / YOGA",atelier:"Meditation active",lieu:"SHAKTI",fac1:"Dorian Vallet",fac2:"",traduction:"",helper1:"Linda Stachetti",helper2:"",helper3:"",angel:"",note:"",logisticId:""},
  {jour:"Jour 2",date:"Dimanche 30 aout",heure:"9:00 - 9:30",type:"REUNION D'EQUIPE",atelier:"REUNION D'EQUIPE",lieu:"",fac1:"Sabryna",fac2:"ShivaChris",traduction:"",helper1:"",helper2:"",helper3:"",angel:"",note:"",logisticId:""},
  {jour:"Jour 2",date:"Dimanche 30 aout",heure:"7:30 - 10:00",type:"REPAS & PAUSE",atelier:"PETIT DEJ",lieu:"",fac1:"",fac2:"",traduction:"",helper1:"",helper2:"",helper3:"",angel:"",note:"",logisticId:""},
  {jour:"Jour 2",date:"Dimanche 30 aout",heure:"9:00 - 9:30",type:"PREPA & LOGITICS",atelier:"PREPARATION Rassemblement",lieu:"SHIVA",fac1:"",fac2:"",traduction:"",helper1:"Alexandre Fourcault",helper2:"Yannick Bohrer",helper3:"",angel:"",note:"",logisticId:""},
  {jour:"Jour 2",date:"Dimanche 30 aout",heure:"9:45 - 11:00",type:"RASSEMBLEMENT",atelier:"Rassemblement",lieu:"SHIVA",fac1:"Clement Victor (Jivan Mutti)",fac2:"Matthieu Chapeleau (Atman)",traduction:"",helper1:"Alexandre Fourcault",helper2:"Yannick Bohrer",helper3:"",angel:"",note:"",logisticId:""},
  {jour:"Jour 2",date:"Dimanche 30 aout",heure:"11:15 - 13:00",type:"ATELIERS TANTRA (AM)",atelier:"Opening Connections",lieu:"SHIVA",fac1:"Scott McClure",fac2:"",traduction:"",helper1:"Maeva Mantione",helper2:"Delphine Del Dupre",helper3:"",angel:"Virginie Bertrand",note:"",logisticId:""},
  {jour:"Jour 2",date:"Dimanche 30 aout",heure:"11:15 - 13:00",type:"ATELIERS TANTRA (AM)",atelier:"Massage meditatif tantrique (1/3)",lieu:"CHENREZIG",fac1:"Joe Jam",fac2:"Alice",traduction:"",helper1:"Daniel Latapie",helper2:"Cedric Vesper",helper3:"",angel:"Virginie Bertrand",note:"",logisticId:""},
  {jour:"Jour 2",date:"Dimanche 30 aout",heure:"11:15 - 13:00",type:"ATELIERS TANTRA (AM)",atelier:"Yabyum - let love happen",lieu:"SHAKTI",fac1:"Selma (Celine Laroche)",fac2:"",traduction:"",helper1:"Philippe Hanrion",helper2:"Alexandre Sattler",helper3:"",angel:"Virginie Bertrand",note:"",logisticId:""},
  {jour:"Jour 2",date:"Dimanche 30 aout",heure:"11:15 - 13:00",type:"ATELIERS TANTRA (AM)",atelier:"Shakti puja : Le mystere des Mahavidya",lieu:"TARA",fac1:"Ishvari",fac2:"",traduction:"",helper1:"Arnaud",helper2:"Alexandre Roque - Bhaskar",helper3:"",angel:"Virginie Bertrand",note:"",logisticId:""},
  {jour:"Jour 2",date:"Dimanche 30 aout",heure:"12:00 - 13:30",type:"ATELIER ARTISTIQUE (AM)",atelier:"Meeting Your Deity - Hypnosis & Sacred Arts Workshop",lieu:"GANESH",fac1:"Samantha Marvels",fac2:"",traduction:"",helper1:"Carine Janez",helper2:"Boris Desvignes",helper3:"",angel:"Virginie Bertrand",note:"",logisticId:""},
  {jour:"Jour 2",date:"Dimanche 30 aout",heure:"11:15 - 13:30",type:"ATELIERS TANTRA (AM)",atelier:"Angel - ATELIERS TANTRA (AM)",lieu:"",fac1:"",fac2:"",traduction:"",helper1:"",helper2:"",helper3:"",angel:"Virginie Bertrand",note:"",logisticId:""},
  {jour:"Jour 2",date:"Dimanche 30 aout",heure:"12:30 - 14:30",type:"REPAS & PAUSE",atelier:"DEJEUNER",lieu:"",fac1:"",fac2:"",traduction:"",helper1:"",helper2:"",helper3:"",angel:"",note:"",logisticId:""},
  {jour:"Jour 2",date:"Dimanche 30 aout",heure:"15:00 - 15:45",type:"REUNION D'EQUIPE",atelier:"REUNION D'EQUIPE (Helpers)",lieu:"",fac1:"Matthieu Chapeleau (Atman)",fac2:"Dorian Vallet",traduction:"",helper1:"",helper2:"",helper3:"",angel:"",note:"",logisticId:""},
  {jour:"Jour 2",date:"Dimanche 30 aout",heure:"14:30 - 16:00",type:"SUPPORT EMOTIONNEL",atelier:"SUPPORT EMOTIONNEL",lieu:"GANESH",fac1:"",fac2:"",traduction:"",helper1:"",helper2:"",helper3:"",angel:"Linda Stachetti",note:"",logisticId:""},
  {jour:"Jour 2",date:"Dimanche 30 aout",heure:"16.00 - 17.30",type:"ATELIERS TANTRA (PM)",atelier:"La Danse de la Polarite",lieu:"SHIVA",fac1:"Mahadevi (Tina Defoy)",fac2:"",traduction:"",helper1:"Frederic Chalard",helper2:"Damien Eissen",helper3:"",angel:"Linda Stachetti",note:"",logisticId:""},
  {jour:"Jour 2",date:"Dimanche 30 aout",heure:"16.00 - 17.30",type:"ATELIERS TANTRA (PM)",atelier:"Vibration a  l'unisson :Tete - Coeur - Sexe",lieu:"CHENREZIG",fac1:"Sophie O'Heix",fac2:"",traduction:"",helper1:"Veronique Santini Bottemer",helper2:"Mukti - Cecile Yvorel",helper3:"",angel:"Linda Stachetti",note:"",logisticId:""},
  {jour:"Jour 2",date:"Dimanche 30 aout",heure:"16.00 - 17.30",type:"ATELIERS TANTRA (PM)",atelier:"Roue de Terre : Consentir et Communiquer",lieu:"SHAKTI",fac1:"Clement Victor (Jivan Mutti)",fac2:"",traduction:"",helper1:"Emma Roussel",helper2:"Vera De Sousa",helper3:"",angel:"Linda Stachetti",note:"",logisticId:""},
  {jour:"Jour 2",date:"Dimanche 30 aout",heure:"16.00 - 17.30",type:"ATELIERS TANTRA (PM)",atelier:"Cesser de Faire, Laisser Etre",lieu:"TARA",fac1:"Audrey Barthelemy",fac2:"",traduction:"",helper1:"Boris Desvignes",helper2:"Yannick Bohrer",helper3:"",angel:"Linda Stachetti",note:"",logisticId:""},
  {jour:"Jour 2",date:"Dimanche 30 aout",heure:"16.00 - 17.30",type:"ATELIERS TANTRA (PM)",atelier:"Angel - ATELIERS TANTRA (PM)",lieu:"",fac1:"",fac2:"",traduction:"",helper1:"",helper2:"",helper3:"",angel:"Linda Stachetti",note:"",logisticId:""},
  {jour:"Jour 2",date:"Dimanche 30 aout",heure:"17.30 - 18.15",type:"REPAS & PAUSE",atelier:"GOUTER",lieu:"",fac1:"",fac2:"",traduction:"",helper1:"",helper2:"",helper3:"",angel:"",note:"",logisticId:""},
  {jour:"Jour 2",date:"Dimanche 30 aout",heure:"18:00 - 19:30",type:"ATELIER ARTISTIQUE (PM)",atelier:"Danse Ecstatic Contact #1 ",lieu:"SHIVA",fac1:"Cedric Vesper",fac2:"Emmanuelle Cueff (Suman)",traduction:"",helper1:"Alexandre Fourcault",helper2:"Maeva Mantione",helper3:"",angel:"Aurelie Lechardeur",note:"",logisticId:""},
  {jour:"Jour 2",date:"Dimanche 30 aout",heure:"18:00 - 19:30",type:"ATELIER ARTISTIQUE (PM)",atelier:"Move & Connect with the 5 Elements",lieu:"CHENREZIG",fac1:"Dorian Vallet",fac2:"Sevda Duroy",traduction:"",helper1:"Damien Eissen",helper2:"Daniel Latapie",helper3:"",angel:"Aurelie Lechardeur",note:"",logisticId:""},
  {jour:"Jour 2",date:"Dimanche 30 aout",heure:"18:00 - 19:30",type:"ATELIER ARTISTIQUE (PM)",atelier:"Ecstatic Dance niveau 1 ",lieu:"SHAKTI",fac1:"Yannick Bohrer",fac2:"",traduction:"",helper1:"Vera De Sousa",helper2:"Delphine Del Dupre",helper3:"",angel:"Aurelie Lechardeur",note:"",logisticId:""},
  {jour:"Jour 2",date:"Dimanche 30 aout",heure:"18:00 - 19:30",type:"ATELIER ARTISTIQUE (PM)",atelier:"L'Union sacre d'Hathor et Horus ",lieu:"TARA",fac1:"Philippe Hanrion",fac2:"",traduction:"",helper1:"Veronique Santini Bottemer",helper2:"Alexandre Sattler",helper3:"",angel:"Aurelie Lechardeur",note:"",logisticId:""},
  {jour:"Jour 2",date:"Dimanche 30 aout",heure:"18:00 - 19:30",type:"ATELIER ARTISTIQUE (PM)",atelier:"Angel - ATELIER ARTISTIQUE (PM)",lieu:"",fac1:"",fac2:"",traduction:"",helper1:"",helper2:"",helper3:"",angel:"Aurelie Lechardeur",note:"",logisticId:""},
  {jour:"Jour 2",date:"Dimanche 30 aout",heure:"19:00 - 20:30",type:"REPAS & PAUSE",atelier:"DINNER",lieu:"",fac1:"",fac2:"",traduction:"",helper1:"",helper2:"",helper3:"",angel:"",note:"",logisticId:""},
  {jour:"Jour 2",date:"Dimanche 30 aout",heure:"20:30 - 21:00",type:"PREPA & LOGITICS",atelier:"PREPA CONCERT (SHIVA)",lieu:"SHIVA",fac1:"",fac2:"",traduction:"",helper1:"Frederic Chalard",helper2:"Mukti - Cecile Yvorel",helper3:"",angel:"",note:"",logisticId:""},
  {jour:"Jour 2",date:"Dimanche 30 aout",heure:"21:00 - 23:00",type:"CEREMONIE & CONCERT",atelier:"CEROMONIE CACAO",lieu:"SHIVA",fac1:"Amana (William Duplain)",fac2:"Ishvari",traduction:"",helper1:"Alexandre Roque - Bhaskar",helper2:"Emma Roussel",helper3:"Arnaud",angel:"Virginie Bertrand",note:"",logisticId:""},
  {jour:"Jour 2",date:"Dimanche 30 aout",heure:"21:00 - 22:00",type:"PREPA & LOGITICS",atelier:"PREPA TEMPLE (CHENREZIG)",lieu:"CHENREZIG",fac1:"",fac2:"",traduction:"",helper1:"Boris Desvignes",helper2:"Linda Stachetti",helper3:"",angel:"",note:"",logisticId:""},
  {jour:"Jour 2",date:"Dimanche 30 aout",heure:"23:30 - 01:00",type:"LOVE TEMPLE",atelier:"Shibari Performance & Interactive Jam",lieu:"CHENREZIG",fac1:"Amana (William Duplain)",fac2:"Ishvari",traduction:"",helper1:"Carine Janez",helper2:"Vera De Sousa",helper3:"",angel:"Daniel Latapie",note:"",logisticId:""},

  // ─── Jour 3 — Lundi 31 aout ─────────────────────────────────────────
  {jour:"Jour 3",date:"Lundi 31 aout",heure:"7:30 - 9:00",type:"MEDITATION / YOGA",atelier:"Yoga",lieu:"CHENREZIG",fac1:"Sevda Duroy",fac2:"",traduction:"",helper1:"Mukti - Cecile Yvorel",helper2:"",helper3:"",angel:"",note:"",logisticId:""},
  {jour:"Jour 3",date:"Lundi 31 aout",heure:"7:30 - 9:00",type:"MEDITATION / YOGA",atelier:"Meditation active d'Osho : Laughing Drums Meditation",lieu:"SHAKTI",fac1:"Selma (Celine Laroche)",fac2:"",traduction:"",helper1:"Philippe Hanrion",helper2:"",helper3:"",angel:"",note:"",logisticId:""},
  {jour:"Jour 3",date:"Lundi 31 aout",heure:"9:00 - 9:30",type:"REUNION D'EQUIPE",atelier:"REUNION D'EQUIPE",lieu:"",fac1:"Sabryna",fac2:"ShivaChris",traduction:"",helper1:"",helper2:"",helper3:"",angel:"",note:"",logisticId:""},
  {jour:"Jour 3",date:"Lundi 31 aout",heure:"7:30 - 10:00",type:"REPAS & PAUSE",atelier:"PETIT DEJ",lieu:"",fac1:"",fac2:"",traduction:"",helper1:"",helper2:"",helper3:"",angel:"",note:"",logisticId:""},
  {jour:"Jour 3",date:"Lundi 31 aout",heure:"9:00 - 9:30",type:"PREPA & LOGITICS",atelier:"PREPARATION Rassemblement",lieu:"SHIVA",fac1:"",fac2:"",traduction:"",helper1:"Maeva Mantione",helper2:"Damien Eissen",helper3:"",angel:"",note:"",logisticId:""},
  {jour:"Jour 3",date:"Lundi 31 aout",heure:"9:45 - 11:00",type:"RASSEMBLEMENT",atelier:"Rassemblement",lieu:"SHIVA",fac1:"Clement Victor (Jivan Mutti)",fac2:"Matthieu Chapeleau (Atman)",traduction:"",helper1:"Maeva Mantione",helper2:"Damien Eissen",helper3:"",angel:"",note:"",logisticId:""},
  {jour:"Jour 3",date:"Lundi 31 aout",heure:"11:15 - 13:00",type:"ATELIERS TANTRA (AM)",atelier:"Entre dans la caresse comme dans la vie Eternelle",lieu:"SHIVA",fac1:"Sandrine Bettinelli",fac2:"",traduction:"",helper1:"Mukti - Cecile Yvorel",helper2:"Cedric Vesper",helper3:"",angel:"Linda Stachetti",note:"",logisticId:""},
  {jour:"Jour 3",date:"Lundi 31 aout",heure:"11:15 - 13:00",type:"ATELIERS TANTRA (AM)",atelier:"Ode a KALI",lieu:"CHENREZIG",fac1:"Emmanuelle Cueff (Suman)",fac2:"",traduction:"",helper1:"Yannick Bohrer",helper2:"Alexandre Sattler",helper3:"",angel:"Linda Stachetti",note:"",logisticId:""},
  {jour:"Jour 3",date:"Lundi 31 aout",heure:"11:15 - 13:00",type:"ATELIERS TANTRA (AM)",atelier:"La Merkaba tantrique ",lieu:"SHAKTI",fac1:"Sabryna",fac2:"ShivaChris",traduction:"",helper1:"Frederic Chalard",helper2:"Emma Roussel",helper3:"",angel:"Linda Stachetti",note:"",logisticId:""},
  {jour:"Jour 3",date:"Lundi 31 aout",heure:"11:15 - 13:00",type:"ATELIERS TANTRA (AM)",atelier:"Plongez dans l'experience « Du plaisir » (pour femmes ou personnes identifiees)",lieu:"TARA",fac1:"Audrey Barthelemy",fac2:"",traduction:"",helper1:"Carine Janez",helper2:"Delphine Del Dupre",helper3:"",angel:"Linda Stachetti",note:"Atelier Femme",logisticId:""},
  {jour:"Jour 3",date:"Lundi 31 aout",heure:"12:00 - 13:30",type:"ATELIER ARTISTIQUE (AM)",atelier:"Danse des portes multidimensionnelles de l'Etre",lieu:"GANESH",fac1:"Mahadevi (Tina Defoy)",fac2:"",traduction:"",helper1:"Veronique Santini Bottemer",helper2:"Paul Raj Amar",helper3:"",angel:"Linda Stachetti",note:"Shift Colibri",logisticId:""},
  {jour:"Jour 3",date:"Lundi 31 aout",heure:"11:15 - 13:30",type:"ATELIERS TANTRA (AM)",atelier:"Angel - ATELIERS TANTRA (AM)",lieu:"",fac1:"",fac2:"",traduction:"",helper1:"",helper2:"",helper3:"",angel:"Linda Stachetti",note:"",logisticId:""},
  {jour:"Jour 3",date:"Lundi 31 aout",heure:"12:30 - 14:30",type:"REPAS & PAUSE",atelier:"DEJEUNER",lieu:"",fac1:"",fac2:"",traduction:"",helper1:"",helper2:"",helper3:"",angel:"",note:"",logisticId:""},
  {jour:"Jour 3",date:"Lundi 31 aout",heure:"15:00 - 15:45",type:"REUNION D'EQUIPE",atelier:"REUNION D'EQUIPE (Helpers)",lieu:"",fac1:"Matthieu Chapeleau (Atman)",fac2:"Dorian Vallet",traduction:"",helper1:"",helper2:"",helper3:"",angel:"",note:"",logisticId:""},
  {jour:"Jour 3",date:"Lundi 31 aout",heure:"14:30 - 15:00",type:"PREPA & LOGITICS",atelier:"Prepa - POOL PARTY",lieu:"PISCINE",fac1:"",fac2:"",traduction:"",helper1:"Philippe Hanrion",helper2:"",helper3:"",angel:"",note:"",logisticId:""},
  {jour:"Jour 3",date:"Lundi 31 aout",heure:"15:00 - 16:00",type:"POOL PARTY",atelier:"POOL PARTY   - DJ Pascal de Lacaze ",lieu:"PISCINE",fac1:"Pascal de Lacaze",fac2:"",traduction:"",helper1:"",helper2:"",helper3:"",angel:"",note:"",logisticId:""},
  {jour:"Jour 3",date:"Lundi 31 aout",heure:"14:30 - 16:00",type:"SUPPORT EMOTIONNEL",atelier:"SUPPORT EMOTIONNEL",lieu:"GANESH",fac1:"",fac2:"",traduction:"",helper1:"",helper2:"",helper3:"",angel:"Aurelie Lechardeur",note:"",logisticId:""},
  {jour:"Jour 3",date:"Lundi 31 aout",heure:"16.00 - 17.30",type:"ATELIERS TANTRA (PM)",atelier:"Voyage avec la Rose (femmes)",lieu:"SHIVA",fac1:"Emma Roussel",fac2:"",traduction:"",helper1:"Maeva Mantione",helper2:"Mukti - Cecile Yvorel",helper3:"",angel:"Aurelie Lechardeur",note:"Atelier Femme",logisticId:""},
  {jour:"Jour 3",date:"Lundi 31 aout",heure:"16.00 - 19:30",type:"ATELIERS TANTRA (PM)",atelier:"The Space Between Us (3hrs)",lieu:"CHENREZIG",fac1:"Our Echo",fac2:"Guy El Hadad - Israel",traduction:"",helper1:"Vera De Sousa",helper2:"Amana (William Duplain)",helper3:"",angel:"Aurelie Lechardeur",note:"Shift Colibri",logisticId:""},
  {jour:"Jour 3",date:"Lundi 31 aout",heure:"16.00 - 17.30",type:"ATELIERS TANTRA (PM)",atelier:"Yoni & Lingam Puja",lieu:"SHAKTI",fac1:"Ishvari",fac2:"",traduction:"",helper1:"Yannick Bohrer",helper2:"Alexandre Roque - Bhaskar",helper3:"",angel:"Aurelie Lechardeur",note:"",logisticId:""},
  {jour:"Jour 3",date:"Lundi 31 aout",heure:"16.00 - 17.30",type:"ATELIERS TANTRA (PM)",atelier:"La Saveur du Desir ",lieu:"TARA",fac1:"Daniel Latapie",fac2:"",traduction:"",helper1:"Arnaud",helper2:"Alexandre Fourcault",helper3:"",angel:"Aurelie Lechardeur",note:"",logisticId:""},
  {jour:"Jour 3",date:"Lundi 31 aout",heure:"16.00 - 17.30",type:"ATELIERS TANTRA (PM)",atelier:"Angel - ATELIERS TANTRA (PM)",lieu:"",fac1:"",fac2:"",traduction:"",helper1:"",helper2:"",helper3:"",angel:"Aurelie Lechardeur",note:"",logisticId:""},
  {jour:"Jour 3",date:"Lundi 31 aout",heure:"17.30 - 18.15",type:"REPAS & PAUSE",atelier:"GOUTER",lieu:"",fac1:"",fac2:"",traduction:"",helper1:"",helper2:"",helper3:"",angel:"",note:"",logisticId:""},
  {jour:"Jour 3",date:"Lundi 31 aout",heure:"18:00 - 19:30",type:"ATELIER ARTISTIQUE (PM)",atelier:"Heart Medicine Dance",lieu:"SHIVA",fac1:"David Llorca",fac2:"",traduction:"",helper1:"Carine Janez",helper2:"Veronique Santini Bottemer",helper3:"",angel:"Boris Desvignes",note:"",logisticId:""},
  {jour:"Jour 3",date:"Lundi 31 aout",heure:"18:00 - 19:30",type:"ATELIER ARTISTIQUE (PM)",atelier:"Danse Orgasmique â€œ Danser la jouissance d'Etre vivant â€œ",lieu:"SHAKTI",fac1:"Virginie Bertrand",fac2:"",traduction:"",helper1:"Alexandre Sattler",helper2:"Daniel Latapie",helper3:"",angel:"Boris Desvignes",note:"",logisticId:""},
  {jour:"Jour 3",date:"Lundi 31 aout",heure:"18:00 - 19:30",type:"ATELIER ARTISTIQUE (PM)",atelier:"Initiation a  la danse Fusion",lieu:"TARA",fac1:"Stephane Ahmed",fac2:"",traduction:"",helper1:"Cedric Vesper",helper2:"Delphine Del Dupre",helper3:"",angel:"Boris Desvignes",note:"",logisticId:""},
  {jour:"Jour 3",date:"Lundi 31 aout",heure:"18:00 - 19:30",type:"ATELIER ARTISTIQUE (PM)",atelier:"Traverser : souffle, froid et confiance (Methode Wim Hof - bain froid)",lieu:"EXTERIEUR",fac1:"Damien Eissen",fac2:"Dorian Vallet",traduction:"",helper1:"Philippe Hanrion",helper2:"Frederic Chalard",helper3:"",angel:"Boris Desvignes",note:"",logisticId:""},
  {jour:"Jour 3",date:"Lundi 31 aout",heure:"18:00 - 19:30",type:"ATELIER ARTISTIQUE (PM)",atelier:"Angel - ATELIER ARTISTIQUE (PM)",lieu:"",fac1:"",fac2:"",traduction:"",helper1:"",helper2:"",helper3:"",angel:"Boris Desvignes",note:"",logisticId:""},
  {jour:"Jour 3",date:"Lundi 31 aout",heure:"19:00 - 20:30",type:"REPAS & PAUSE",atelier:"DINNER",lieu:"",fac1:"",fac2:"",traduction:"",helper1:"",helper2:"",helper3:"",angel:"",note:"",logisticId:""},
  {jour:"Jour 3",date:"Lundi 31 aout",heure:"20:30 - 21:00",type:"PREPA & LOGITICS",atelier:"PREPA CONCERT (SHIVA)",lieu:"SHIVA",fac1:"",fac2:"",traduction:"",helper1:"Daniel Latapie",helper2:"Yannick Bohrer",helper3:"",angel:"",note:"",logisticId:""},
  {jour:"Jour 3",date:"Lundi 31 aout",heure:"21:00 - 23:00",type:"CEREMONIE & CONCERT",atelier:"DJ Set avec Juan Felix",lieu:"SHIVA",fac1:"Felix Ardevol",fac2:"",traduction:"",helper1:"Cedric Vesper",helper2:"",helper3:"",angel:"Daniel Latapie",note:"",logisticId:""},
  {jour:"Jour 3",date:"Lundi 31 aout",heure:"20:30 - 21:00",type:"PREPA & LOGITICS",atelier:"PREPA TEMPLE (CHENREZIG)",lieu:"CHENREZIG",fac1:"",fac2:"",traduction:"",helper1:"Alexandre Fourcault",helper2:"Carine Janez",helper3:"Linda Stachetti",angel:"",note:"",logisticId:""},
  {jour:"Jour 3",date:"Lundi 31 aout",heure:"21:00 â€“ 1:00",type:"LOVE TEMPLE",atelier:"Love Temple des Erotypes @R",lieu:"CHENREZIG",fac1:"Paul Raj Amar",fac2:"Audrey Barthelemy",traduction:"",helper1:"Arnaud",helper2:"Maeva Mantione",helper3:"",angel:"Virginie Bertrand",note:"",logisticId:""},

  // ─── Jour 4 — Mardi 1 septembre ─────────────────────────────────────
  {jour:"Jour 4",date:"Mardi 1 septembre",heure:"7:30 - 9:00",type:"MEDITATION / YOGA",atelier:"Yoga",lieu:"CHENREZIG",fac1:"Sevda Duroy",fac2:"",traduction:"",helper1:"Cedric Vesper",helper2:"",helper3:"",angel:"",note:"",logisticId:""},
  {jour:"Jour 4",date:"Mardi 1 septembre",heure:"7:30 - 9:00",type:"MEDITATION / YOGA",atelier:"Meditation",lieu:"SHAKTI",fac1:"ShivaChris",fac2:"",traduction:"",helper1:"Carine Janez",helper2:"",helper3:"",angel:"",note:"",logisticId:""},
  {jour:"Jour 4",date:"Mardi 1 septembre",heure:"9:00 - 9:30",type:"REUNION D'EQUIPE",atelier:"REUNION D'EQUIPE",lieu:"",fac1:"Sabryna",fac2:"ShivaChris",traduction:"",helper1:"",helper2:"",helper3:"",angel:"",note:"",logisticId:""},
  {jour:"Jour 4",date:"Mardi 1 septembre",heure:"7:30 - 10:00",type:"REPAS & PAUSE",atelier:"PETIT DEJ",lieu:"",fac1:"",fac2:"",traduction:"",helper1:"",helper2:"",helper3:"",angel:"",note:"",logisticId:""},
  {jour:"Jour 4",date:"Mardi 1 septembre",heure:"9:00 - 9:30",type:"PREPA & LOGITICS",atelier:"PREPARATION Rassemblement",lieu:"SHIVA",fac1:"",fac2:"",traduction:"",helper1:"Veronique Santini Bottemer",helper2:"Damien Eissen",helper3:"",angel:"",note:"",logisticId:""},
  {jour:"Jour 4",date:"Mardi 1 septembre",heure:"9:45 - 11:00",type:"RASSEMBLEMENT",atelier:"Rassemblement",lieu:"SHIVA",fac1:"Clement Victor (Jivan Mutti)",fac2:"Matthieu Chapeleau (Atman)",traduction:"",helper1:"Veronique Santini Bottemer",helper2:"Damien Eissen",helper3:"",angel:"",note:"",logisticId:""},
  {jour:"Jour 4",date:"Mardi 1 septembre",heure:"11:15 - 13:00",type:"ATELIERS TANTRA (AM)",atelier:"Releasing Sexual Shame & Conditioning",lieu:"SHIVA",fac1:"Samantha Marvels",fac2:"",traduction:"",helper1:"Mukti - Cecile Yvorel",helper2:"Carine Janez",helper3:"",angel:"Aurelie Lechardeur",note:"",logisticId:""},
  {jour:"Jour 4",date:"Mardi 1 septembre",heure:"11:15 - 13:00",type:"ATELIERS TANTRA (AM)",atelier:"Alice : Dissolution (2/3) massage meditatif tantrique",lieu:"CHENREZIG",fac1:"Bruno Deck",fac2:"",traduction:"",helper1:"Philippe Hanrion",helper2:"Alexandre Fourcault",helper3:"",angel:"Aurelie Lechardeur",note:"",logisticId:""},
  {jour:"Jour 4",date:"Mardi 1 septembre",heure:"11:15 - 13:00",type:"ATELIERS TANTRA (AM)",atelier:"L'Alchimie de l'Extase",lieu:"SHAKTI",fac1:"Sabryna",fac2:"ShivaChris",traduction:"",helper1:"Arnaud",helper2:"Delphine Del Dupre",helper3:"",angel:"Aurelie Lechardeur",note:"",logisticId:""},
  {jour:"Jour 4",date:"Mardi 1 septembre",heure:"11:15 - 13:30",type:"ATELIERS TANTRA (AM)",atelier:"Ode a  la liberte (2hrs)",lieu:"TARA",fac1:"Selma (Celine Laroche)",fac2:"",traduction:"",helper1:"Emma Roussel",helper2:"Vera De Sousa",helper3:"",angel:"Aurelie Lechardeur",note:"Atelier + long",logisticId:""},
  {jour:"Jour 4",date:"Mardi 1 septembre",heure:"12:00 - 13:30",type:"ATELIER ARTISTIQUE (AM)",atelier:"Baladi Tao-Tantrique",lieu:"GANESH",fac1:"Mahadevi (Tina Defoy)",fac2:"",traduction:"",helper1:"Cedric Vesper",helper2:"Boris Desvignes",helper3:"",angel:"Aurelie Lechardeur",note:"",logisticId:""},
  {jour:"Jour 4",date:"Mardi 1 septembre",heure:"11:15 - 13:30",type:"ATELIERS TANTRA (AM)",atelier:"Angel - ATELIERS TANTRA (AM)",lieu:"",fac1:"",fac2:"",traduction:"",helper1:"",helper2:"",helper3:"",angel:"Aurelie Lechardeur",note:"",logisticId:""},
  {jour:"Jour 4",date:"Mardi 1 septembre",heure:"12:30 - 14:30",type:"REPAS & PAUSE",atelier:"DEJEUNER",lieu:"",fac1:"",fac2:"",traduction:"",helper1:"",helper2:"",helper3:"",angel:"",note:"",logisticId:""},
  {jour:"Jour 4",date:"Mardi 1 septembre",heure:"15:00 - 15:45",type:"REUNION D'EQUIPE",atelier:"REUNION D'EQUIPE (Helpers)",lieu:"",fac1:"Matthieu Chapeleau (Atman)",fac2:"Dorian Vallet",traduction:"",helper1:"",helper2:"",helper3:"",angel:"",note:"",logisticId:""},
  {jour:"Jour 4",date:"Mardi 1 septembre",heure:"14:30 - 16:00",type:"SUPPORT EMOTIONNEL",atelier:"SUPPORT EMOTIONNEL",lieu:"GANESH",fac1:"",fac2:"",traduction:"",helper1:"",helper2:"",helper3:"",angel:"Linda Stachetti",note:"",logisticId:""},
  {jour:"Jour 4",date:"Mardi 1 septembre",heure:"16.00 - 17.30",type:"ATELIERS TANTRA (PM)",atelier:"The Art of Kissing ",lieu:"SHIVA",fac1:"Paul Raj Amar",fac2:"",traduction:"",helper1:"Emma Roussel",helper2:"Delphine Del Dupre",helper3:"",angel:"Linda Stachetti",note:"",logisticId:""},
  {jour:"Jour 4",date:"Mardi 1 septembre",heure:"16.00 - 19.30",type:"ATELIERS TANTRA (PM)",atelier:"Sacred Mirrors: Grief Ceremony/ Celebration of Life (3hrs)",lieu:"CHENREZIG",fac1:"Our Echo",fac2:"Guy El Hadad - Israel",traduction:"",helper1:"Alexandre Sattler",helper2:"Frederic Chalard",helper3:"",angel:"Linda Stachetti",note:"Atelier + long",logisticId:""},
  {jour:"Jour 4",date:"Mardi 1 septembre",heure:"16.00 - 17.30",type:"ATELIERS TANTRA (PM)",atelier:"Roue de l'Eau : Roue du consentement & free flow massage ",lieu:"SHAKTI",fac1:"Clement Victor (Jivan Mutti)",fac2:"",traduction:"",helper1:"Arnaud",helper2:"Vera De Sousa",helper3:"",angel:"Linda Stachetti",note:"",logisticId:""},
  {jour:"Jour 4",date:"Mardi 1 septembre",heure:"16.00 - 17.30",type:"ATELIERS TANTRA (PM)",atelier:"L Ouroboros tantrique : cercle, souffle et alchimie",lieu:"TARA",fac1:"Daniel Latapie",fac2:"",traduction:"",helper1:"Damien Eissen",helper2:"David Llorca",helper3:"",angel:"Linda Stachetti",note:"Shift Colibri",logisticId:""},
  {jour:"Jour 4",date:"Mardi 1 septembre",heure:"16.00 - 17.30",type:"ATELIERS TANTRA (PM)",atelier:"Angel - ATELIERS TANTRA (PM)",lieu:"",fac1:"",fac2:"",traduction:"",helper1:"",helper2:"",helper3:"",angel:"Linda Stachetti",note:"",logisticId:""},
  {jour:"Jour 4",date:"Mardi 1 septembre",heure:"17.30 - 18.15",type:"REPAS & PAUSE",atelier:"GOUTER",lieu:"",fac1:"",fac2:"",traduction:"",helper1:"",helper2:"",helper3:"",angel:"",note:"",logisticId:""},
  {jour:"Jour 4",date:"Mardi 1 septembre",heure:"18:00 - 19:30",type:"ATELIER ARTISTIQUE (PM)",atelier:"Danse Fusion : guider / se laisser guider",lieu:"SHIVA",fac1:"Stephane Ahmed",fac2:"",traduction:"",helper1:"Mukti - Cecile Yvorel",helper2:"Carine Janez",helper3:"",angel:"Boris Desvignes",note:"",logisticId:""},
  {jour:"Jour 4",date:"Mardi 1 septembre",heure:"18:00 - 19:30",type:"ATELIER ARTISTIQUE (PM)",atelier:"Danse Ecstatic Contact #2 ",lieu:"SHAKTI",fac1:"Cedric Vesper",fac2:"Emmanuelle Cueff (Suman)",traduction:"",helper1:"Alexandre Fourcault",helper2:"Sophie O'Heix",helper3:"",angel:"Boris Desvignes",note:"Shift Colibri",logisticId:""},
  {jour:"Jour 4",date:"Mardi 1 septembre",heure:"18:00 - 19:30",type:"ATELIER ARTISTIQUE (PM)",atelier:"Animal Embodiment ",lieu:"TARA",fac1:"Dorian Vallet",fac2:"",traduction:"",helper1:"Virginie Bertrand",helper2:"Veronique Santini Bottemer",helper3:"",angel:"Boris Desvignes",note:"",logisticId:""},
  {jour:"Jour 4",date:"Mardi 1 septembre",heure:"18:00 - 19:30",type:"ATELIER ARTISTIQUE (PM)",atelier:"Angel - ATELIER ARTISTIQUE (PM)",lieu:"",fac1:"",fac2:"",traduction:"",helper1:"",helper2:"",helper3:"",angel:"Boris Desvignes",note:"",logisticId:""},
  {jour:"Jour 4",date:"Mardi 1 septembre",heure:"19:00 - 20:30",type:"REPAS & PAUSE",atelier:"DINNER",lieu:"",fac1:"",fac2:"",traduction:"",helper1:"",helper2:"",helper3:"",angel:"",note:"",logisticId:""},
  {jour:"Jour 4",date:"Mardi 1 septembre",heure:"20:30 - 21:00",type:"PREPA & LOGITICS",atelier:"PREPA CONCERT (SHIVA)",lieu:"SHIVA",fac1:"",fac2:"",traduction:"",helper1:"Philippe Hanrion",helper2:"Frederic Chalard",helper3:"",angel:"",note:"",logisticId:""},
  {jour:"Jour 4",date:"Mardi 1 septembre",heure:"21:00 - 23:00",type:"CEREMONIE & CONCERT",atelier:"CONCERT chants & mantra avec Kelly Aura & Claude Brame",lieu:"SHIVA",fac1:"Kelly Aura",fac2:"Claude Brame",traduction:"",helper1:"Emma Roussel",helper2:"Arnaud",helper3:"",angel:"Mukti - Cecile Yvorel",note:"",logisticId:""},
  {jour:"Jour 4",date:"Mardi 1 septembre",heure:"21:00 - 22:00",type:"PREPA & LOGITICS",atelier:"PREPA TEMPLE (CHENREZIG)",lieu:"CHENREZIG",fac1:"",fac2:"",traduction:"",helper1:"Alexandre Fourcault",helper2:"Delphine Del Dupre",helper3:"",angel:"",note:"",logisticId:""},
  {jour:"Jour 4",date:"Mardi 1 septembre",heure:"23:30 - 01:00",type:"LOVE TEMPLE",atelier:"Love temple devotionnel ",lieu:"CHENREZIG",fac1:"Ishvari",fac2:"",traduction:"",helper1:"Alexandre Roque - Bhaskar",helper2:"Maeva Mantione",helper3:"",angel:"Daniel Latapie",note:"",logisticId:""},

  // ─── Jour 5 — Mercredi 2 septembre ──────────────────────────────────
  {jour:"Jour 5",date:"Mercredi 2 septembre",heure:"7:30 - 9:00",type:"MEDITATION / YOGA",atelier:"Yoga Nidra",lieu:"CHENREZIG",fac1:"Simone Bikene",fac2:"",traduction:"",helper1:"Delphine Del Dupre",helper2:"",helper3:"",angel:"",note:"",logisticId:""},
  {jour:"Jour 5",date:"Mercredi 2 septembre",heure:"7:30 - 9:00",type:"MEDITATION / YOGA",atelier:"Grounding / Integrative Movement Class",lieu:"SHAKTI",fac1:"Our Echo",fac2:"",traduction:"",helper1:"Yannick Bohrer",helper2:"",helper3:"",angel:"",note:"",logisticId:""},
  {jour:"Jour 5",date:"Mercredi 2 septembre",heure:"9:00 - 9:30",type:"REUNION D'EQUIPE",atelier:"REUNION D'EQUIPE",lieu:"",fac1:"Sabryna",fac2:"ShivaChris",traduction:"",helper1:"",helper2:"",helper3:"",angel:"",note:"",logisticId:""},
  {jour:"Jour 5",date:"Mercredi 2 septembre",heure:"7:30 - 10:00",type:"REPAS & PAUSE",atelier:"PETIT DEJ",lieu:"",fac1:"",fac2:"",traduction:"",helper1:"",helper2:"",helper3:"",angel:"",note:"",logisticId:""},
  {jour:"Jour 5",date:"Mercredi 2 septembre",heure:"9:00 - 9:30",type:"PREPA & LOGITICS",atelier:"PREPARATION Rassemblement",lieu:"SHIVA",fac1:"",fac2:"",traduction:"",helper1:"Alexandre Fourcault",helper2:"Damien Eissen",helper3:"",angel:"",note:"",logisticId:""},
  {jour:"Jour 5",date:"Mercredi 2 septembre",heure:"9:45 - 11:00",type:"RASSEMBLEMENT",atelier:"Rassemblement",lieu:"SHIVA",fac1:"Clement Victor (Jivan Mutti)",fac2:"Matthieu Chapeleau (Atman)",traduction:"",helper1:"Alexandre Fourcault",helper2:"Damien Eissen",helper3:"",angel:"",note:"",logisticId:""},
  {jour:"Jour 5",date:"Mercredi 2 septembre",heure:"11:15 - 13:00",type:"ATELIERS TANTRA (AM)",atelier:"Roue du Feu : Liberation emotionnelle et Kali ",lieu:"SHIVA",fac1:"Clement Victor (Jivan Mutti)",fac2:"",traduction:"",helper1:"Mukti - Cecile Yvorel",helper2:"Cedric Vesper",helper3:"",angel:"Aurelie Lechardeur",note:"",logisticId:""},
  {jour:"Jour 5",date:"Mercredi 2 septembre",heure:"11:15 - 13:00",type:"ATELIERS TANTRA (AM)",atelier:"Ode a  SHIVA ",lieu:"CHENREZIG",fac1:"Emmanuelle Cueff (Suman)",fac2:"",traduction:"",helper1:"Philippe Hanrion",helper2:"Alexandre Sattler",helper3:"",angel:"Aurelie Lechardeur",note:"",logisticId:""},
  {jour:"Jour 5",date:"Mercredi 2 septembre",heure:"11:15 - 13:00",type:"ATELIERS TANTRA (AM)",atelier:"Mystic Shibari - L'Art de la Transgression",lieu:"SHAKTI",fac1:"Amana (William Duplain)",fac2:"",traduction:"",helper1:"Frederic Chalard",helper2:"Arnaud",helper3:"",angel:"Aurelie Lechardeur",note:"",logisticId:""},
  {jour:"Jour 5",date:"Mercredi 2 septembre",heure:"11:15 - 13:00",type:"ATELIERS TANTRA (AM)",atelier:"Au commencement etait le corps ",lieu:"TARA",fac1:"Sandrine Bettinelli",fac2:"",traduction:"",helper1:"Carine Janez",helper2:"Alexandre Roque - Bhaskar",helper3:"",angel:"Aurelie Lechardeur",note:"",logisticId:""},
  {jour:"Jour 5",date:"Mercredi 2 septembre",heure:"12:00 - 13:30",type:"ATELIER ARTISTIQUE (AM)",atelier:"Danse de sublimation et Yi king ",lieu:"GANESH",fac1:"Boris Desvignes",fac2:"",traduction:"",helper1:"Daniel Latapie",helper2:"Veronique Santini Bottemer",helper3:"",angel:"Aurelie Lechardeur",note:"",logisticId:""},
  {jour:"Jour 5",date:"Mercredi 2 septembre",heure:"12:00 - 13:30",type:"ATELIER ARTISTIQUE (AM)",atelier:"Water Dance",lieu:"PISCINE",fac1:"David Llorca",fac2:"",traduction:"",helper1:"Emma Roussel",helper2:"Linda Stachetti",helper3:"",angel:"Aurelie Lechardeur",note:"",logisticId:""},
  {jour:"Jour 5",date:"Mercredi 2 septembre",heure:"11:15 - 13:30",type:"ATELIERS TANTRA (AM)",atelier:"Angel - ATELIERS TANTRA (AM)",lieu:"",fac1:"",fac2:"",traduction:"",helper1:"",helper2:"",helper3:"",angel:"Aurelie Lechardeur",note:"",logisticId:""},
  {jour:"Jour 5",date:"Mercredi 2 septembre",heure:"12:30 - 14:30",type:"REPAS & PAUSE",atelier:"DEJEUNER",lieu:"",fac1:"",fac2:"",traduction:"",helper1:"",helper2:"",helper3:"",angel:"",note:"",logisticId:""},
  {jour:"Jour 5",date:"Mercredi 2 septembre",heure:"15:00 - 15:45",type:"REUNION D'EQUIPE",atelier:"REUNION D'EQUIPE (Helpers)",lieu:"",fac1:"Matthieu Chapeleau (Atman)",fac2:"Dorian Vallet",traduction:"",helper1:"",helper2:"",helper3:"",angel:"",note:"",logisticId:""},
  {jour:"Jour 5",date:"Mercredi 2 septembre",heure:"14.00 - 16.00",type:"TANTRA CAFÃ‰ & CONFERENCE",atelier:"Tantra Cafe - Tout ce que vous avez toujours voulu savoir sur la sexualite tantrique",lieu:"?",fac1:"Sandrine Bettinelli",fac2:"",traduction:"",helper1:"Boris Desvignes",helper2:"Carine Janez",helper3:"",angel:"Virginie Bertrand",note:"",logisticId:""},
  {jour:"Jour 5",date:"Mercredi 2 septembre",heure:"15.30 - 16.00",type:"PREPA & LOGITICS",atelier:"Prepa - POOL PARTY",lieu:"PISCINE",fac1:"",fac2:"",traduction:"",helper1:"Alexandre Fourcault",helper2:"",helper3:"",angel:"",note:"",logisticId:""},
  {jour:"Jour 5",date:"Mercredi 2 septembre",heure:"16.00 - 17.30",type:"POOL PARTY",atelier:"POOL PARTY - DJ Juan Felix",lieu:"PISCINE",fac1:"Felix Ardevol",fac2:"",traduction:"",helper1:"",helper2:"",helper3:"",angel:"Virginie Bertrand",note:"",logisticId:""},
  {jour:"Jour 5",date:"Mercredi 2 septembre",heure:"14:30 - 16:00",type:"SUPPORT EMOTIONNEL",atelier:"SUPPORT EMOTIONNEL",lieu:"GANESH",fac1:"",fac2:"",traduction:"",helper1:"",helper2:"",helper3:"",angel:"Virginie Bertrand",note:"",logisticId:""},
  {jour:"Jour 5",date:"Mercredi 2 septembre",heure:"16.00 - 17.30",type:"ATELIERS TANTRA (PM)",atelier:"Angel - ATELIERS TANTRA (PM)",lieu:"",fac1:"",fac2:"",traduction:"",helper1:"",helper2:"",helper3:"",angel:"Virginie Bertrand",note:"",logisticId:""},
  {jour:"Jour 5",date:"Mercredi 2 septembre",heure:"17.30 - 18.15",type:"REPAS & PAUSE",atelier:"GOUTER",lieu:"",fac1:"",fac2:"",traduction:"",helper1:"",helper2:"",helper3:"",angel:"",note:"",logisticId:""},
  {jour:"Jour 5",date:"Mercredi 2 septembre",heure:"18:00 - 19:30",type:"ATELIER ARTISTIQUE (PM)",atelier:"Et si tu tissais le fil de ta liberte ? ",lieu:"CHENREZIG",fac1:"Laurence Heitzmann",fac2:"Laurent Lacoste",traduction:"",helper1:"Veronique Santini Bottemer",helper2:"Alexandre Roque - Bhaskar",helper3:"",angel:"Daniel Latapie",note:"",logisticId:""},
  {jour:"Jour 5",date:"Mercredi 2 septembre",heure:"18:00 - 19:30",type:"ATELIER ARTISTIQUE (PM)",atelier:"Roue de l'Air : Roue de l'Air : Poemes Medecine ",lieu:"SHAKTI",fac1:"Clement Victor (Jivan Mutti)",fac2:"Matthieu Chapeleau (Atman)",traduction:"",helper1:"Mukti - Cecile Yvorel",helper2:"Maeva Mantione",helper3:"",angel:"Daniel Latapie",note:"",logisticId:""},
  {jour:"Jour 5",date:"Mercredi 2 septembre",heure:"18:00 - 19:30",type:"ATELIER ARTISTIQUE (PM)",atelier:"Live Electro Accoustique & Voix",lieu:"TARA",fac1:"Emmanuelle Cueff (Suman)",fac2:"Stephane Ahmed",traduction:"",helper1:"Cedric Vesper",helper2:"Delphine Del Dupre",helper3:"",angel:"Daniel Latapie",note:"",logisticId:""},
  {jour:"Jour 5",date:"Mercredi 2 septembre",heure:"18:00 - 19:30",type:"ATELIER ARTISTIQUE (PM)",atelier:"Glorious Bodies / Corps de gloire (bodypainting) ",lieu:"GANESH",fac1:"Paul Raj Amar",fac2:"Helene",traduction:"",helper1:"Damien Eissen",helper2:"Alexandre Sattler",helper3:"",angel:"Daniel Latapie",note:"",logisticId:""},
  {jour:"Jour 5",date:"Mercredi 2 septembre",heure:"18:00 - 19:30",type:"ATELIER ARTISTIQUE (PM)",atelier:"Angel - ATELIER ARTISTIQUE (PM)",lieu:"",fac1:"",fac2:"",traduction:"",helper1:"",helper2:"",helper3:"",angel:"Daniel Latapie",note:"",logisticId:""},
  {jour:"Jour 5",date:"Mercredi 2 septembre",heure:"19:00 - 20:30",type:"REPAS & PAUSE",atelier:"DINNER",lieu:"",fac1:"",fac2:"",traduction:"",helper1:"",helper2:"",helper3:"",angel:"",note:"",logisticId:""},
  {jour:"Jour 5",date:"Mercredi 2 septembre",heure:"20:30 - 21:00",type:"PREPA & LOGITICS",atelier:"PREPA CONCERT (SHIVA)",lieu:"SHIVA",fac1:"",fac2:"",traduction:"",helper1:"Frederic Chalard",helper2:"Philippe Hanrion",helper3:"",angel:"",note:"",logisticId:""},
  {jour:"Jour 5",date:"Mercredi 2 septembre",heure:"21:00 - 23:00",type:"CEREMONIE & CONCERT",atelier:"Concert: Mitsch Kohn (& artists a  definir)",lieu:"SHIVA",fac1:"Mitsch Kohn",fac2:"",traduction:"",helper1:"Frederic Chalard",helper2:"Philippe Hanrion",helper3:"",angel:"Boris Desvignes",note:"",logisticId:""},
  {jour:"Jour 5",date:"Mercredi 2 septembre",heure:"21:00 - 22:00",type:"PREPA & LOGITICS",atelier:"PREPA TEMPLE (CHENREZIG)",lieu:"CHENREZIG",fac1:"",fac2:"",traduction:"",helper1:"Alexandre Fourcault",helper2:"Yannick Bohrer",helper3:"Cedric Vesper",angel:"",note:"",logisticId:""},
  {jour:"Jour 5",date:"Mercredi 2 septembre",heure:"23:30 - 01:00",type:"LOVE TEMPLE",atelier:"Embrasser le Mystere",lieu:"CHENREZIG",fac1:"Clement Victor (Jivan Mutti)",fac2:"Matthieu Chapeleau (Atman)",traduction:"",helper1:"Vera De Sousa",helper2:"Boris Desvignes",helper3:"Maeva Mantione",angel:"Linda Stachetti",note:"",logisticId:""},

  // ─── Jour 6 — Jeudi 3 septembre ─────────────────────────────────────
  {jour:"Jour 6",date:"Jeudi 3 septembre",heure:"7:30 - 9:00",type:"MEDITATION / YOGA",atelier:"AcroYoga ",lieu:"CHENREZIG",fac1:"Sevda Duroy",fac2:"ShivaChris",traduction:"",helper1:"Frederic Chalard",helper2:"",helper3:"",angel:"",note:"",logisticId:""},
  {jour:"Jour 6",date:"Jeudi 3 septembre",heure:"7:30 - 9:00",type:"MEDITATION / YOGA",atelier:"Mindfulness & Mouvements Somatiques",lieu:"SHAKTI",fac1:"Linda Stachetti",fac2:"",traduction:"",helper1:"Virginie Bertrand",helper2:"",helper3:"",angel:"",note:"",logisticId:""},
  {jour:"Jour 6",date:"Jeudi 3 septembre",heure:"9:00 - 9:30",type:"REUNION D'EQUIPE",atelier:"REUNION D'EQUIPE",lieu:"",fac1:"Sabryna",fac2:"ShivaChris",traduction:"",helper1:"",helper2:"",helper3:"",angel:"",note:"",logisticId:""},
  {jour:"Jour 6",date:"Jeudi 3 septembre",heure:"7:30 - 10:00",type:"REPAS & PAUSE",atelier:"PETIT DEJ",lieu:"",fac1:"",fac2:"",traduction:"",helper1:"",helper2:"",helper3:"",angel:"",note:"",logisticId:""},
  {jour:"Jour 6",date:"Jeudi 3 septembre",heure:"9:00 - 9:30",type:"PREPA & LOGITICS",atelier:"PREPARATION Rassemblement",lieu:"SHIVA",fac1:"",fac2:"",traduction:"",helper1:"Alexandre Fourcault",helper2:"Damien Eissen",helper3:"",angel:"",note:"",logisticId:""},
  {jour:"Jour 6",date:"Jeudi 3 septembre",heure:"9:45 - 11:00",type:"RASSEMBLEMENT",atelier:"Rassemblement",lieu:"SHIVA",fac1:"Clement Victor (Jivan Mutti)",fac2:"Matthieu Chapeleau (Atman)",traduction:"",helper1:"Alexandre Fourcault",helper2:"Damien Eissen",helper3:"",angel:"",note:"",logisticId:""},
  {jour:"Jour 6",date:"Jeudi 3 septembre",heure:"11:15 - 13:00",type:"ATELIERS TANTRA (AM)",atelier:"Alice : Incarnation (3/3) massage meditatif tantrique",lieu:"CHENREZIG",fac1:"Simone Bikene",fac2:"",traduction:"",helper1:"Mukti - Cecile Yvorel",helper2:"Cedric Vesper",helper3:"",angel:"Boris Desvignes",note:"",logisticId:""},
  {jour:"Jour 6",date:"Jeudi 3 septembre",heure:"11:15 - 13:00",type:"ATELIERS TANTRA (AM)",atelier:"Loving Leadership ",lieu:"SHAKTI",fac1:"Scott McClure",fac2:"",traduction:"",helper1:"Philippe Hanrion",helper2:"Alexandre Sattler",helper3:"",angel:"Boris Desvignes",note:"",logisticId:""},
  {jour:"Jour 6",date:"Jeudi 3 septembre",heure:"11:15 - 13:00",type:"ATELIERS TANTRA (AM)",atelier:"La Grande Spirale du COEUR ",lieu:"TARA",fac1:"Emmanuelle Cueff (Suman)",fac2:"",traduction:"",helper1:"Alexandre Roque - Bhaskar",helper2:"Yannick Bohrer",helper3:"",angel:"Boris Desvignes",note:"",logisticId:""},
  {jour:"Jour 6",date:"Jeudi 3 septembre",heure:"12:00 - 13:30",type:"TANTRA CAFÃ‰ & CONFERENCE",atelier:"Conference : Pour un tantra d'aujourd'hui ",lieu:"Ganesh",fac1:"Laurent Lacoste",fac2:"",traduction:"",helper1:"Emma Roussel",helper2:"Carine Janez",helper3:"",angel:"Boris Desvignes",note:"",logisticId:""},
  {jour:"Jour 6",date:"Jeudi 3 septembre",heure:"11:15 - 13:30",type:"ATELIERS TANTRA (AM)",atelier:"Angel - ATELIERS TANTRA (AM)",lieu:"",fac1:"",fac2:"",traduction:"",helper1:"",helper2:"",helper3:"",angel:"Boris Desvignes",note:"",logisticId:""},

  // ─── Jour 1 — Samedi 29 aout ────────────────────────────────────────
  {jour:"Jour 1",date:"Samedi 29 aout",heure:"11:00 - 13:30",type:"POOL PARTY",atelier:"TEST 5",lieu:"SHIVA",fac1:"",fac2:"",traduction:"",helper1:"",helper2:"",helper3:"",angel:"",note:"",logisticId:""},

  // ─── Jour 6 — Jeudi 3 septembre ─────────────────────────────────────
  {jour:"Jour 6",date:"Jeudi 3 septembre",heure:"12:30 - 14:30",type:"REPAS & PAUSE",atelier:"DEJEUNER",lieu:"",fac1:"",fac2:"",traduction:"",helper1:"",helper2:"",helper3:"",angel:"",note:"",logisticId:""},
  {jour:"Jour 6",date:"Jeudi 3 septembre",heure:"15:00 - 15:45",type:"REUNION D'EQUIPE",atelier:"REUNION D'EQUIPE (Helpers)",lieu:"",fac1:"Matthieu Chapeleau (Atman)",fac2:"Dorian Vallet",traduction:"",helper1:"",helper2:"",helper3:"",angel:"",note:"",logisticId:""},
  {jour:"Jour 6",date:"Jeudi 3 septembre",heure:"14:30 - 16:00",type:"SUPPORT EMOTIONNEL",atelier:"SUPPORT EMOTIONNEL",lieu:"Ganesh",fac1:"",fac2:"",traduction:"",helper1:"",helper2:"",helper3:"",angel:"Virginie Bertrand",note:"",logisticId:""},
  {jour:"Jour 6",date:"Jeudi 3 septembre",heure:"16.00 - 17.30",type:"ATELIERS TANTRA (PM)",atelier:"Contact meets Tantra",lieu:"SHIVA",fac1:"David Llorca",fac2:"",traduction:"",helper1:"Veronique Santini Bottemer",helper2:"Aurelie Lechardeur",helper3:"",angel:"Virginie Bertrand",note:"",logisticId:""},
  {jour:"Jour 6",date:"Jeudi 3 septembre",heure:"16.00 - 17.30",type:"ATELIERS TANTRA (PM)",atelier:"Voyage au pays de mon sexe ",lieu:"CHENREZIG",fac1:"Laurence Heitzmann",fac2:"Laurent Lacoste",traduction:"",helper1:"Daniel Latapie",helper2:"Alexandre Fourcault",helper3:"",angel:"Virginie Bertrand",note:"",logisticId:""},
  {jour:"Jour 6",date:"Jeudi 3 septembre",heure:"16.00 - 17.30",type:"ATELIERS TANTRA (PM)",atelier:"Mystic Shibari -The Art of Surrender",lieu:"SHAKTI",fac1:"Amana (William Duplain)",fac2:"",traduction:"",helper1:"Emma Roussel",helper2:"Alexandre Roque - Bhaskar",helper3:"",angel:"Virginie Bertrand",note:"",logisticId:""},
  {jour:"Jour 6",date:"Jeudi 3 septembre",heure:"16.00 - 17.30",type:"ATELIERS TANTRA (PM)",atelier:"Un bain de guerison Corps et Ame",lieu:"TARA",fac1:"Sophie O'Heix",fac2:"",traduction:"",helper1:"Yannick Bohrer",helper2:"Boris Desvignes",helper3:"",angel:"Virginie Bertrand",note:"",logisticId:""},
  {jour:"Jour 6",date:"Jeudi 3 septembre",heure:"16.00 - 17.30",type:"ATELIERS TANTRA (PM)",atelier:"Angel - ATELIERS TANTRA (PM)",lieu:"",fac1:"",fac2:"",traduction:"",helper1:"",helper2:"",helper3:"",angel:"Virginie Bertrand",note:"",logisticId:""},
  {jour:"Jour 6",date:"Jeudi 3 septembre",heure:"17.30 - 18.15",type:"REPAS & PAUSE",atelier:"GOUTER",lieu:"",fac1:"",fac2:"",traduction:"",helper1:"",helper2:"",helper3:"",angel:"",note:"",logisticId:""},
  {jour:"Jour 6",date:"Jeudi 3 septembre",heure:"18:00 - 19:30",type:"ATELIER ARTISTIQUE (PM)",atelier:"Atelier artistique « free your voice and movement playshop»",lieu:"SHIVA",fac1:"Mitsch Kohn",fac2:"",traduction:"",helper1:"Vera De Sousa",helper2:"Maeva Mantione",helper3:"",angel:"Aurelie Lechardeur",note:"",logisticId:""},
  {jour:"Jour 6",date:"Jeudi 3 septembre",heure:"18:00 - 19:30",type:"ATELIER ARTISTIQUE (PM)",atelier:"L'Art d'Etre en Mouvement ",lieu:"CHENREZIG",fac1:"Linda Stachetti",fac2:"",traduction:"",helper1:"Frederic Chalard",helper2:"Sevda Duroy",helper3:"",angel:"Aurelie Lechardeur",note:"Shift Colibri",logisticId:""},
  {jour:"Jour 6",date:"Jeudi 3 septembre",heure:"18:00 - 19:30",type:"ATELIER ARTISTIQUE (PM)",atelier:"Pranam : Danse Devotionnelle ",lieu:"SHAKTI",fac1:"Ishvari",fac2:"",traduction:"",helper1:"Cedric Vesper",helper2:"Philippe Hanrion",helper3:"",angel:"Aurelie Lechardeur",note:"",logisticId:""},
  {jour:"Jour 6",date:"Jeudi 3 septembre",heure:"18:00 - 19:30",type:"ATELIER ARTISTIQUE (PM)",atelier:"Bain Mantrique - Soin Sonore Collectif",lieu:"TARA",fac1:"Emmanuelle Cueff (Suman)",fac2:"",traduction:"",helper1:"Alexandre Sattler",helper2:"Veronique Santini Bottemer",helper3:"",angel:"Aurelie Lechardeur",note:"",logisticId:""},
  {jour:"Jour 6",date:"Jeudi 3 septembre",heure:"18:00 - 19:30",type:"ATELIER ARTISTIQUE (PM)",atelier:"Angel - ATELIER ARTISTIQUE (PM)",lieu:"",fac1:"",fac2:"",traduction:"",helper1:"",helper2:"",helper3:"",angel:"Aurelie Lechardeur",note:"",logisticId:""},
  {jour:"Jour 6",date:"Jeudi 3 septembre",heure:"19:00 - 20:30",type:"REPAS & PAUSE",atelier:"DINNER",lieu:"",fac1:"",fac2:"",traduction:"",helper1:"",helper2:"",helper3:"",angel:"",note:"",logisticId:""},
  {jour:"Jour 6",date:"Jeudi 3 septembre",heure:"20:30 - 21:00",type:"PREPA & LOGITICS",atelier:"PREPA CONCERT (SHIVA)",lieu:"SHIVA",fac1:"",fac2:"",traduction:"",helper1:"Mukti - Cecile Yvorel",helper2:"Alexandre Roque - Bhaskar",helper3:"",angel:"",note:"",logisticId:""},
  {jour:"Jour 6",date:"Jeudi 3 septembre",heure:"21:00 - 23:00",type:"CEREMONIE & CONCERT",atelier:"SOIREE SURPRISE pour enflammer le Chapiteau !",lieu:"SHIVA",fac1:"",fac2:"",traduction:"",helper1:"Carine Janez",helper2:"Veronique Santini Bottemer",helper3:"",angel:"Linda Stachetti",note:"",logisticId:""},
  {jour:"Jour 6",date:"Jeudi 3 septembre",heure:"21:00 - 22:00",type:"PREPA & LOGITICS",atelier:"PREPA TEMPLE (CHENREZIG)",lieu:"CHENREZIG",fac1:"",fac2:"",traduction:"",helper1:"Maeva Mantione",helper2:"Yannick Bohrer",helper3:"",angel:"",note:"",logisticId:""},
  {jour:"Jour 6",date:"Jeudi 3 septembre",heure:"23:30 - 01:00",type:"LOVE TEMPLE",atelier:"The temple of erotic innocence - An Oracular Night Ceremony",lieu:"CHENREZIG",fac1:"Our Echo",fac2:"Guy El Hadad - Israel",traduction:"",helper1:"Vera De Sousa",helper2:"Carine Janez",helper3:"",angel:"Daniel Latapie",note:"",logisticId:""},

  // ─── Jour 7 — Vendredi 4 septembre ──────────────────────────────────
  {jour:"Jour 7",date:"Vendredi 4 septembre",heure:"7:30 - 9:00",type:"MEDITATION / YOGA",atelier:"Yoga & automassages",lieu:"CHENREZIG",fac1:"Sevda Duroy",fac2:"",traduction:"",helper1:"Philippe Hanrion",helper2:"",helper3:"",angel:"",note:"",logisticId:""},
  {jour:"Jour 7",date:"Vendredi 4 septembre",heure:"7:30 - 9:00",type:"MEDITATION / YOGA",atelier:"A definir (yoga / meditation)",lieu:"SHAKTI",fac1:"",fac2:"",traduction:"",helper1:"Damien Eissen",helper2:"",helper3:"",angel:"",note:"",logisticId:""},
  {jour:"Jour 7",date:"Vendredi 4 septembre",heure:"9:00 - 9:30",type:"REUNION D'EQUIPE",atelier:"REUNION D'EQUIPE",lieu:"",fac1:"Sabryna",fac2:"ShivaChris",traduction:"",helper1:"",helper2:"",helper3:"",angel:"",note:"",logisticId:""},
  {jour:"Jour 7",date:"Vendredi 4 septembre",heure:"7:30 - 10:00",type:"REPAS & PAUSE",atelier:"PETIT DEJ",lieu:"",fac1:"",fac2:"",traduction:"",helper1:"",helper2:"",helper3:"",angel:"",note:"",logisticId:""},
  {jour:"Jour 7",date:"Vendredi 4 septembre",heure:"10:00 - 11:00",type:"CEREMONIE & CONCERT",atelier:"PREPARATION CEREMONIE DE CLOTURE",lieu:"SHIVA",fac1:"",fac2:"",traduction:"",helper1:"Cedric Vesper",helper2:"Philippe Hanrion",helper3:"Carine Janez",angel:"",note:"",logisticId:""},
  {jour:"Jour 7",date:"Vendredi 4 septembre",heure:"11:00 - 13:30",type:"CEREMONIE & CONCERT",atelier:"CEREMONIE DE CLOTURE",lieu:"SHIVA",fac1:"Sabryna",fac2:"ShivaChris",traduction:"",helper1:"Veronique Santini Bottemer",helper2:"Yannick Bohrer",helper3:"",angel:"",note:"",logisticId:""},
  {jour:"Jour 7",date:"Vendredi 4 septembre",heure:"12:30 - 14:30",type:"REPAS & PAUSE",atelier:"DEJEUNER",lieu:"",fac1:"",fac2:"",traduction:"",helper1:"",helper2:"",helper3:"",angel:"",note:"",logisticId:""},
  {jour:"Jour 7",date:"Vendredi 4 septembre",heure:"APRES MIDI",type:"REUNION D'EQUIPE",atelier:"REUNION D'EQUIPE - FINAL DEBRIEF",lieu:"",fac1:"Sabryna",fac2:"ShivaChris",traduction:"",helper1:"",helper2:"",helper3:"",angel:"",note:"",logisticId:""},
  {jour:"Jour 7",date:"Vendredi 4 septembre",heure:"APRES MIDI",type:"PREPA & LOGITICS",atelier:"RANGEMENT",lieu:"",fac1:"",fac2:"",traduction:"",helper1:"",helper2:"",helper3:"",angel:"",note:"",logisticId:""},
];

/**
 * Convertit un objet AGENDA en tableau positionnel [14 colonnes]
 * identique au format RAW utilisé par les rapports.
 * Indice : [0]jour [1]date [2]heure [3]type [4]atelier [5]lieu
 *          [6]fac1 [7]fac2 [8]traduction [9]helper1 [10]helper2
 *          [11]helper3 [12]angel [13]note
 */
function agendaToRaw(entries) {
  return entries.map(e => [
    e.jour, e.date, e.heure, e.type, e.atelier, e.lieu,
    e.fac1, e.fac2, e.traduction,
    e.helper1, e.helper2, e.helper3,
    e.angel, e.note
  ]);
}