/**
 * TANTRAMOUR 2026 — * Référentiel : Facilitateurs
 * Chaque entrée : { id, value }
 *   id    : clé unique (stable, ne jamais changer)
 *   value : nom exact tel qu'il apparaît dans AGENDA (champs fac1, fac2)
 */
const REF_FACILITATEURS = [
  { id: "F_ALICE", value: "Alice" },
  { id: "F_AMANA", value: "Amana (William Duplain)" },
  { id: "F_AUDREY", value: "Audrey Barthelemy" },
  { id: "F_BORIS", value: "Boris Desvignes" },
  { id: "F_BRUNO", value: "Bruno Deck" },
  { id: "F_CEDRIC", value: "Cedric Vesper" },
  { id: "F_CLAUDE", value: "Claude Brame" },
  { id: "F_CLEMENT", value: "Clement Victor (Jivan Mutti)" },
  { id: "F_DAMIEN", value: "Damien Eissen" },
  { id: "F_DANIEL", value: "Daniel Latapie" },
  { id: "F_DAVID", value: "David Llorca" },
  { id: "F_DORIAN", value: "Dorian Vallet" },
  { id: "F_EMMA", value: "Emma Roussel" },
  { id: "F_EMMANUELLE", value: "Emmanuelle Cueff (Suman)" },
  { id: "F_FELIX", value: "Felix Ardevol" },
  { id: "F_GUY", value: "Guy El Hadad - Israel" },
  { id: "F_HELENE", value: "Helene" },
  { id: "F_ISHVARI", value: "Ishvari" },
  { id: "F_JOE", value: "Joe Jam" },
  { id: "F_KELLY", value: "Kelly Aura" },
  { id: "F_LAURENT", value: "Laurent Lacoste" },
  { id: "F_LAURENCE", value: "Laurence Heitzmann" },
  { id: "F_LINDA", value: "Linda Stachetti" },
  { id: "F_MAHADEVI", value: "Mahadevi (Tina Defoy)" },
  { id: "F_MATTHIEU", value: "Matthieu Chapeleau (Atman)" },
  { id: "F_MITSCH", value: "Mitsch Kohn" },
  { id: "F_OUR_ECHO", value: "Our Echo" },
  { id: "F_PASCAL", value: "Pascal de Lacaze" },
  { id: "F_PAUL", value: "Paul Raj Amar" },
  { id: "F_PHILIPPE", value: "Philippe Hanrion" },
  { id: "F_SABRYNA", value: "Sabryna" },
  { id: "F_SAMANTHA", value: "Samantha Marvels" },
  { id: "F_SANDRINE", value: "Sandrine Bettinelli" },
  { id: "F_SCOTT", value: "Scott McClure" },
  { id: "F_SELMA", value: "Selma (Celine Laroche)" },
  { id: "F_SEVDA", value: "Sevda Duroy" },
  { id: "F_SHIVACHRIS", value: "ShivaChris" },
  { id: "F_SIMONE", value: "Simone Bikene" },
  { id: "F_SOPHIE", value: "Sophie O'Heix" },
  { id: "F_STEPHANE", value: "Stephane Ahmed" },
  { id: "F_VIRGINIE", value: "Virginie Bertrand" },
  { id: "F_YANNICK", value: "Yannick Bohrer" },
  { id: "F_NEW1", value: "RESOURCE TEST" },
];
