/**
 * TANTRAMOUR 2026 — Configuration de l'affichage des rapports
 * ============================================================
 * Permet d'activer/désactiver les rapports et de choisir leur section.
 */
var REF_DISPLAY_REPORTS = [
  {
    "id": "rep_programme",
    "title": "Programme Festival",
    "titleKey": "card_programme_title",
    "desc": "Ateliers publics par jour — descriptions & détails",
    "descKey": "card_programme_desc",
    "icon": "🎪",
    "url": "Rapport_Programme.html",
    "section": "DreamTeam",
    "showInDreamTeam": true,
    "active": true,
    "cardStyle": "background:#3b82d4;border-color:#3b82d4;color:#fff;",
    "iconStyle": "background:rgba(255,255,255,.2);border-color:rgba(255,255,255,.3);",
    "titleStyle": "color:#fff;",
    "descStyle": "color:rgba(255,255,255,.8);",
    "arrowStyle": "color:rgba(255,255,255,.7);",
    "isProtected": false,
    "order": 1
  },
  {
    "id": "rep_mon_planning_v2",
    "title": "Mon Planning V2",
    "titleKey": "card_mon_planning_v2_title",
    "desc": "Vue par ressource — détails ateliers, logistique, popup FR/EN",
    "descKey": "card_mon_planning_v2_desc",
    "icon": "📋",
    "url": "Rapport_Mon_Planning_V2.html",
    "section": "DreamTeam",
    "showInDreamTeam": true,
    "active": true,
    "cardStyle": "background:#fef9c3;border-color:#fde68a;color:#111;",
    "iconStyle": "background:rgba(255,255,255,.45);border-color:rgba(17,17,17,.12);",
    "titleStyle": "color:#111;",
    "descStyle": "color:rgba(17,17,17,.78);",
    "arrowStyle": "color:rgba(17,17,17,.7);",
    "isProtected": false,
    "order": 2
  },
  {
    "id": "rep_mon_agenda_simplifie",
    "title": "Mon Agenda Simplifié",
    "titleKey": "card_mon_agenda_simplifie_title",
    "desc": "Agenda visuel filtré par nom — couleur selon votre rôle dans chaque atelier",
    "descKey": "card_mon_agenda_simplifie_desc",
    "icon": "🗓️",
    "url": "Rapport_Mon_Agenda_Simplifie.html",
    "section": "DreamTeam",
    "showInDreamTeam": true,
    "active": true,
    "cardStyle": "background:#f0fdf4;border-color:#86efac;color:#111;",
    "iconStyle": "background:rgba(255,255,255,.6);border-color:#86efac;",
    "titleStyle": "color:#166534;",
    "descStyle": "color:#166534cc;",
    "arrowStyle": "color:#16a34a;",
    "isProtected": false,
    "order": 3
  },
  {
    "id": "rep_agenda_simplifie",
    "title": "Agenda Simplifié",
    "titleKey": "card_agenda_simplifie_title",
    "desc": "Vue calendrier par jour & lieu — tous les ateliers positionnés à l'heure",
    "descKey": "card_agenda_simplifie_desc",
    "icon": "🗓️",
    "url": "Rapport_Agenda_Simplifie.html",
    "section": "DreamTeam",
    "showInDreamTeam": false,
    "active": true,
    "cardStyle": "background:#fce7f3;border-color:#f9a8d4;color:#9d174d;",
    "iconStyle": "background:rgba(255,255,255,.6);border-color:#f9a8d4;",
    "titleStyle": "color:#9d174d;",
    "descStyle": "color:#be185d;",
    "arrowStyle": "color:#f472b6;",
    "isProtected": false,
    "order": 5
  },
  {
    "id": "rep_agenda_simplifie_salle",
    "title": "Agenda Simplifié par Salle",
    "titleKey": "card_agenda_simplifie_salle_title",
    "desc": "Vue calendrier par salle — tous les ateliers d'une salle positionnés à l'heure",
    "descKey": "card_agenda_simplifie_salle_desc",
    "icon": "🏛️",
    "url": "Rapport_Agenda_Simplifie_par_Salle.html",
    "section": "DreamTeam",
    "showInDreamTeam": false,
    "active": true,
    "cardStyle": "background:#fce7f3;border-color:#f9a8d4;color:#9d174d;",
    "iconStyle": "background:rgba(255,255,255,.6);border-color:#f9a8d4;",
    "titleStyle": "color:#9d174d;",
    "descStyle": "color:#be185d;",
    "arrowStyle": "color:#f472b6;",
    "isProtected": false,
    "order": 4
  },
  {
    "id": "rep_angels_shifts",
    "title": "Planning Angel",
    "titleKey": "card_angel_title",
    "desc": "Vue du planning des Angels ainsi que leur contact",
    "descKey": "card_angel_desc",
    "icon": "👼",
    "url": "Rapport_Angels_Shifts.html",
    "section": "DreamTeam",
    "showInDreamTeam": true,
    "active": true,
    "cardStyle": "border-color:#f9a8d4;",
    "iconStyle": "",
    "titleStyle": "",
    "descStyle": "",
    "arrowStyle": "",
    "isProtected": false,
    "order": 6
  },
  {
    "id": "rep_traducteurs",
    "title": "Planning Traducteurs",
    "titleKey": "card_traducteurs_title",
    "desc": "Vue par traducteur — shifts regroupés, filtres Jour/Traducteur",
    "descKey": "card_traducteurs_desc",
    "icon": "🌐",
    "url": "Rapport_Traducteurs.html",
    "section": "DreamTeam",
    "showInDreamTeam": true,
    "active": true,
    "cardStyle": "",
    "iconStyle": "",
    "titleStyle": "",
    "descStyle": "",
    "arrowStyle": "",
    "isProtected": false,
    "order": 7
  },
  {
    "id": "rep_colibri",
    "title": "Planning Colibri",
    "titleKey": "card_colibri_title",
    "desc": "Ateliers avec animateur ayant le rôle Shift Colibri",
    "descKey": "card_colibri_desc",
    "icon": "🐦",
    "url": "Rapport_Colibri.html",
    "section": "DreamTeam",
    "showInDreamTeam": true,
    "active": true,
    "cardStyle": "border-color:#c4b5fd;",
    "iconStyle": "",
    "titleStyle": "",
    "descStyle": "",
    "arrowStyle": "",
    "isProtected": false,
    "order": 8
  },
  {
    "id": "rep_news",
    "title": "NEWS",
    "titleKey": "card_news_title",
    "desc": "Publier & gérer les messages importants DreamTeam et Festivaliers",
    "descKey": "card_news_desc",
    "icon": "📢",
    "url": "Rapport_News.html",
    "section": "Admin",
    "showInDreamTeam": false,
    "active": true,
    "cardStyle": "background:#7c3aed;border-color:#7c3aed;color:#fff;",
    "iconStyle": "background:rgba(255,255,255,.2);border-color:rgba(255,255,255,.3);",
    "titleStyle": "color:#fff;",
    "descStyle": "color:rgba(255,255,255,.8);",
    "arrowStyle": "color:rgba(255,255,255,.7);",
    "isProtected": false,
    "order": 1
  },
  {
    "id": "rep_saisie_ateliers",
    "title": "Saisie des Ateliers",
    "titleKey": "card_saisie_ateliers_title",
    "desc": "Saisir descriptions FR/EN, niveau piment, consignes et besoins logistiques",
    "descKey": "card_saisie_ateliers_desc",
    "icon": "📋",
    "url": "Rapport_Saisie_Ateliers.html",
    "section": "Logistique",
    "showInDreamTeam": false,
    "active": false,
    "cardStyle": "background:#ca8a04;border-color:#ca8a04;color:#fff;",
    "iconStyle": "background:rgba(255,255,255,.2);border-color:rgba(255,255,255,.3);",
    "titleStyle": "color:#fff;",
    "descStyle": "color:rgba(255,255,255,.8);",
    "arrowStyle": "color:rgba(255,255,255,.7);",
    "isProtected": false,
    "order": 5
  },
  {
    "id": "rep_editer_atelier",
    "title": "Éditer un atelier",
    "titleKey": "card_editer_title",
    "desc": "Sélectionnez un atelier et modifiez ses champs en direct",
    "descKey": "card_editer_desc",
    "icon": "✏️",
    "url": "Rapport_Editer_Atelier.html",
    "section": "Gestion planning",
    "showInDreamTeam": false,
    "active": true,
    "cardStyle": "background:#4b5563;border-color:#374151;color:#fff;",
    "iconStyle": "background:rgba(255,255,255,.15);border-color:rgba(255,255,255,.25);",
    "titleStyle": "color:#fff;",
    "descStyle": "color:rgba(255,255,255,.8);",
    "arrowStyle": "color:rgba(255,255,255,.6);",
    "isProtected": true,
    "order": 1
  },
  {
    "id": "rep_agenda_jour",
    "title": "Planning par Jour",
    "titleKey": "card_agenda_jour_title",
    "desc": "Tous les ateliers — filtres jour, lieu, rôle",
    "descKey": "card_agenda_jour_desc",
    "icon": "📅",
    "url": "Rapport_Agenda_par_Jour.html",
    "section": "Gestion planning",
    "showInDreamTeam": false,
    "active": true,
    "cardStyle": "",
    "iconStyle": "",
    "titleStyle": "",
    "descStyle": "",
    "arrowStyle": "",
    "isProtected": false,
    "order": 4
  },
  {
    "id": "rep_gerer_ressources",
    "title": "Gérer les Ressources",
    "titleKey": "card_ressources_title",
    "desc": "Animateurs, Helpers, Traducteurs, Angels — référentiel unifié éditable",
    "descKey": "card_ressources_desc",
    "icon": "👥",
    "url": "Rapport_Gerer_Ressources.html",
    "section": "Admin",
    "showInDreamTeam": false,
    "active": true,
    "cardStyle": "border-color:#86efac;",
    "iconStyle": "",
    "titleStyle": "",
    "descStyle": "",
    "arrowStyle": "",
    "isProtected": true,
    "order": 3
  },
  {
    "id": "rep_remplacement_ressource",
    "title": "Remplacement de Ressource",
    "titleKey": "card_remplacement_title",
    "desc": "Personne indisponible — proposition automatique de remplaçants sans conflit",
    "descKey": "card_remplacement_desc",
    "icon": "🔄",
    "url": "Rapport_Remplacement_Ressource.html",
    "section": "Admin",
    "showInDreamTeam": false,
    "active": false,
    "cardStyle": "border-color:#fca5a5;",
    "iconStyle": "",
    "titleStyle": "",
    "descStyle": "",
    "arrowStyle": "",
    "isProtected": true,
    "order": 9
  },
  {
    "id": "rep_trad_affectation",
    "title": "Affectation Traducteur",
    "titleKey": "card_trad_affect_title",
    "desc": "Ateliers anglophones sans traducteur — détection TBC et affectation guidée",
    "descKey": "card_trad_affect_desc",
    "icon": "🌐✅",
    "url": "Rapport_Traducteur_Affectation.html",
    "section": "Gestion planning",
    "showInDreamTeam": false,
    "active": false,
    "cardStyle": "border-color:#c4b5fd;",
    "iconStyle": "",
    "titleStyle": "",
    "descStyle": "",
    "arrowStyle": "",
    "isProtected": true,
    "order": 5
  },
  {
    "id": "rep_besoins_equipements",
    "title": "Besoins Équipements",
    "titleKey": "card_besoins_eq_title",
    "desc": "Tableau de bord des équipements demandés par atelier — filtres, tri, export",
    "descKey": "card_besoins_eq_desc",
    "icon": "🔩",
    "url": "Rapport_Besoins_Equipements.html",
    "section": "Logistique",
    "showInDreamTeam": false,
    "active": false,
    "cardStyle": "background:#0f766e;border-color:#0f766e;color:#fff;",
    "iconStyle": "background:rgba(255,255,255,.2);border-color:rgba(255,255,255,.3);",
    "titleStyle": "color:#fff;",
    "descStyle": "color:rgba(255,255,255,.8);",
    "arrowStyle": "color:rgba(255,255,255,.7);",
    "isProtected": false,
    "order": 3
  },
  {
    "id": "rep_stock_equipements_lieux",
    "title": "Stock & Équipements par Lieu",
    "titleKey": "card_stock_eq_lieux_title",
    "desc": "Gestion des stocks face aux pics demandés par salle & alertes de dépassement",
    "descKey": "card_stock_eq_lieux_desc",
    "icon": "🏛️",
    "url": "Rapport_Stock_Equipements_Lieux.html",
    "section": "Logistique",
    "showInDreamTeam": false,
    "active": true,
    "cardStyle": "background:#0d9488;border-color:#0d9488;color:#fff;",
    "iconStyle": "background:rgba(255,255,255,.2);border-color:rgba(255,255,255,.3);",
    "titleStyle": "color:#fff;",
    "descStyle": "color:rgba(255,255,255,.8);",
    "arrowStyle": "color:rgba(255,255,255,.7);",
    "isProtected": false,
    "order": 5
  },
  {
    "id": "rep_infos_ateliers",
    "title": "Informations Ateliers",
    "titleKey": "card_ria_title",
    "desc": "Consignes, besoins logistiques et infos pour helpers et intervenants",
    "descKey": "card_ria_desc",
    "icon": "ℹ️",
    "url": "Rapport_Informations_Ateliers.html",
    "section": "Gestion planning",
    "showInDreamTeam": false,
    "active": true,
    "cardStyle": "background:#16a34a;border-color:#16a34a;color:#fff;",
    "iconStyle": "background:rgba(255,255,255,.2);border-color:rgba(255,255,255,.3);",
    "titleStyle": "color:#fff;",
    "descStyle": "color:rgba(255,255,255,.8);",
    "arrowStyle": "color:rgba(255,255,255,.7);",
    "isProtected": false,
    "order": 3
  },
  {
    "id": "rep_transform_upload",
    "title": "Transform & Upload",
    "titleKey": "card_transform_upload_title",
    "desc": "Convertir les fiches animateurs en fichier logistique consolidé (.xlsx)",
    "descKey": "card_transform_upload_desc",
    "icon": "🔄",
    "url": "TRANSFORM_UPLOAD.html",
    "section": "Gestion planning",
    "showInDreamTeam": false,
    "active": true,
    "cardStyle": "background:#0f766e;border-color:#0f766e;color:#fff;",
    "iconStyle": "background:rgba(255,255,255,.2);border-color:rgba(255,255,255,.3);",
    "titleStyle": "color:#fff;",
    "descStyle": "color:rgba(255,255,255,.8);",
    "arrowStyle": "color:rgba(255,255,255,.7);",
    "isProtected": false,
    "order": 2
  },
  {
    "id": "rep_log_speciale",
    "title": "Logistique Spéciale",
    "titleKey": "card_log_spec_title",
    "desc": "Tous les besoins logistiques spéciaux renseignés par les animateurs",
    "descKey": "card_log_spec_desc",
    "icon": "⭐",
    "url": "Rapport_Logistique_Speciale.html",
    "section": "Logistique",
    "showInDreamTeam": false,
    "active": false,
    "cardStyle": "border-color:#c4b5fd;",
    "iconStyle": "",
    "titleStyle": "",
    "descStyle": "",
    "arrowStyle": "",
    "isProtected": true,
    "order": 4
  },
  {
    "id": "rep_conflits",
    "title": "Conflits de planning",
    "titleKey": "card_conflits_title",
    "desc": "Personnes assignées à plusieurs rôles simultanément",
    "descKey": "card_conflits_desc",
    "icon": "⚠️",
    "url": "Rapport_Conflits.html",
    "section": "Contrôle & Vérification",
    "showInDreamTeam": false,
    "active": true,
    "cardStyle": "",
    "iconStyle": "",
    "titleStyle": "",
    "descStyle": "",
    "arrowStyle": "",
    "isProtected": true,
    "order": 2
  },
  {
    "id": "rep_charge_travail",
    "title": "Charge de travail (Workload)",
    "titleKey": "card_charge_title",
    "desc": "Helpers & Angels — nombre d'ateliers, durée, harmonisation",
    "descKey": "card_charge_desc",
    "icon": "⚖️",
    "url": "Rapport_Charge_Travail.html",
    "section": "Contrôle & Vérification",
    "showInDreamTeam": false,
    "active": true,
    "cardStyle": "background:#7c3aed;border-color:#6d28d9;color:#fff;",
    "iconStyle": "background:rgba(255,255,255,.15);border-color:rgba(255,255,255,.25);",
    "titleStyle": "color:#fff;",
    "descStyle": "color:rgba(255,255,255,.8);",
    "arrowStyle": "color:rgba(255,255,255,.6);",
    "isProtected": true,
    "order": 1
  },
  {
    "id": "rep_problemes",
    "title": "Problèmes de planning",
    "titleKey": "card_problemes_title",
    "desc": "Ateliers anglophones sans traducteur · Ressources insuffisantes — correction inline",
    "descKey": "card_problemes_desc",
    "icon": "🚨",
    "url": "Rapport_Problemes.html",
    "section": "Contrôle & Vérification",
    "showInDreamTeam": false,
    "active": true,
    "cardStyle": "border-color:#fca5a5;",
    "iconStyle": "",
    "titleStyle": "",
    "descStyle": "",
    "arrowStyle": "",
    "isProtected": true,
    "order": 3
  },
  {
    "id": "rep_desc_manquantes",
    "title": "Descriptions manquantes",
    "titleKey": "card_desc_manq_title",
    "desc": "Ateliers sans description FR ou EN — suivi et accès direct à l'éditeur",
    "descKey": "card_desc_manq_desc",
    "icon": "📋",
    "url": "Rapport_Descriptions_Manquantes.html",
    "section": "Contrôle & Vérification",
    "showInDreamTeam": false,
    "active": false,
    "cardStyle": "border-color:#fcd34d;",
    "iconStyle": "",
    "titleStyle": "",
    "descStyle": "",
    "arrowStyle": "",
    "isProtected": true,
    "order": 4
  },
  {
    "id": "rep_log_manquante",
    "title": "Logistique manquante",
    "titleKey": "card_log_manq_title",
    "desc": "Ateliers sans info logistique ou non validés par les animateurs",
    "descKey": "card_log_manq_desc",
    "icon": "📦",
    "url": "Rapport_Logistique_Manquante.html",
    "section": "Contrôle & Vérification",
    "showInDreamTeam": false,
    "active": false,
    "cardStyle": "border-color:#fca5a5;",
    "iconStyle": "",
    "titleStyle": "",
    "descStyle": "",
    "arrowStyle": "",
    "isProtected": true,
    "order": 5
  },
  {
    "id": "rep_gestion_affichage",
    "title": "Gestion Affichage",
    "titleKey": "card_gestion_affichage_title",
    "desc": "Organiser, activer ou déplacer les rapports dans les sections",
    "descKey": "card_gestion_affichage_desc",
    "icon": "🎛️",
    "url": "Rapport_Gestion_Affichage.html",
    "section": "Admin",
    "showInDreamTeam": false,
    "active": true,
    "cardStyle": "background:#1e3a8a;border-color:#1e3a8a;color:#fff;",
    "iconStyle": "background:rgba(255,255,255,.2);border-color:rgba(255,255,255,.3);",
    "titleStyle": "color:#fff;",
    "descStyle": "color:rgba(255,255,255,.8);",
    "arrowStyle": "color:rgba(255,255,255,.7);",
    "isProtected": true,
    "order": 5
  },
  {
    "id": "rep_admin",
    "title": "Admin",
    "titleKey": "nav_admin",
    "desc": "Paramètres globaux et administration de l'application",
    "descKey": "card_admin_desc",
    "icon": "⚙️",
    "url": "Admin.html",
    "section": "Admin",
    "showInDreamTeam": false,
    "active": false,
    "cardStyle": "border-color:#94a3b8;",
    "iconStyle": "",
    "titleStyle": "",
    "descStyle": "",
    "arrowStyle": "",
    "isProtected": true,
    "order": 6
  },
  {
    "id": "rep_master_data",
    "title": "Master Data",
    "titleKey": "nav_masterdata",
    "desc": "Gestion des référentiels de données (Lieux, Équipements, Consignes, etc.)",
    "descKey": "card_masterdata_desc",
    "icon": "🗂",
    "url": "MasterData.html",
    "section": "Admin",
    "showInDreamTeam": false,
    "active": true,
    "cardStyle": "border-color:#94a3b8;",
    "iconStyle": "",
    "titleStyle": "",
    "descStyle": "",
    "arrowStyle": "",
    "isProtected": true,
    "order": 2
  },
  {
    "id": "rep_manuel",
    "title": "Manuel utilisateur",
    "titleKey": "nav_manuel",
    "desc": "Guide d'utilisation complet de la plateforme",
    "descKey": "card_manuel_desc",
    "icon": "📖",
    "url": "user-manual.html",
    "section": "Admin",
    "showInDreamTeam": false,
    "active": true,
    "cardStyle": "border-color:#94a3b8;",
    "iconStyle": "",
    "titleStyle": "",
    "descStyle": "",
    "arrowStyle": "",
    "isProtected": false,
    "order": 7
  },
  {
    "id": "rep_regles",
    "title": "Règles & Documentation",
    "titleKey": "nav_regles",
    "desc": "Spécifications métier et règles de gestion du festival",
    "descKey": "card_regles_desc",
    "icon": "📐",
    "url": "Rapport_Regles.html",
    "section": "Admin",
    "showInDreamTeam": false,
    "active": true,
    "cardStyle": "border-color:#94a3b8;",
    "iconStyle": "",
    "titleStyle": "",
    "descStyle": "",
    "arrowStyle": "",
    "isProtected": false,
    "order": 8
  }
];
