/**
 * TANTRAMOUR 2026 — Référentiel : Équipements
 * Chaque entrée : { id, value, type, categorie, stock, description, remarque }
 *   value       : nom de l'équipement
 *   type        : "Hameau" | "Tantramour" | "Animateur" | "Autre" (fournisseur)
 *   categorie   : nom de la catégorie — géré via ref_equip_cat.js (REF_EQUIP_CAT)
 *   stock       : nombre (0-1000) ou "N/A"
 *   description : texte libre
 *   remarque    : texte libre
 */
var REF_EQUIPEMENTS = [
  { type: "Hameau", categorie: "Pratique", id: "EQ_MAT", value: "Tapis de Yoga", stock: 141, description: "Tapis de Yoga", remarque: "" },
  { type: "Hameau", categorie: "Pratique", id: "EQ_BRIC", value: "Brique de yoga", stock: 34, description: "Brique de yoga", remarque: "" },
  { type: "Hameau", categorie: "Pratique", id: "EQ_COUSIN", value: "Cousin", stock: 360, description: "Cousin", remarque: "" },
  { type: "Hameau", categorie: "Pratique", id: "EQ_MATELAS", value: "Matelas", stock: 169, description: "Matelas", remarque: "" },
  { type: "Hameau", categorie: "Animation", id: "EQ_MICCASQUE", value: "Micro Casque", stock: "N/A", description: "Micro Casque", remarque: "" },
  { type: "Hameau", categorie: "Mobilier & aménagement", id: "EQ_CHAISE", value: "Chaise", stock: 246, description: "Chaise", remarque: "" },
  { type: "Hameau", categorie: "Mobilier & aménagement", id: "EQ_TABLE", value: "Table", stock: "N/A", description: "Table", remarque: "" },
  { type: "Hameau", categorie: "Animation", id: "EQ_BOARD", value: "Paperboard", stock: 12, description: "Paperboard", remarque: "" },
  { type: "Hameau", categorie: "Mobilier & aménagement", id: "EQ_MIROIR", value: "Miroir", stock: 1, description: "Miroir", remarque: "" },
  { type: "Hameau", categorie: "Cuisine", id: "EQ_SALADIER", value: "Saladier", stock: "N/A", description: "Saladier", remarque: "" },
  { type: "Hameau", categorie: "Hygiène & entretien", id: "EQ_SERVIETTE", value: "Serviettes de toilette", stock: "N/A", description: "Serviettes de toilette", remarque: "" },
  { type: "Hameau", categorie: "Cuisine", id: "EQ_BASSINE", value: "Bassine", stock: "N/A", description: "Bassine", remarque: "" },
  { type: "Hameau", categorie: "Cuisine", id: "EQ_PAN", value: "Casserol", stock: "N/A", description: "Casserol", remarque: "" },
  { type: "Hameau", categorie: "Cuisine", id: "EQ_LOUCHE", value: "Louche", stock: "N/A", description: "Louche", remarque: "" },
  { type: "Tantramour", categorie: "Ambiance & décoration", id: "EQ_SPOT", value: "SPOT (Lumiere)", stock: "N/A", description: "SPOT (Lumiere)", remarque: "" },
  { type: "Tantramour", categorie: "Hygiène & entretien", id: "EQ_LINGETTE", value: "Lingette humide", stock: "N/A", description: "Lingette humide", remarque: "" },
  { type: "Tantramour", categorie: "Hygiène & entretien", id: "EQ_MOUCHOIR", value: "Boite Mouchoirs", stock: "N/A", description: "Boite Mouchoirs", remarque: "" },
  { type: "Tantramour", categorie: "Hygiène & entretien", id: "EQ_TALC", value: "Talc", stock: "N/A", description: "Talc", remarque: "" },
  { type: "Tantramour", categorie: "Hygiène & entretien", id: "EQ_COCO", value: "Huile de coco", stock: "N/A", description: "Huile de coco", remarque: "" },
  { type: "Tantramour", categorie: "Ambiance & décoration", id: "EQ_COUPELLE", value: "Petite coupelle", stock: "N/A", description: "Petite coupelle", remarque: "" },
  { type: "Tantramour", categorie: "Ambiance & décoration", id: "EQ_CHAUFPLAT", value: "Bougie chauffe plat", stock: "N/A", description: "Bougie chauffe plat", remarque: "" },
  { type: "Tantramour", categorie: "Ambiance & décoration", id: "EQ_BOUGIE", value: "Bougie", stock: "N/A", description: "Bougie", remarque: "" },
  { type: "Tantramour", categorie: "Ambiance & décoration", id: "EQ_BRIQUET", value: "Briquet", stock: "N/A", description: "Briquet", remarque: "" },
  { type: "Tantramour", categorie: "Ambiance & décoration", id: "EQ_LEDSMALL", value: "Bougie LED (petite)", stock: "N/A", description: "Bougie LED (petite)", remarque: "" },
  { type: "Tantramour", categorie: "Ambiance & décoration", id: "EQ_LEDBIG", value: "Bougie LED (Grande)", stock: "N/A", description: "Bougie LED (Grande)", remarque: "" },
  { type: "Tantramour", categorie: "Consommables & fournitures", id: "EQ_PAPIER", value: "Paquet de papier", stock: "N/A", description: "Paquet de papier", remarque: "" },
  { type: "Tantramour", categorie: "Consommables & fournitures", id: "EQ_PEN", value: "Crayon", stock: "N/A", description: "Crayon", remarque: "" },
  { type: "Tantramour", categorie: "Ambiance & décoration", id: "EQ_PALO", value: "Palo Santo", stock: "N/A", description: "Palo Santo", remarque: "" },
  { type: "Tantramour", categorie: "Hygiène & entretien", id: "EQ_MASQUE", value: "Masque", stock: "N/A", description: "Masque", remarque: "" },
  { type: "Hameau", categorie: "Animation", id: "EQ_MICSS", value: "Micro Sans Fil", stock: "N/A", description: "Micro Sans Fil", remarque: "" },
  { type: "Hameau", categorie: "Animation", id: "EQ_MIC", value: "Micro (cable) - Tonor", stock: 1, description: "Micro avec cable", remarque: "" },
  { type: "Animateur", categorie: "Ambiance & décoration", id: "EQ_TENTURE", value: "Tenture", stock: "N/A", description: "Tenture", remarque: "" },
  { type: "Animateur", categorie: "Animation", id: "EQ_TAMBOUR", value: "Tambour", stock: "N/A", description: "Tambour", remarque: "" },
  { type: "Animateur", categorie: "Pratique", id: "EQ_CLOCHETTE", value: "Clochette", stock: "N/A", description: "Clochette", remarque: "" },
  { type: "Tantramour", categorie: "Animation", id: "EQ_ROSER", value: "Rose rouge", stock: "N/A", description: "Rose rouge", remarque: "A ACHETER" },
  { type: "Tantramour", categorie: "Animation", id: "EQ_ROSEB", value: "Rose Blanche", stock: "N/A", description: "Rose Blanche", remarque: "A ACHETER" },
  { type: "Tantramour", categorie: "Animation", id: "EQ_FLEUR", value: "Bouquet de fleur (DIVERS)", stock: "N/A", description: "Bouquet de fleur (DIVERS)", remarque: "A ACHETER" },
  { type: "Tantramour", categorie: "Animation", id: "EQ_ROSES", value: "Bouquet de ROSES", stock: "N/A", description: "Bouquet de ROSES", remarque: "A ACHETER" },
  { type: "Tantramour", categorie: "Animation", id: "EQ_PIEDMIC", value: "Pied Micro", stock: "N/A", description: "Pied Micro + pince micro", remarque: "Demander à Felix" },
  { type: "NEW", categorie: "Divers", id: "EQ_NEW01", value: "hfdg", stock: 0, description: "dfhf", remarque: "" },
  { type: "Tantramour", categorie: "Pratique", id: "EQ_GLACON", value: "Glacons (Kg)", stock: "N/A", description: "Paquet de glacons", remarque: "A ACHETER" },
  { type: "Tantramour", categorie: "Pratique", id: "EQ_PISCINE", value: "Piscine gonflable", stock: "N/A", description: "Piscine gonflable", remarque: "" },
  { type: "Hameau", categorie: "Mobilier & aménagement", id: "EQ_NEW000", value: "Table mange debout", stock: 3, description: "Table \"mange debout\"", remarque: "Table \"mange debout\"" },
  { type: "Hameau", categorie: "Animation", id: "EQ_NEW001", value: "Pied Micro (Hameau)", stock: 4, description: "Pied Micro (Hameau)", remarque: "" },
  { type: "Hameau", categorie: "Animation", id: "EQ_NEW002", value: "Récepteur Bluetooth", stock: 4, description: "Récepteur Bluetooth", remarque: "Récepteur Bluetooth" },
  { type: "Hameau", categorie: "Mobilier & aménagement", id: "EQ_NEW003", value: "Fauteuil osier", stock: 6, description: "Fauteuil osier", remarque: "" },
  { type: "Hameau", categorie: "Mobilier & aménagement", id: "EQ_NEW004", value: "Fauteuil blanc", stock: 8, description: "Fauteuil blanc", remarque: "" },
  { type: "Hameau", categorie: "Animation", id: "EQ_NEW005", value: "Bobseat", stock: 10, description: "Bobseat", remarque: "" },
  { type: "Hameau", categorie: "Mobilier & aménagement", id: "EQ_NEW006", value: "Grande table pliante #2 (183 cm)", stock: 10, description: "Grande table pliante #2 (183 cm)", remarque: "Grande table pliante grise (183cm/76cm/73cm hauteur)" },
  { type: "Hameau", categorie: "Mobilier & aménagement", id: "EQ_NEW007", value: "Petite Table", stock: 15, description: "Petite Table", remarque: "petite table noire carrée" },
  { type: "Hameau", categorie: "Mobilier & aménagement", id: "EQ_NEW008", value: "TISSUS murs - Tentures", stock: 16, description: "TISSUS murs - Tentures", remarque: "TISSUS murs - Tentures" },
  { type: "Hameau", categorie: "Mobilier & aménagement", id: "EQ_NEW009", value: "Tables de Massage", stock: 29, description: "Tables de Massage", remarque: "Tables de Massage" },
  { type: "Hameau", categorie: "Animation", id: "EQ_NEW010", value: "Zafou", stock: 32, description: "Zafu", remarque: "" },
  { type: "Hameau", categorie: "Mobilier & aménagement", id: "EQ_NEW011", value: "Grande table pliante #1 (122 cm)", stock: 58, description: "Grande table pliante #1 (122 cm)", remarque: "Table grise pliante  (122cm/60cm/74cm hauteur)" },
  { type: "Tantramour", categorie: "Ambiance & décoration", id: "EQ_NEW02", value: "Encens", stock: 0, description: "Encens", remarque: "" },
  { type: "Tantramour", categorie: "Animation", id: "EQ_NEW03", value: "Masque", stock: 0, description: "Masque", remarque: "" },
  { type: "Autre", categorie: "Animation", id: "TEST_EQMATT", value: "TEST ITEM UPLAOD", stock: 56, description: "TEST ITEM UPLAOD", remarque: "" },
];
